
* To get texts for tax codes.
CLEAR TAX_TEXT.

DATA: BEGIN OF COMP_DATA,
LAND1 LIKE T001-LAND1,
SPRAS LIKE T001-SPRAS,
END OF COMP_DATA.

DATA: ZKALSM LIKE T005-KALSM.

*GS_IT_KOND_TX_W-KBETR = GS_IT_KOND_TX_W-KBETR * -1.

TX_RATE = GS_IT_KOND_TX_W-KBETR.
TX_RATE = TX_RATE / 10.

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE LAND1 SPRAS FROM T001 INTO CORRESPONDING FIELDS OF
*COMP_DATA
*WHERE BUKRS = IS_BIL_INVOICE-HD_ORG-COMP_CODE.
*
* NEW CODE
SELECT LAND1 SPRAS
UP TO 1 ROWS  FROM T001 INTO CORRESPONDING FIELDS OF
COMP_DATA
WHERE BUKRS = IS_BIL_INVOICE-HD_ORG-COMP_CODE ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE KALSM FROM T005 INTO ZKALSM WHERE LAND1 = COMP_DATA-LAND1.
*
* NEW CODE
SELECT KALSM
UP TO 1 ROWS  FROM T005 INTO ZKALSM WHERE LAND1 = COMP_DATA-LAND1 ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

*SELECT SINGLE TEXT1 FROM T007S INTO TAX_TEXT1 WHERE
*           SPRAS = COMP_DATA-SPRAS AND
*           KALSM = ZKALSM AND
*           MWSKZ = GS_HD_KOND_W-MWSKZ.

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE TEXT1 FROM T007S INTO TAX_TEXT WHERE
*SPRAS = IS_NAST-SPRAS AND
*KALSM = ZKALSM AND
*MWSKZ = GS_IT_KOND_TX_W-MWSKZ.
*
* NEW CODE
SELECT TEXT1
UP TO 1 ROWS  FROM T007S INTO TAX_TEXT WHERE
SPRAS = IS_NAST-SPRAS AND
KALSM = ZKALSM AND
MWSKZ = GS_IT_KOND_TX_W-MWSKZ ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

IF SY-SUBRC <> 0.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE TEXT1 FROM T007S INTO TAX_TEXT WHERE
*SPRAS = COMP_DATA-SPRAS AND
*KALSM = ZKALSM AND
*MWSKZ = GS_IT_KOND_TX_W-MWSKZ.
*
* NEW CODE
SELECT TEXT1
UP TO 1 ROWS  FROM T007S INTO TAX_TEXT WHERE
SPRAS = COMP_DATA-SPRAS AND
KALSM = ZKALSM AND
MWSKZ = GS_IT_KOND_TX_W-MWSKZ ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
ENDIF.

