DATA LS_MARA TYPE MARA.

TYPES: BEGIN OF T_HTNMAT.
INCLUDE STRUCTURE V_HTNM.
TYPES:
REVLV LIKE RAMPL-REVLV,
END OF T_HTNMAT.

DATA LT_HTNMAT TYPE TABLE OF T_HTNMAT.
DATA LS_HTNMAT TYPE T_HTNMAT.

DATA LT_HTNAMP TYPE TABLE OF RAMPL.
DATA LS_HTNAMP TYPE RAMPL.

DATA: LS_TMPPF TYPE TMPPF.

** Structure LFA1_KEY: Key for table LFA1 for mass access
DATA  LT_HERST TYPE TABLE OF LFA1_KEY.
DATA  LS_HERST TYPE LFA1_KEY.

** Table LFA1 : Vendor Master (General Section) **
DATA  LT_LFA1  TYPE TABLE OF LFA1.
DATA  LS_LFA1  TYPE LFA1.

DATA:  L_VORGA LIKE T160-VORGA,
L_MTCOM LIKE MTCOM,
L_MT06E LIKE MT06E,
L_MTCOR LIKE MTCOR.

DATA: L_MPN TYPE TY_HTNM.
CLEAR GT_MPN.
*--------------------------------------------------*
REFRESH: LT_HTNMAT, LT_HTNAMP.
IF NOT ( <FS>-MATNR EQ SPACE AND <FS>-EMATN EQ SPACE ).
IF <FS>-MFRPN IS INITIAL AND NOT <FS>-MPROF IS INITIAL.
CALL FUNCTION 'MB_SEARCH_HTN_MATERIAL'
EXPORTING
I_EMATN          = <FS>-EMATN
I_BMATN          = <FS>-MATNR
I_MPROF          = <FS>-MPROF
I_WERKS          = <FS>-WERKS
I_DATUV          = SY-DATUM
TABLES
E_HTNMAT         = LT_HTNMAT
E_HTNAMP         = LT_HTNAMP
EXCEPTIONS
NO_RECORDS_FOUND = 1
OTHERS           = 2.
ELSEIF NOT <FS>-MFRPN IS INITIAL.

CALL FUNCTION 'MB_READ_TMPPF'
EXPORTING
PROFILE        = <FS>-MPROF
IMPORTING
MPN_PARAMETERS = LS_TMPPF
EXCEPTIONS
NO_ENTRY       = 1
OTHERS         = 2.

IF NOT LS_TMPPF-MPAMP IS INITIAL.
CALL FUNCTION 'MB_SEARCH_HTN_MATERIAL'
EXPORTING
I_EMATN          = <FS>-EMATN
I_BMATN          = <FS>-MATNR
I_MPROF          = <FS>-MPROF
I_WERKS          = <FS>-WERKS
I_DATUV          = SY-DATUM
I_REVLV          = <FS>-REVLV
TABLES
E_HTNMAT         = LT_HTNMAT
E_HTNAMP         = LT_HTNAMP
EXCEPTIONS
NO_RECORDS_FOUND = 1
OTHERS           = 2.
ENDIF.
REFRESH  LT_HTNMAT.
CLEAR    LS_HTNMAT.
IF NOT LT_HTNAMP[] IS INITIAL.
LOOP AT LT_HTNAMP INTO LS_HTNAMP.
LS_HTNMAT-MFRPN = <FS>-MFRPN.
IF NOT <FS>-EMNFR IS INITIAL.
LS_HTNMAT-EMNFR = <FS>-EMNFR.
ELSE.
LS_HTNMAT-EMNFR = <FS>-MFRNR.
ENDIF.
LS_HTNMAT-MFRNR = LS_HTNAMP-MFRNR.
LS_HTNMAT-REVLV = LS_HTNAMP-REVLV.
LS_HTNMAT-MATNR = <FS>-EMATN.
APPEND LS_HTNMAT TO LT_HTNMAT.
ENDLOOP.
CLEAR   LS_HTNAMP.
REFRESH LT_HTNAMP.
ELSE.
LS_HTNMAT-MFRPN = <FS>-MFRPN.
IF NOT <FS>-EMNFR IS INITIAL.
LS_HTNMAT-EMNFR = <FS>-EMNFR.
ELSE.
LS_HTNMAT-EMNFR = <FS>-MFRNR.
ENDIF.
LS_HTNMAT-REVLV = <FS>-REVLV.       "Revisionslevel
LS_HTNMAT-MATNR = <FS>-EMATN.
APPEND LS_HTNMAT TO LT_HTNMAT.
ENDIF.
ENDIF.
ENDIF.                                                      "437458
*
*--------------------------------------------------*
IF NOT LT_HTNMAT[] IS INITIAL.
LOOP AT LT_HTNMAT INTO LS_HTNMAT.
CLEAR: L_MTCOM, L_MT06E, L_MTCOR, L_VORGA.

L_MTCOM-KENNG = 'MT06E'.
L_MTCOM-MATNR = LS_HTNMAT-MATNR.
L_MTCOM-PSTAT = 'E'.
L_MTCOM-SPRAS = IS_EKKO-SPRAS.
L_MTCOM-KZSPR = 'X'.

CALL FUNCTION 'MEX_CHECK_MATERIAL'
EXPORTING
IM_MTCOM      = L_MTCOM
IM_VORGA      = SPACE
IMPORTING
EX_MT06E      = L_MT06E
EX_MTCOR      = L_MTCOR
EXCEPTIONS
ERROR_MESSAGE = 1
OTHERS        = 2.
IF SY-SUBRC NE 0.
DELETE LT_HTNMAT.
CONTINUE.
ENDIF.
CALL FUNCTION 'MEX_CHECK_MT06E_STATUS'
EXPORTING
IM_MTCOM      = L_MTCOM
IM_MTCOR      = L_MTCOR
IM_MT06E      = L_MT06E
EXCEPTIONS
ERROR_MESSAGE = 1
OTHERS        = 2.
IF SY-SUBRC NE 0.
DELETE LT_HTNMAT.
CONTINUE.
ENDIF.
ENDLOOP.
ENDIF.

*--------------------------------------------------*
IF NOT LT_HTNAMP[] IS INITIAL.
LOOP AT LT_HTNAMP INTO LS_HTNAMP.
CLEAR: L_MTCOM, L_MT06E, L_MTCOR, L_VORGA.

L_MTCOM-KENNG = 'MT06E'.
L_MTCOM-MATNR = LS_HTNAMP-MATNR.
L_MTCOM-PSTAT = 'E'.
L_MTCOM-SPRAS = IS_EKKO-SPRAS.
L_MTCOM-KZSPR = 'X'.

CALL FUNCTION 'MEX_CHECK_MATERIAL'
EXPORTING
IM_MTCOM      = L_MTCOM
IM_VORGA      = SPACE
IMPORTING
EX_MT06E      = L_MT06E
EX_MTCOR      = L_MTCOR
EXCEPTIONS
ERROR_MESSAGE = 1
OTHERS        = 2.
IF SY-SUBRC NE 0.
DELETE LT_HTNAMP.
CONTINUE.
ENDIF.
CALL FUNCTION 'MEX_CHECK_MT06E_STATUS'
EXPORTING
IM_MTCOM      = L_MTCOM
IM_MTCOR      = L_MTCOR
IM_MT06E      = L_MT06E
EXCEPTIONS
ERROR_MESSAGE = 1
OTHERS        = 2.
IF SY-SUBRC NE 0.
DELETE LT_HTNAMP.
CONTINUE.
ENDIF.
ENDLOOP.
ENDIF.

*--------------------------------------------------*
* if no MPN info exist, exit
*--------------------------------------------------*

IF   LT_HTNMAT[] IS INITIAL AND
LT_HTNAMP[] IS INITIAL.
EXIT.
ENDIF.

*--------------------------------------------------*
* Prepare GT_MPN for printing
*--------------------------------------------------*

REFRESH: LT_HERST, GT_MPN.
CLEAR LS_HERST.
CLEAR L_MPN.
IF NOT LT_HTNAMP[] IS INITIAL.
LOOP AT LT_HTNAMP INTO LS_HTNAMP.
MOVE-CORRESPONDING LS_HTNAMP TO L_MPN.
CALL FUNCTION 'MARA_SINGLE_READ'
EXPORTING
MATNR  = LS_HTNAMP-MATNR
IMPORTING
WMARA  = LS_MARA
EXCEPTIONS
OTHERS = 5.
LS_HERST-LIFNR = LS_MARA-MFRNR.
APPEND LS_HERST TO LT_HERST.

L_MPN-EMNFR = LS_MARA-MFRNR.
L_MPN-REVLV = LS_HTNAMP-REVLV.
L_MPN-MFRPN = LS_MARA-MFRPN.
APPEND L_MPN TO GT_MPN.
CLEAR L_MPN.
ENDLOOP.
ELSEIF NOT LT_HTNMAT[] IS INITIAL AND
<FS>-MFRPN IS INITIAL.
LOOP AT LT_HTNMAT INTO LS_HTNMAT.
LS_HERST-LIFNR = LS_HTNMAT-MFRNR.
APPEND LS_HERST TO LT_HERST.
ENDLOOP.
IF NOT LT_HERST[] IS INITIAL.
CALL FUNCTION 'WY_LFA1_ARRAY_READ'
TABLES
PTI_LFA1_KEYTAB          = LT_HERST
PTO_LFA1                 = LT_LFA1
EXCEPTIONS
ERR_NO_RECORDS_REQUESTED = 1
ERR_NO_RECORDS_FOUND     = 2
OTHERS                   = 3.
ENDIF.

ENDIF.

CLEAR L_MPN.

IF NOT LT_HTNAMP[] IS INITIAL.
LOOP AT GT_MPN INTO L_MPN.
READ TABLE LT_LFA1 INTO LS_LFA1
WITH KEY LIFNR = L_MPN-EMNFR.
IF SY-SUBRC EQ 0 AND
NOT LS_LFA1-EMNFR IS INITIAL.
L_MPN-EMNFR = LS_LFA1-EMNFR.
MODIFY GT_MPN FROM L_MPN.
ENDIF.
ENDLOOP.
ELSE.
REFRESH GT_MPN.
LOOP AT LT_HTNMAT INTO LS_HTNMAT.
MOVE-CORRESPONDING LS_HTNMAT TO L_MPN.
IF L_MPN-EMNFR IS INITIAL AND
<FS>-MFRPN IS INITIAL.
READ TABLE LT_LFA1 INTO LS_LFA1
WITH KEY LIFNR = LS_HTNMAT-MFRNR.
IF SY-SUBRC EQ 0 AND
NOT LS_LFA1-EMNFR IS INITIAL.
L_MPN-EMNFR = LS_LFA1-EMNFR.
ENDIF.
ENDIF.
IF NOT <FS>-REVLV IS INITIAL.
L_MPN-REVLV = <FS>-REVLV.
ENDIF.
APPEND L_MPN TO GT_MPN.
ENDLOOP.
ENDIF.

























