
CLEAR GS_QM_CERT_CATEGORY.

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE * INTO GS_QM_CERT_CATEGORY
*FROM TQ05 WHERE ZGTYP EQ <FS>-ZGTYP.
*
* NEW CODE
SELECT *
UP TO 1 ROWS  INTO GS_QM_CERT_CATEGORY
FROM TQ05 WHERE ZGTYP EQ <FS>-ZGTYP ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

IF SY-SUBRC EQ 0.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE KURZTEXT INTO GS_QM_CERT_TXT
*FROM TQ05T  WHERE SPRACHE EQ IS_EKKO-SPRAS
*AND   ZGTYP   EQ <FS>-ZGTYP.
*
* NEW CODE
SELECT KURZTEXT
UP TO 1 ROWS  INTO GS_QM_CERT_TXT
FROM TQ05T  WHERE SPRACHE EQ IS_EKKO-SPRAS
AND   ZGTYP   EQ <FS>-ZGTYP ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
ENDIF.



















