CONSTANTS LC_CHARX TYPE C VALUE 'X'.

DATA LT_DA_T_CABN LIKE CABN OCCURS 10 WITH HEADER LINE.
DATA LS_CONF_OUT  TYPE CONF_OUT.

DATA: BEGIN OF LS_DA_KEY,
MANDT LIKE CABN-MANDT,
ATINN LIKE CABN-ATINN,
END OF LS_DA_KEY.

REFRESH GT_CONF_OUT.

CHECK NOT <FS>-CUOBJ IS INITIAL AND
<FS>-ATTYP NE '02'.
"----- ATTYP: '02', Variant----------

CALL FUNCTION 'VC_I_GET_CONFIGURATION'
EXPORTING
INSTANCE      = <FS>-CUOBJ
LANGUAGE      = IS_NAST-SPRAS
PRINT_SALES   = LC_CHARX
TABLES
CONFIGURATION = GT_CONF_OUT
EXCEPTIONS
OTHERS        = 4.

RANGES LR_DA_IN_CABN FOR LT_DA_T_CABN-ATINN.

CLEAR   LR_DA_IN_CABN.
REFRESH LR_DA_IN_CABN.

LOOP AT GT_CONF_OUT INTO LS_CONF_OUT.
LR_DA_IN_CABN-OPTION = 'EQ'.
LR_DA_IN_CABN-SIGN   = 'I'.
LR_DA_IN_CABN-LOW    = LS_CONF_OUT-ATINN.
APPEND LR_DA_IN_CABN.
ENDLOOP.

CLEAR   LT_DA_T_CABN.
REFRESH LT_DA_T_CABN.

CALL FUNCTION 'CLSE_SELECT_CABN'
TABLES
IN_CABN        = LR_DA_IN_CABN
T_CABN         = LT_DA_T_CABN
EXCEPTIONS
NO_ENTRY_FOUND = 1
OTHERS         = 2.

SORT LT_DA_T_CABN.

LOOP AT GT_CONF_OUT INTO LS_CONF_OUT.
LS_DA_KEY-MANDT = SY-MANDT.
LS_DA_KEY-ATINN = LS_CONF_OUT-ATINN.
READ TABLE LT_DA_T_CABN WITH KEY LS_DA_KEY BINARY SEARCH.
IF SY-SUBRC <> 0 OR
( ( LT_DA_T_CABN-ATTAB = 'SDCOM' AND LT_DA_T_CABN-ATFEL = 'VKOND') OR
( LT_DA_T_CABN-ATTAB = 'VCSD_UPDATE' ) ) .
DELETE GT_CONF_OUT.
ENDIF.
ENDLOOP.

