PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZFIRFC04-BUKRS .
    FIELD ZFIRFC04-GRUPO .
    FIELD ZFIRFC04-ZKEY .
    FIELD ZFIRFC04-CPUDT .
    FIELD ZFIRFC04-CPUTM .
    FIELD ZFIRFC04-UNAME .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZFIRFC04-BUKRS .
    FIELD ZFIRFC04-GRUPO .
    FIELD ZFIRFC04-ZKEY .
  module detail_pai.
 endchain.
