*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZ_ACT_TABLATOP.                   " Global Data
  INCLUDE LZ_ACT_TABLAUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZ_ACT_TABLAF00                         . " subprograms
  INCLUDE LZ_ACT_TABLAI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZ_ACT_TABLAF...                   " Subprograms
* INCLUDE LZ_ACT_TABLAO...                   " PBO-Modules
* INCLUDE LZ_ACT_TABLAI...                   " PAI-Modules
