*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZAGENCIATOP.                      " Global Data
  INCLUDE LZAGENCIAUXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZAGENCIAF00                            . " subprograms
  INCLUDE LZAGENCIAI00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZAGENCIAF...                      " Subprograms
* INCLUDE LZAGENCIAO...                      " PBO-Modules
* INCLUDE LZAGENCIAI...                      " PAI-Modules
