*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZAM_AT1TOP.                       " Global Data
  INCLUDE LZAM_AT1UXX.                       " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZAM_AT1F00                             . " subprograms
  INCLUDE LZAM_AT1I00                             . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZAM_AT1F...                       " Subprograms
* INCLUDE LZAM_AT1O...                       " PBO-Modules
* INCLUDE LZAM_AT1I...                       " PAI-Modules
