PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFIPG003_OUT CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFIPG003_OUT-BUKRS .
    FIELD ZFIPG003_OUT-HBKID .
    FIELD ZFIPG003_OUT-PROGRAMM .
    FIELD ZFIPG003_OUT-F_LAUFD .
    FIELD ZFIPG003_OUT-F_LAUFI .
    FIELD ZFIPG003_OUT-F_ZLSCH .
    FIELD ZFIPG003_OUT-F_NROTRAN .
    FIELD ZFIPG003_OUT-F_RETVVFI .
    FIELD ZFIPG003_OUT-F_FILENAME .
    FIELD ZFIPG003_OUT-F_FECPAG .
    FIELD ZFIPG003_OUT-F_CONVENIO .
    FIELD ZFIPG003_OUT-F_MODULO .
    FIELD ZFIPG003_OUT-F_SERVICIO .
    FIELD ZFIPG003_OUT-F_DESCRIPCION .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFIPG003_OUT-BUKRS .
    FIELD ZFIPG003_OUT-HBKID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
