*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZBMNC_LISTABDETTOP.               " Global Data
  INCLUDE LZBMNC_LISTABDETUXX.               " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZBMNC_LISTABDETF00                     . " subprograms
  INCLUDE LZBMNC_LISTABDETI00                     . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZBMNC_LISTABDETF...               " Subprograms
* INCLUDE LZBMNC_LISTABDETO...               " PBO-Modules
* INCLUDE LZBMNC_LISTABDETI...               " PAI-Modules
