*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZCBAN_CC_SUCTOP.                  " Global Data
  INCLUDE LZCBAN_CC_SUCUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZCBAN_CC_SUCF00                        . " subprograms
  INCLUDE LZCBAN_CC_SUCI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZCBAN_CC_SUCF...                  " Subprograms
* INCLUDE LZCBAN_CC_SUCO...                  " PBO-Modules
* INCLUDE LZCBAN_CC_SUCI...                  " PAI-Modules
