PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCB_ITER_SUC CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCB_ITER_SUC-BUKRS .
    FIELD ZCB_ITER_SUC-HBKID .
    FIELD ZCB_ITER_SUC-HKTID .
    FIELD ZCB_ITER_SUC-SECUENCIA .
    FIELD ZCB_ITER_SUC-REFCAR .
    FIELD ZCB_ITER_SUC-ENABLED .
    FIELD ZCB_ITER_SUC-REFCONT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCB_ITER_SUC-BUKRS .
    FIELD ZCB_ITER_SUC-HBKID .
    FIELD ZCB_ITER_SUC-HKTID .
    FIELD ZCB_ITER_SUC-SECUENCIA .
    FIELD ZCB_ITER_SUC-REFCAR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
