PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCEBE_PRESCRIP CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCEBE_PRESCRIP-KOKRS .
    FIELD ZCEBE_PRESCRIP-BUKRS .
    FIELD ZCEBE_PRESCRIP-PRCTR .
    FIELD ZCEBE_PRESCRIP-MCTXT .
    FIELD ZCEBE_PRESCRIP-DATAB .
    FIELD ZCEBE_PRESCRIP-ERSDA .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCEBE_PRESCRIP-KOKRS .
    FIELD ZCEBE_PRESCRIP-BUKRS .
    FIELD ZCEBE_PRESCRIP-PRCTR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
