*&---------------------------------------------------------------------*
*&  Include           ZCL_SEN_PRINT_ACEPTA_TOP
*&---------------------------------------------------------------------*
TABLES BKPF.
TABLES VBRK.
TYPE-POOLS SLIS.
CONSTANTS TRUE                   TYPE C VALUE 'X'.
CONSTANTS C_FORMNAME_TOP_OF_PAGE TYPE SLIS_FORMNAME VALUE 'TOP_OF_PAGE'.
CONSTANTS C_FORMNAME_TOP_OF_LIST TYPE SLIS_FORMNAME VALUE 'TOP_OF_LIST'.
CONSTANTS C_FORMNAME_END_OF_LIST TYPE SLIS_FORMNAME VALUE 'END_OF_LIST'.
DATA      TMP  TYPE STRING.
DATA      P    TYPE STRING.
DATA: BEGIN OF TI_DOC OCCURS 0,
        VBELN   LIKE VBRK-VBELN,
        ZBLART  LIKE VBRK-ZBLART,
        XBLNR   LIKE VBRK-XBLNR,
        MENSAJE TYPE C LENGTH 200,
      END OF TI_DOC.

DATA: CLIENT    TYPE REF TO IF_HTTP_CLIENT,
      PATH      TYPE STRING,
      SCHEME    TYPE I,
      OFF       TYPE I,
      RC        TYPE SY-SUBRC,
      HOST      TYPE STRING,
      PORT      TYPE STRING,
      CONTENT   TYPE STRING,
      XCONTENT  TYPE XSTRING,
      HTTP_RC   TYPE  SYSUBRC,
      BINARY    TYPE FLAG,
      TIMEOUT   TYPE I,
      STR_DAT   TYPE STRING,
      COM_ACC   TYPE STRING,
      ERRORTEXT TYPE STRING,
      SUBRC     TYPE I.

TYPES: BEGIN OF EST_ENTRADA,
        REGISTRO(1000) TYPE C,
       END OF EST_ENTRADA.

DATA IT_ENTRADA TYPE STANDARD TABLE OF EST_ENTRADA WITH HEADER LINE.
DATA FILE       TYPE STRING.
DATA IS_U_LAYOUT   TYPE SLIS_LAYOUT_ALV.
DATA IT_U_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV.
DATA IT_U_SORT     TYPE SLIS_T_SORTINFO_ALV.
DATA IS_PRINT      TYPE SLIS_PRINT_ALV.
DATA GT_EVENTS     TYPE SLIS_T_EVENT.
DATA WA_EVENT      TYPE SLIS_ALV_EVENT.
DATA GT_EVENT_EXIT TYPE SLIS_T_EVENT_EXIT.
DATA: BEGIN OF IT_BLART OCCURS 0,
             BLART TYPE C LENGTH 4,
             GLOSA TYPE C LENGTH 30,
         END OF IT_BLART.


DATA : FIELD_TAB LIKE DFIES  OCCURS 0 WITH HEADER LINE.
DATA : RETURN_TAB LIKE DDSHRETVAL OCCURS 0 WITH HEADER LINE.
DATA : X TYPE STRING.
DATA : str_numcop type string.
