*&---------------------------------------------------------------------*
*&  Include           ZCL_CREA_PEDIDOS_SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN OF BLOCK B_TP1 WITH FRAME TITLE TEXT-003.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 10.
PARAMETERS P_DELDB AS CHECKBOX.
SELECTION-SCREEN COMMENT 13(32) TEXT-005.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B_TP1.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF BLOCK B_TPO WITH FRAME TITLE TEXT-000.
PARAMETERS P_LOCAL AS CHECKBOX.
PARAMETERS P_FILE LIKE RLGRAP-FILENAME.
SELECTION-SCREEN END OF BLOCK B_TPO.
