*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZCTARECHAZOTOP.                   " Global Data
  INCLUDE LZCTARECHAZOUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZCTARECHAZOF00                         . " subprograms
  INCLUDE LZCTARECHAZOI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZCTARECHAZOF...                   " Subprograms
* INCLUDE LZCTARECHAZOO...                   " PBO-Modules
* INCLUDE LZCTARECHAZOI...                   " PAI-Modules
