PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZDATSOCELEC_BAN CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZDATSOCELEC_BAN-BUKRS .
    FIELD ZDATSOCELEC_BAN-RUT_CONTR .
    FIELD ZDATSOCELEC_BAN-RUT_ENVIA .
    FIELD ZDATSOCELEC_BAN-FEC_RES .
    FIELD ZDATSOCELEC_BAN-NUM_RES .
    FIELD ZDATSOCELEC_BAN-TIP_OPERA .
    FIELD ZDATSOCELEC_BAN-TIP_LIB .
    FIELD ZDATSOCELEC_BAN-TIP_ENV .
    FIELD ZDATSOCELEC_BAN-FOLIO_NOT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZDATSOCELEC_BAN-BUKRS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
