*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZDIRECCGUIATOP.                   " Global Data
  INCLUDE LZDIRECCGUIAUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZDIRECCGUIAF00                         . " subprograms
  INCLUDE LZDIRECCGUIAI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZDIRECCGUIAF...                   " Subprograms
* INCLUDE LZDIRECCGUIAO...                   " PBO-Modules
* INCLUDE LZDIRECCGUIAI...                   " PAI-Modules
