*&---------------------------------------------------------------------*
*&  Include           ZENV_FAC_ELEC_TOP
*&---------------------------------------------------------------------*
TABLES: KOMK, KOMP, KOMVD, VBCO3, VBDKR, VBDPR, VBDRE, CONF_OUT,
        SADR, TVKO, ADRS, T005, T001, T001G, TVCINT, KONH, TLIC,
        FPLTVB, SDACCDPC, VBRK, BKPF, BSET, VBDPRL, VTOPIS, NAST,
        *NAST, TNAPR, ITCPO, ARC_PARAMS, TOA_DARA, ADDR_KEY, ZCABPEDEXT, VBFA.

TABLES IDCN_BOMA.
DATA H_NIINV LIKE IDCN_BOMA-LIINV.
TYPE-POOLS SZADR.

DATA BEGIN OF TVBDPR OCCURS 100.      "Internal table for items
        INCLUDE STRUCTURE VBDPR.
DATA END OF TVBDPR.

DATA BEGIN OF TKOMV OCCURS 50.
        INCLUDE STRUCTURE KOMV.
DATA END OF TKOMV.

DATA BEGIN OF TKOMVD OCCURS 50.
        INCLUDE STRUCTURE KOMVD.
DATA END OF TKOMVD.

DATA BEGIN OF *TKOMVD OCCURS 50.
        INCLUDE STRUCTURE KOMVD.
DATA END OF *TKOMVD.

DATA BEGIN OF HKOMV OCCURS 50.
        INCLUDE STRUCTURE KOMV.
DATA END OF HKOMV.

DATA BEGIN OF HKOMVD OCCURS 50.
        INCLUDE STRUCTURE KOMVD.
DATA END OF HKOMVD.

DATA BEGIN OF TKOMCON OCCURS 50.
        INCLUDE STRUCTURE CONF_OUT.
DATA END   OF TKOMCON.

DATA BEGIN OF IXSDACCDPC OCCURS 0.
        INCLUDE STRUCTURE SDACCDPC.
DATA END OF IXSDACCDPC.

DATA: BEGIN OF GT_SDACCDPC_DOC OCCURS 0,
        VBELN TYPE VBELN,
        POSNR TYPE POSNR,
      END OF GT_SDACCDPC_DOC.
DATA DA_XFILKD             LIKE TVFK-XFILKD.
DATA CHARA                 TYPE C VALUE 'A'.
DATA CHARB                 TYPE C VALUE 'B'.
DATA DOWNPAY_REFRESH       TYPE C.

DATA REPEAT                TYPE C.
DATA ANZAL                 LIKE NAST-ANZAL.
DATA NAST_ANZAL            LIKE NAST-ANZAL.
DATA NAST_TDARMOD          LIKE NAST-TDARMOD.
DATA XSCREEN               TYPE C.
DATA XVBELN                LIKE VBRK-VBELN.
DATA XPOSNR                LIKE VBRL-POSNR.
DATA PR_KAPPL              TYPE C VALUE 'V'.
DATA PRINT_MWSKZ           TYPE C.
DATA CCNAME(30)            TYPE C.
DATA HEADER_USEREXIT       LIKE TNAPR-RONAM.
DATA ITEM_USEREXIT         LIKE TNAPR-RONAM.
DATA HEADER_PRINT_USEREXIT LIKE TNAPR-RONAM.
DATA ITEM_PRINT_USEREXIT   LIKE TNAPR-RONAM.
DATA GET_DATA_USEREXIT     LIKE TNAPR-RONAM.
DATA PRINT_LOCAL_CURR_CH   TYPE C.
DATA KOMVDK_CH             LIKE KOMVD OCCURS 10 WITH HEADER LINE.
DATA KOMVDP_CH             LIKE KOMVD OCCURS 10 WITH HEADER LINE.

*INCLUDE IDBILLPRINT.
INCLUDE SDZAVDAT.
TABLES ADRC.
TABLES VBRP.

DATA COM_ACC     TYPE STRING.
DATA STR_DAT     TYPE STRING.
DATA PATH        TYPE STRING.
DATA TIMEOUT     TYPE I.
DATA SUBRC       TYPE I.
DATA ERRORTEXT   TYPE STRING.
DATA HTTP_RC     TYPE  SYSUBRC.
DATA BINARY      TYPE FLAG.
DATA DOC         TYPE C LENGTH 12 VALUE '102'.
DATA RC          TYPE SY-SUBRC.
DATA CONTENT     TYPE STRING.
DATA URL         TYPE STRING.
DATA SCHEME      TYPE I.
DATA OFF         TYPE I.
DATA CLIENT      TYPE REF TO IF_HTTP_CLIENT.
DATA PORT        TYPE STRING.
DATA HOST        TYPE STRING.
DATA LS_VBRK     LIKE VBRK.
DATA LS_BKPF     LIKE BKPF.
DATA STR_AWKEY   TYPE STRING.
DATA S_MNT_NET      TYPE C LENGTH 21.
DATA S_MNT_EXE      TYPE C LENGTH 21.
DATA S_MNT_IVA      TYPE C LENGTH 21.
DATA S_MNT_TOT      TYPE C LENGTH 21.
DATA TOTAL_DOC      LIKE VBRK-NETWR.
DATA STR_DETALLE    TYPE STRING.
DATA STR_REFERENCIA TYPE STRING.
DATA STR_POS        TYPE STRING.
DATA POS            TYPE I.
DATA STR_NETWR      TYPE C LENGTH 21.
DATA STR_DESC       TYPE C LENGTH 1000.
data str_send       type string.
DATA STR_ARKTX      TYPE C LENGTH 40.
DATA STR_XBLNR_REF  TYPE STRING.
DATA STR_FKDAT_REF  TYPE STRING.
DATA STR_TIP_REF    TYPE STRING.
DATA STR_BSARK      TYPE STRING.
DATA STR_FECHA      TYPE STRING.
DATA STR_TMSTFIRMA  TYPE STRING.
DATA TXT_CONTENT    TYPE C LENGTH 200.
DATA NUMCORE        TYPE C LENGTH 10.
DATA GS_THEAD       TYPE THEAD.
DATA T_LINES        TYPE STANDARD TABLE OF TLINE.
DATA GS_LINES       LIKE LINE OF T_LINES.
DATA L_STR          TYPE I.
DATA POS_STR        TYPE I.
DATA T_NAME LIKE THEAD-TDNAME.
