*&---------------------------------------------------------------------*
*& Report: < ZEY_GDS_CORRECTION > *
*& Author: < EY_DES04 > *
*& Description: < ReSQ Correction > *
*& Date: <24-12-2019> *
*& Transport Number: < ECDK917080 > *
*&---------------------------------------------------------------------*
*&---------------------------------------------------------------------*
*& Report  ZFI_CONTAB_CASTIGOS
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT  ZFI_CONTAB_CASTIGOS_X_DOC.
TYPE-POOLS RSDS.

CONSTANTS: C_PERIOD_PREV(3) VALUE '-21'.
TABLES BSEG.

DATA: TRANGE               TYPE RSDS_TRANGE,
      TRANGE_LINE          LIKE LINE OF TRANGE,
      TRANGE_FRANGE_T_LINE LIKE LINE OF TRANGE_LINE-FRANGE_T,
      TRANGE_FRANGE_T_SELOPT_T_LINE
        LIKE LINE OF TRANGE_FRANGE_T_LINE-SELOPT_T,
      TEXPR TYPE RSDS_TEXPR.

DATA L_FECHINI LIKE BSEG-FDTAG.
*
DATA BEGIN OF WA_CONTRAT .
DATA  VERTN LIKE BSEG-VERTN.
DATA END OF WA_CONTRAT.
*
DATA BEGIN OF WA_Num_docto.
     data BUKRS like bseg-BUKRS.
     data BELNR like bseg-BELNR.
     data GJAHR like bseg-GJAHR.
     data BUZEI like bseg-BUZEI.
DATA END OF WA_Num_docto.
*
DATA GT_CONTRAT   LIKE WA_CONTRAT   OCCURS 0 .
*
DATA GT_Num_docto LIKE WA_Num_docto OCCURS 0 .
*
FIELD-SYMBOLS <FS_CONTRAT> LIKE WA_CONTRAT.

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
PARAMETERS:P_BUKRS LIKE BSEG-BUKRS OBLIGATORY,
           P_FDTAG LIKE BSEG-FDTAG OBLIGATORY.
**-Parametrso ocultos.
PARAMETERS:
 P_BSCHL LIKE BSEG-BSCHL DEFAULT '01' NO-DISPLAY,
 P_KOART LIKE BSEG-KOART DEFAULT 'D' NO-DISPLAY,
 P_AUGBL LIKE BSEG-AUGBL DEFAULT SPACE NO-DISPLAY,
 P_VERTN LIKE BSEG-VERTN DEFAULT SPACE NO-DISPLAY.
SELECTION-SCREEN END OF BLOCK B1.

AT SELECTION-SCREEN on P_fdtag.
  IF NOT ( P_fdtag LE Sy-datum ).
    MESSAGE 'Fecha selección debe ser menor o igual a hoy'(003) TYPE 'E'.
  ENDIF.

START-OF-SELECTION.
  CALL FUNCTION 'SG_PS_ADD_MONTH_TO_DATE'
    EXPORTING
      MONTHS  = C_PERIOD_PREV
      OLDDATE = P_FDTAG
    IMPORTING
      NEWDATE = L_FECHINI.

*  SELECT VERTN INTO CORRESPONDING FIELDS OF TABLE GT_CONTRAT
*    FROM BSEG
*    WHERE BUKRS EQ P_BUKRS AND
*          BSCHL EQ P_BSCHL AND
*          KOART EQ P_KOART AND
*          AUGBL EQ P_AUGBL AND
*          VERTN NE P_VERTN AND
*          FDTAG LE L_FECHINI.

SELECT BUKRS BELNR GJAHR BUZEI INTO CORRESPONDING FIELDS OF TABLE GT_Num_docto
FROM BSEG
WHERE BUKRS EQ P_BUKRS AND
BSCHL EQ P_BSCHL AND
KOART EQ P_KOART AND
AUGBL EQ P_AUGBL AND
*Begin of change: ReSQ Correction for Addition ORDER BY PRIMARY KEY 24/12/2019 EY_DES04 ECDK917080 *
*FDTAG LE L_FECHINI.
FDTAG LE L_FECHINI ORDER BY PRIMARY KEY .
*End of change: ReSQ Correction for Addition ORDER BY PRIMARY KEY 24/12/2019 EY_DES04 ECDK917080 *

  IF SY-SUBRC NE 0.
    MESSAGE 'No existen registros para los parametros ingresados'(002) TYPE 'I'.
  ELSE.
*   DELETE ADJACENT DUPLICATES FROM GT_CONTRAT COMPARING VERTN.
    TRANGE_LINE-TABLENAME                = 'BSID'.
*   TRANGE_FRANGE_T_LINE-FIELDNAME       = 'VERTN'.
   TRANGE_FRANGE_T_LINE-FIELDNAME       = 'BUKRS'.
   TRANGE_FRANGE_T_LINE-FIELDNAME       = 'BELNR'.
   TRANGE_FRANGE_T_LINE-FIELDNAME       = 'GJAHR'.
   TRANGE_FRANGE_T_LINE-FIELDNAME       = 'BUZEI'.
*
    TRANGE_FRANGE_T_SELOPT_T_LINE-SIGN   = 'I'.
    TRANGE_FRANGE_T_SELOPT_T_LINE-OPTION = 'EQ'.
*    LOOP AT GT_CONTRAT ASSIGNING <FS_CONTRAT>.
*      TRANGE_FRANGE_T_SELOPT_T_LINE-LOW    = <FS_CONTRAT>-VERTN.
*    LOOP AT GT_Num_docto ASSIGNING <FS_CONTRAT>.
*      TRANGE_FRANGE_T_SELOPT_T_LINE-LOW    = <FS_CONTRAT>-VERTN.
*      APPEND TRANGE_FRANGE_T_SELOPT_T_LINE  TO TRANGE_FRANGE_T_LINE-SELOPT_T.
*    ENDLOOP.
*    APPEND TRANGE_FRANGE_T_LINE           TO TRANGE_LINE-FRANGE_T.
*
    REFRESH TRANGE_FRANGE_T_LINE-SELOPT_T[].
    TRANGE_FRANGE_T_LINE-FIELDNAME       = 'AUGBL'.
    TRANGE_FRANGE_T_SELOPT_T_LINE-SIGN   = 'I'.
    TRANGE_FRANGE_T_SELOPT_T_LINE-OPTION = 'EQ'.
    TRANGE_FRANGE_T_SELOPT_T_LINE-LOW    = SPACE.
    APPEND TRANGE_FRANGE_T_SELOPT_T_LINE  TO TRANGE_FRANGE_T_LINE-SELOPT_T.
    APPEND TRANGE_FRANGE_T_LINE           TO TRANGE_LINE-FRANGE_T.
*
*
    APPEND TRANGE_LINE                    TO TRANGE.
**-
    CALL FUNCTION 'FREE_SELECTIONS_RANGE_2_EX'
      EXPORTING
        FIELD_RANGES = TRANGE
      IMPORTING
        EXPRESSIONS  = TEXPR.

    SUBMIT RFITEMAR "VIA SELECTION-SCREEN
         WITH FREE SELECTIONS TEXPR
         WITH DD_BUKRS-LOW = P_BUKRS
    AND RETURN.
  ENDIF.

END-OF-SELECTION.
