*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFICH001TOP.                      " Global Data
  INCLUDE LZFICH001UXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFICH001F00                            . " subprograms
  INCLUDE LZFICH001I00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFICH001F...                      " Subprograms
* INCLUDE LZFICH001O...                      " PBO-Modules
* INCLUDE LZFICH001I...                      " PAI-Modules
