DATA: LS_T166P TYPE T166P.
DATA: LS_TEXT TYPE TY_TEXT.
DATA: LT_TEXTS TYPE TABLE OF TY_TEXT.

LS_TEXT-TDOBJECT = 'EKPO'.
LS_TEXT-TDSPRAS  = GV_LANGUAGE.
LS_TEXT-TDNAME   = <FS>-EBELN.
LS_TEXT-TDNAME+10(5)   = <FS>-EBELP.

CLEAR GT_ITM_TEXTS.

CALL FUNCTION 'SELECT_TEXT'
EXPORTING
OBJECT     = LS_TEXT-TDOBJECT
NAME       = LS_TEXT-TDNAME
ID         = '*'
LANGUAGE   = LS_TEXT-TDSPRAS
TABLES
SELECTIONS = LT_TEXTS.
IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ENDIF.
SORT LT_TEXTS BY TDID.

* append texts allowed to GT_ITM_TEXTS
* Item Text Part
CLEAR LS_TEXT.
LOOP AT LT_TEXTS INTO LS_TEXT.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE * FROM T166P INTO LS_T166P
*WHERE DRUVO = IV_DRUVO  AND
*BSTYP = IS_EKKO-BSTYP  AND
*BSART = IS_EKKO-BSART AND
*PSTYP = <FS>-PSTYP.
*
* NEW CODE
SELECT *
UP TO 1 ROWS  FROM T166P INTO LS_T166P
WHERE DRUVO = IV_DRUVO  AND
BSTYP = IS_EKKO-BSTYP  AND
BSART = IS_EKKO-BSART AND
PSTYP = <FS>-PSTYP ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
IF SY-SUBRC = 0.
APPEND LS_TEXT TO GT_ITM_TEXTS.
ENDIF.
CLEAR LS_TEXT.
ENDLOOP.









