***For intra-company Stock Transfer Order *****
***Read supplying plan address ****************
CHECK NOT IS_EKKO-RESWK IS INITIAL.

DATA LS_T001W     TYPE T001W.
SELECT SINGLE * FROM T001W INTO LS_T001W
WHERE WERKS EQ IS_EKKO-RESWK.
IF NOT LS_T001W-ADRNR IS INITIAL.
MOVE LS_T001W-ADRNR TO GV_ADDNR_VENDOR.
ENDIF.


