* read komk data
CLEAR GS_HD_KOND.
CLEAR GS_HD_KOMK.
CLEAR GT_HD_COND_FREIGHT.
CLEAR GT_HD_COND_TAX.
*CLEAR GV_FREIGHT_SUM.


GS_HD_KOMK-SUPOS   = IS_BIL_INVOICE-HD_KOMK-SUPOS.
GS_HD_KOMK-FKWRT   = IS_BIL_INVOICE-HD_KOMK-FKWRT.
* read condition data
CLEAR GS_HD_KOND.
DATA: GS_HD_KOND_WA TYPE LBBIL_HD_KOND.
LOOP AT IS_BIL_INVOICE-HD_KOND INTO GS_HD_KOND_WA

WHERE BIL_NUMBER = IS_BIL_INVOICE-HD_GEN-BIL_NUMBER.

*  IF GS_HD_KOND_WA-KOEIN ='%'.
*    DIVIDE GS_HD_KOND_WA-KBETR BY 10.
*  ENDIF.
*  WRITE GS_HD_KOND_WA-KBETR TO GS_HD_KOND_WA-BTRMW CURRENCY '2'.
*  APPEND GS_HD_KOND_WA TO GS_HD_KOND.

IF GS_HD_KOND_WA-KNTYP = 'F'.
APPEND GS_HD_KOND_WA TO GT_HD_COND_FREIGHT.
ADD GS_HD_KOND_WA-KWERT TO GV_FREIGHT_SUM.
*  ELSEIF NOT GS_HD_KOND_WA-MWSK1 IS INITIAL.
ELSEIF GS_HD_KOND_WA-KSCHL = 'MWST'.
APPEND GS_HD_KOND_WA TO GT_HD_COND_TAX.
ELSE.
APPEND GS_HD_KOND_WA TO GS_HD_KOND.
ENDIF.
ENDLOOP.


