CLEAR: GV_VTEXT,GV_KWERT,GV_KWERT_IN_DOC_CUR.
CHECK NOT <KO>-KWERT = <FS>-NETWR.

IF ( <KO>-KNTYP = 'O' OR NOT <KO>-KVARC IS INITIAL )
AND NOT <KO>-KNUMH IS INITIAL.
"***** Variant Condition Description *****
PERFORM GET_VARIANT_DESC
USING GV_LANGUAGE
<KO>-KNUMH
GV_VTEXT.
ELSE.
SELECT SINGLE VTEXT INTO GV_VTEXT FROM T685T
WHERE SPRAS = GV_LANGUAGE
AND KSCHL = <KO>-KSCHL.
ENDIF.

IF SY-SUBRC = 0.
MOVE <KO>-KWERT TO GV_KWERT.

ENDIF.

* Check document currency
IF NOT GV_SPEC_CUR_DECIMAL IS INITIAL.
WRITE GV_KWERT TO GV_KWERT_IN_DOC_CUR
CURRENCY IS_EKKO-WAERS.
ENDIF.
*Determine if the discount is based on %
*Determine if the discount is based on %
IF  <KO>-KRECH = 'A' OR
<KO>-KRECH = 'H' OR
<KO>-KRECH = 'I' OR
<KO>-KSCHL = 'SKTO'.
<KO>-KBETR = <KO>-KBETR / 10.
MOVE '%' TO <KO>-WAERS.
ENDIF.


* Determine Tax
IF <KO>-KNTYP EQ 'D'.
ADD <KO>-KWERT TO GV_TAX.
CLEAR GV_KWERT.
ENDIF.
* Determine Freight Charges
IF <KO>-KNTYP EQ 'F'.
ADD: <KO>-KWERT TO GV_FRAKWERT.
CLEAR GV_KWERT.
ENDIF.

