CLEAR GT_MDPM.

DATA MDPA LIKE MDPA.

MDPA-RSNUM = <EK>-RSNUM.
MDPA-MATNR = <FS>-MATNR.
MDPA-PWWRK = <FS>-WERKS.
REFRESH: GT_MDPM.
CALL FUNCTION 'MD_LESEN_KOMPONENTEN'
EXPORTING
EMDPA = MDPA
IMPORTING
IMDPA = MDPA
TABLES
MDPMX = GT_MDPM.

