DATA: WA_T166P TYPE T166P.
DATA: WA_TEXT TYPE TY_TEXT.
DATA: WT_TEXTS TYPE TABLE OF TY_TEXT.
WA_TEXT-TDOBJECT = 'EKPO'.
WA_TEXT-TDSPRAS  = GV_LANGUAGE.
WA_TEXT-TDNAME   = <FS>-EBELN.
WA_TEXT-TDNAME+10(5)   = <FS>-EBELP.

CLEAR GT_ITM_TEXTS.

CALL FUNCTION 'SELECT_TEXT'
EXPORTING
OBJECT     = WA_TEXT-TDOBJECT
NAME       = WA_TEXT-TDNAME
ID         = '*'
LANGUAGE   = WA_TEXT-TDSPRAS
TABLES
SELECTIONS = WT_TEXTS.
IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ENDIF.
SORT WT_TEXTS BY TDID.

* append texts allowed to GT_ITM_TEXTS
* Item Text Part
CLEAR WA_TEXT.
LOOP AT WT_TEXTS INTO WA_TEXT.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE * FROM T166P
*INTO WA_T166P
*WHERE DRUVO = IV_DRUVO  AND
*BSTYP = IS_EKKO-BSTYP  AND
*BSART = IS_EKKO-BSART AND
*PSTYP = <FS>-PSTYP.
*
* NEW CODE
SELECT *
UP TO 1 ROWS  FROM T166P
INTO WA_T166P
WHERE DRUVO = IV_DRUVO  AND
BSTYP = IS_EKKO-BSTYP  AND
BSART = IS_EKKO-BSART AND
PSTYP = <FS>-PSTYP ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
IF SY-SUBRC = 0.
APPEND WA_TEXT TO GT_ITM_TEXTS.
ENDIF.
CLEAR WA_TEXT.
ENDLOOP.









