DATA LS_EKEK TYPE EKEK.
DATA LS_T006 TYPE T006.

CLEAR GS_PEKPO.
CLEAR GS_PRT_AUX.

SELECT SINGLE * FROM T006 INTO LS_T006
WHERE MSEHI EQ <FS>-MEINS.       "Order unit

READ TABLE IT_PEKPO INTO GS_PEKPO
WITH KEY EBELP = <FS>-EBELP.

READ TABLE IT_EKEK INTO LS_EKEK
WITH KEY EBELN = <FS>-EBELN
EBELP = <FS>-EBELP.

***Scheduled Quantity => GS_PRT_AUX-PRMG1
WRITE <FS>-MENGE NO-SIGN DECIMALS LS_T006-DECAN
TO GS_PRT_AUX-PRMG1.

***Target Quantity    => GS_PRT_AUX-PRMG3
WRITE <FS>-KTMNG NO-SIGN DECIMALS LS_T006-DECAN
TO GS_PRT_AUX-PRMG3.

***Delivered Quantity => GS_PRT_AUX-PRMG2
IF IS_EKKO-LPHIS IS INITIAL.
WRITE GS_PEKPO-WEMNG NO-SIGN DECIMALS LS_T006-DECAN
TO GS_PRT_AUX-PRMG2.
ELSE.
WRITE LS_EKEK-ABEFZ NO-SIGN DECIMALS LS_T006-DECAN
TO GS_PRT_AUX-PRMG2.
ENDIF.

***Last Delivered Quantity => GS_PRT_AUX-PRMG4
IF NOT GS_PEKPO-LWEMG IS INITIAL.
WRITE GS_PEKPO-LWEMG NO-SIGN DECIMALS LS_T006-DECAN
TO GS_PRT_AUX-PRMG4.
ENDIF.






















