DATA LS_EKET TYPE EKET.

CLEAR GV_DLV_CHTXT.

READ TABLE IT_EKET INTO LS_EKET
WITH KEY
EBELN = <FS>-EBELN
EBELP = <FS>-EBELP.

* In case a position has been delivered partially.
IF SY-SUBRC = 0 AND LS_EKET-WEMNG <> 0.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE CHTXT FROM  T166T
*INTO   GV_DLV_CHTXT
*WHERE  SPRAS  = IS_EKKO-SPRAS
*AND    CTXNR  = 'P15'.
*
* NEW CODE
SELECT CHTXT
UP TO 1 ROWS  FROM  T166T
INTO   GV_DLV_CHTXT
WHERE  SPRAS  = IS_EKKO-SPRAS
AND    CTXNR  = 'P15' ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* If a position has been delivered completely, it is deleted
* from Xeket and therefore sy-subrc <> 0.
ELSEIF SY-SUBRC <> 0.
IF <FS>-PSTYP <> '6'.   "not text item
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE CHTXT FROM  T166T
*INTO   GV_DLV_CHTXT
*WHERE  SPRAS  = IS_EKKO-SPRAS
*AND    CTXNR  = 'P14'.
*
* NEW CODE
SELECT CHTXT
UP TO 1 ROWS  FROM  T166T
INTO   GV_DLV_CHTXT
WHERE  SPRAS  = IS_EKKO-SPRAS
AND    CTXNR  = 'P14' ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
ENDIF.
ENDIF.

























