
* To get texts for tax codes.
CLEAR TAX_TEXT.

DATA: BEGIN OF COMP_DATA,
LAND1 LIKE T001-LAND1,
SPRAS LIKE T001-SPRAS,
END OF COMP_DATA.

DATA: ZKALSM LIKE T005-KALSM.

*GS_HD_KOND_W-KBETR = GS_HD_KOND_W-KBETR * -1.

TX_RATE = GS_HD_KOND_W-KBETR.
TX_RATE = TX_RATE / 10.

SELECT SINGLE LAND1 SPRAS FROM T001 INTO CORRESPONDING FIELDS OF
COMP_DATA
WHERE BUKRS = IS_BIL_INVOICE-HD_ORG-COMP_CODE.

SELECT SINGLE KALSM FROM T005 INTO ZKALSM WHERE LAND1 = COMP_DATA-LAND1.

*SELECT SINGLE TEXT1 FROM T007S INTO TAX_TEXT1 WHERE
*           SPRAS = COMP_DATA-SPRAS AND
*           KALSM = ZKALSM AND
*           MWSKZ = GS_HD_KOND_W-MWSKZ.

SELECT SINGLE TEXT1 FROM T007S INTO TAX_TEXT WHERE
SPRAS = IS_NAST-SPRAS AND
KALSM = ZKALSM AND
MWSKZ = GS_HD_KOND_W-MWSKZ.

IF SY-SUBRC <> 0.
SELECT SINGLE TEXT1 FROM T007S INTO TAX_TEXT WHERE
SPRAS = COMP_DATA-SPRAS AND
KALSM = ZKALSM AND
MWSKZ = GS_HD_KOND_W-MWSKZ.
ENDIF.

