***For intra-company Stock Transfer Order *****
***Read supplying plan address ****************
CHECK NOT IS_EKKO-RESWK IS INITIAL.

DATA LS_T001W     TYPE T001W.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE * FROM T001W INTO LS_T001W
*WHERE WERKS EQ IS_EKKO-RESWK.
*
* NEW CODE
SELECT *
UP TO 1 ROWS  FROM T001W INTO LS_T001W
WHERE WERKS EQ IS_EKKO-RESWK ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
IF NOT LS_T001W-ADRNR IS INITIAL.
MOVE LS_T001W-ADRNR TO GV_ADDNR_VENDOR.
ENDIF.


