
TABLES: THEAD, *THEAD.
DATA: TMPPF TYPE TABLE OF TMPPF WITH HEADER LINE.

DATA: QV_TEXT_I  LIKE TQ09T-KURZTEXT,
TL_TEXT_I  LIKE TQ09T-KURZTEXT.

DATA: L_QM_TEXT  TYPE TY_TEXT.
CLEAR GS_QM_CERT_REQUIRED.
CLEAR GT_QM_TEXTS.

CHECK IV_DRUVO EQ CON_NEU OR
IV_DRUVO EQ CON_AEND.
CHECK IS_EKKO-LIFNR NE SPACE.
CHECK <FS>-MATNR NE SPACE.
CHECK <FS>-WERKS NE SPACE.
CHECK <FS>-SSQSS NE SPACE.
CLEAR: THEAD, *THEAD.

IF NOT <FS>-MPROF IS INITIAL AND
<FS>-MPROF NE TMPPF-MPROF.
CALL FUNCTION 'MB_READ_TMPPF'
EXPORTING
PROFILE        = <FS>-MPROF
IMPORTING
MPN_PARAMETERS = TMPPF.
ENDIF.

CALL FUNCTION 'QBCK_QM_DOCUMENT_TEXTS'
EXPORTING
I_DAT         = IS_EKKO-BEDAT
I_LANGU       = IS_EKKO-SPRAS
I_LIFNR       = IS_EKKO-LIFNR
I_MATNR       = <FS>-MATNR
I_TQ08_QM_PUR = <FS>-SSQSS
I_WERK        = <FS>-WERKS
I_REVLV       = <FS>-REVLV
I_EMATNR      = <FS>-EMATN
I_STAT17      = TMPPF-MPQIN
IMPORTING
E_QV_LTEXT    = THEAD-TDNAME
E_QV_OBJECT   = THEAD-TDOBJECT
E_QV_TXTID    = THEAD-TDID
E_QV_TEXT     = QV_TEXT_I
E_TL_LTEXT    = *THEAD-TDNAME
E_TL_OBJECT   = *THEAD-TDOBJECT
E_TL_TXTID    = *THEAD-TDID
E_TL_TEXT     = TL_TEXT_I
E_ZG_KZ       = GS_QM_CERT_REQUIRED
EXCEPTIONS
NO_LIEFERANT  = 01
NO_MATERIAL   = 02
NO_QINF       = 03
NO_TQ08       = 04
NO_WERK       = 05.

IF SY-SUBRC EQ 0.
IF THEAD-TDOBJECT NE SPACE.
CLEAR L_QM_TEXT.
L_QM_TEXT-TDOBJECT = THEAD-TDOBJECT.
L_QM_TEXT-TDID     = THEAD-TDID.
L_QM_TEXT-TDNAME   = THEAD-TDNAME.
L_QM_TEXT-TDTEXT   = QV_TEXT_I.
APPEND L_QM_TEXT TO GT_QM_TEXTS.
ENDIF.
IF *THEAD-TDOBJECT NE SPACE.
CLEAR L_QM_TEXT.
L_QM_TEXT-TDOBJECT = *THEAD-TDOBJECT.
L_QM_TEXT-TDID     = *THEAD-TDID.
L_QM_TEXT-TDNAME   = *THEAD-TDNAME.
L_QM_TEXT-TDTEXT   = TL_TEXT_I.
APPEND L_QM_TEXT TO GT_QM_TEXTS.
ENDIF.
ENDIF.




