GV_NETWR = IS_PEKKO-NETWR.

ADD   IS_PEKKO-NETWR TO GV_TOTAL.
ADD   GV_FRAKWERT    TO GV_TOTAL.
ADD   GV_TAX         TO GV_TOTAL.

* Check document currency
IF NOT GV_SPEC_CUR_DECIMAL IS INITIAL.
WRITE IS_PEKKO-NETWR TO       GV_NETWR_IN_DOC_CUR
CURRENCY IS_EKKO-WAERS.

WRITE GV_FRAKWERT    TO       GV_FRAKWERT_DOC_CUR
CURRENCY IS_EKKO-WAERS.

WRITE GV_TAX         TO       GV_TAX_IN_DOC_CUR
CURRENCY IS_EKKO-WAERS.

WRITE GV_TOTAL       TO       GV_TOTAL_IN_DOC_CUR
CURRENCY IS_EKKO-WAERS.
ENDIF.



