DATA: LS_T166K TYPE T166K.
DATA: LT_TEXTS TYPE TABLE OF TY_TEXT.
DATA: LS_TEXT  TYPE TY_TEXT.

LS_TEXT-TDOBJECT = 'EKKO'.
LS_TEXT-TDSPRAS  = GV_LANGUAGE.
LS_TEXT-TDNAME   = IS_EKKO-EBELN.

CLEAR GT_HD_TEXTS.

CALL FUNCTION 'SELECT_TEXT'
EXPORTING
OBJECT     = LS_TEXT-TDOBJECT
NAME       = LS_TEXT-TDNAME
ID         = '*'
LANGUAGE   = LS_TEXT-TDSPRAS
TABLES
SELECTIONS = LT_TEXTS.
IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ENDIF.
SORT LT_TEXTS BY TDID.

* read IMG setting -- table T166K
* append texts allowed to GT_HD_TEXTS
* Head Text Part
CLEAR LS_TEXT.
LOOP AT LT_TEXTS INTO LS_TEXT.
SELECT SINGLE *  FROM T166K  INTO LS_T166K
WHERE DRUVO     = IV_DRUVO  AND
BSTYP     = IS_EKKO-BSTYP  AND
BSART     = IS_EKKO-BSART  AND
TDOBJECT  = LS_TEXT-TDOBJECT AND
TDID      = LS_TEXT-TDID.
IF SY-SUBRC = 0.
APPEND LS_TEXT TO GT_HD_TEXTS.
ENDIF.
CLEAR LS_TEXT.
ENDLOOP.


















