* To get texts for tax codes.
*TABLES: T005, T007S, T001.
DATA: BEGIN OF COMP_DATA,
LAND1 LIKE T001-LAND1,
SPRAS LIKE T001-SPRAS,
END OF COMP_DATA.

DATA: ZKALSM LIKE T005-KALSM.

SELECT SINGLE LAND1 SPRAS FROM T001 INTO CORRESPONDING FIELDS OF
COMP_DATA
WHERE BUKRS = IS_BIL_INVOICE-HD_ORG-COMP_CODE.

SELECT SINGLE KALSM FROM T005 INTO ZKALSM WHERE LAND1 = COMP_DATA-LAND1.

SELECT SINGLE TEXT1 FROM T007S INTO TAX_TEXT WHERE
SPRAS = IS_NAST-SPRAS AND
KALSM = ZKALSM AND
MWSKZ = GS_IT_KOND_W-MWSKZ.

IF SY-SUBRC <> 0.
SELECT SINGLE TEXT1 FROM T007S INTO TAX_TEXT WHERE
SPRAS = COMP_DATA-SPRAS AND
KALSM = ZKALSM AND
MWSKZ = GS_IT_KOND_W-MWSKZ.
ENDIF.


IF GS_IT_KOND_W-KBETR < 0.
GS_IT_KOND_W-KBETR = GS_IT_KOND_W-KBETR * -1.
ENDIF.

TX_BASE = GS_IT_KOND_W-KAWRT.
*IF TX_BASE = '0'.
*  TX_BASE = GS_IT_KOND_W-KAWRT.
*ELSE.
*  TX_BASE = TX_BASE + GS_IT_KOND_W-KAWRT.
*ENDIF.

