DATA LS_EKPO TYPE EKPO.
CLEAR GV_SPEC_CUR_DECIMAL.
LOOP AT IT_EKPO INTO LS_EKPO.
IF IS_EKKO-BSTYP EQ 'K' OR    " Doc Type = Contract
IS_EKKO-STAKO NE SPACE.    " Doc w/ time-dependent cond
IF LS_EKPO-LOEKZ NE 'L'.    " Deletion indicator
IF LS_EKPO-PSTYP EQ '9'.  " Service
GV_TOTAL = GV_TOTAL + LS_EKPO-NETPR.
ELSE.
GV_TOTAL = GV_TOTAL + LS_EKPO-ZWERT.
ENDIF.
ENDIF.
ENDIF.
ENDLOOP.

* Check document currency
IF NOT GV_SPEC_CUR_DECIMAL IS INITIAL.
WRITE GV_TOTAL       TO       GV_TOTAL_IN_DOC_CUR
CURRENCY IS_EKKO-WAERS.
ENDIF.



