
DATA LS_KEY_DATA TYPE RSEROB.
DATA LT_SERNOS   TYPE TABLE OF RSEROB.
DATA LS_SERNOS   TYPE RSEROB.
DATA LT_KOMSER   TYPE TABLE OF RISERLS.
DATA LS_KOMSER   TYPE RISERLS.

CLEAR GT_KOMSER_PRT.

LS_KEY_DATA-TASER   = 'SER02'.
LS_KEY_DATA-SDAUFNR = IS_VBDKA-VBELN.
LS_KEY_DATA-POSNR   = <FS>-POSNR.
IF LS_KEY_DATA-SDAUFNR IS INITIAL AND
NOT LS_KEY_DATA-POSNR IS INITIAL.
LS_KEY_DATA-SDAUFNR = '$'.
ENDIF.

* Read the Serialnumbers of a Position.
CALL FUNCTION 'GET_SERNOS_OF_DOCUMENT'
EXPORTING
KEY_DATA            = LS_KEY_DATA
TABLES
SERNOS              = LT_SERNOS
EXCEPTIONS
KEY_PARAMETER_ERROR = 1
NO_SUPPORTED_ACCESS = 2
NO_DATA_FOUND       = 3
OTHERS              = 4.

CHECK SY-SUBRC EQ 0.

LOOP AT LT_SERNOS INTO LS_SERNOS.
LS_KOMSER-VBELN = LS_SERNOS-SDAUFNR.
LS_KOMSER-POSNR = LS_SERNOS-POSNR.
LS_KOMSER-SERNR = LS_SERNOS-SERNR.
APPEND LS_KOMSER TO LT_KOMSER.
ENDLOOP.

* Process the stringtable for Printing.
CALL FUNCTION 'PROCESS_SERIALS_FOR_PRINT'
EXPORTING
I_BOUNDARY_LEFT             = '(_'
I_BOUNDARY_RIGHT            = '_)'
I_SEP_CHAR_STRINGS          = ',_'
I_SEP_CHAR_INTERVAL         = '_-_'
I_USE_INTERVAL              = 'X'
I_BOUNDARY_METHOD           = 'C'
I_LINE_LENGTH               = 50
I_NO_ZERO                   = 'X'
I_ALPHABET                  = SY-ABCDE
I_DIGITS                    = '0123456789'
I_SPECIAL_CHARS             = '-'
I_WITH_SECOND_DIGIT         = ' '
TABLES
SERIALS                     = LT_KOMSER
SERIALS_PRINT               = GT_KOMSER_PRT
EXCEPTIONS
BOUNDARY_MISSING            = 01
INTERVAL_SEPARATION_MISSING = 02
LENGTH_TO_SMALL             = 03
INTERNAL_ERROR              = 04
WRONG_METHOD                = 05
WRONG_SERIAL                = 06
TWO_EQUAL_SERIALS           = 07
SERIAL_WITH_WRONG_CHAR      = 08
SERIAL_SEPARATION_MISSING   = 09.





















