TYPES: BEGIN OF TY_CHG_TEXTS,
EBELN TYPE EKPO-EBELN,
EBELP TYPE EKPO-EBELP,
CTXNR TYPE T166T-CTXNR,
CHTXT TYPE T166T-CHTXT,
F_OLD TYPE CDSHW-F_OLD,
F_NEW TYPE CDSHW-F_NEW,
END OF TY_CHG_TEXTS.

TYPES: BEGIN OF TY_MEEIN_XAEND.
INCLUDE STRUCTURE CDSHW.
TYPES:
EBELP LIKE EKPO-EBELP,
ZEKKN LIKE EKKN-ZEKKN,
ETENR LIKE EKET-ETENR,
CTXNR LIKE T166C-CTXNR,
ROUNR LIKE T166C-ROUNR,
INSERT,
FLAG_ADRNR,
END OF TY_MEEIN_XAEND.

TYPES TY_MEEIN_XAEND_TAB
TYPE STANDARD TABLE OF TY_MEEIN_XAEND.

* Type for Header Texts, Item Texts and QM Texts
TYPES: BEGIN OF TY_TEXT.
INCLUDE STRUCTURE THEAD.
TYPES:  TDTEXT LIKE TTXIT-TDTEXT,
END OF TY_TEXT.

* Type for Manufacturing Part Number
TYPES  : BEGIN OF TY_HTNM.
INCLUDE STRUCTURE V_HTNM.
TYPES:   REVLV LIKE RAMPL-REVLV,
END OF TY_HTNM.

TYPES: BEGIN OF TY_ZTERM_TXT,
LINE(50),
END OF TY_ZTERM_TXT.

*TYPE for calculating tax totals
TYPES: BEGIN OF Y_POTAXES,
TELLER TYPE I,
TAXCODE TYPE MWSKZ,
TAXCOND TYPE KSCHL,
TXNAME TYPE VTXTK,
TXPERCENTAGE TYPE KBETR_KOND,
TXAMOUNT TYPE P DECIMALS 2,
END OF Y_POTAXES.

TYPES TY_POTAXES TYPE STANDARD TABLE OF Y_POTAXES with default key initial size 0.

*Test system fields
TYPES: BEGIN OF sysinfo,
system       TYPE	cccategory,
fonam	       TYPE	na_fname,
sform	       TYPE	na_fname,
pgnam	       TYPE	na_pgnam,
param    	TYPE	char1,
END OF sysinfo.





