
* DECDIDING THE LANGUAGE KEY
DATA: L_LANGU TYPE DDLANGUAGE.
IF GV_LANGUAGE IS INITIAL.
L_LANGU = SY-LANGU.
ELSE.
L_LANGU = GV_LANGUAGE.
ENDIF.

*S WE / H WA
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE shkzg FROM t156 INTO gv_shkzg
*WHERE bwart = is_mseg-bwart.
*
* NEW CODE
SELECT shkzg
UP TO 1 ROWS  FROM t156 INTO gv_shkzg
WHERE bwart = is_mseg-bwart ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

IF gv_shkzg = 'S'.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE ltext FROM t003t INTO gv_title
*WHERE spras = l_langu
*AND  blart = 'WE'.
*
* NEW CODE
SELECT ltext
UP TO 1 ROWS  FROM t003t INTO gv_title
WHERE spras = l_langu
AND  blart = 'WE' ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
*AND  BLART = IS_MKPF-BLART.
ELSE.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE ltext FROM t003t INTO gv_title
*WHERE spras = l_langu
*AND  blart = 'WA'.
*
* NEW CODE
SELECT ltext
UP TO 1 ROWS  FROM t003t INTO gv_title
WHERE spras = l_langu
AND  blart = 'WA' ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
ENDIF.












