DATA: WA_T166K TYPE T166K.
DATA: WT_TEXTS TYPE TABLE OF TY_TEXT.
DATA: WA_TEXT TYPE TY_TEXT.

WA_TEXT-TDOBJECT = 'EKKO'.
WA_TEXT-TDSPRAS  = GV_LANGUAGE.
WA_TEXT-TDNAME   = IS_EKKO-EBELN.

CLEAR GT_HD_TEXTS.

CALL FUNCTION 'SELECT_TEXT'
EXPORTING
OBJECT     = WA_TEXT-TDOBJECT
NAME       = WA_TEXT-TDNAME
ID         = '*'
LANGUAGE   = WA_TEXT-TDSPRAS
TABLES
SELECTIONS = WT_TEXTS.
IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ENDIF.
SORT WT_TEXTS BY TDID.

* read IMG setting -- table T166K
* append texts allowed to GT_HD_TEXTS
* Head Text Part
CLEAR WA_TEXT.
LOOP AT WT_TEXTS INTO WA_TEXT.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE *  FROM T166K  INTO WA_T166K
*WHERE DRUVO = IV_DRUVO  AND
*BSTYP = IS_EKKO-BSTYP  AND
*BSART = IS_EKKO-BSART  AND
*TDOBJECT = WA_TEXT-TDOBJECT AND
*TDID  = WA_TEXT-TDID.
*
* NEW CODE
SELECT *
UP TO 1 ROWS   FROM T166K  INTO WA_T166K
WHERE DRUVO = IV_DRUVO  AND
BSTYP = IS_EKKO-BSTYP  AND
BSART = IS_EKKO-BSART  AND
TDOBJECT = WA_TEXT-TDOBJECT AND
TDID  = WA_TEXT-TDID ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
IF SY-SUBRC = 0.
APPEND WA_TEXT TO GT_HD_TEXTS.
ENDIF.
CLEAR WA_TEXT.
ENDLOOP.


















