* read condition data
CLEAR GS_IT_KOND.
CLEAR GS_IT_PRICE.
CLEAR GS_PRICE.

* DATA: GS_IT_KOND_WA TYPE LBBIL_IT_KOND.
LOOP AT IS_BIL_INVOICE-IT_KOND INTO GS_IT_KOND_WA
WHERE BIL_NUMBER = GS_IT_GEN-BIL_NUMBER
AND ITM_NUMBER = GS_IT_GEN-ITM_NUMBER.

IF GS_IT_KOND_WA-KNTYP = 'F'.
ADD GS_IT_KOND_WA-KWERT TO GV_FREIGHT_SUM.
ENDIF.

IF GS_IT_KOND_WA-KNTYP = 'D'.
*    ADD GS_IT_KOND_WA-KWERT TO GS_TAXVAL.
READ TABLE GS_IT_KOND_TX INTO GS_IT_KOND_TX_W
WITH KEY MWSKZ = GS_IT_KOND_WA-MWSKZ.
IF SY-SUBRC = 0.
ADD: GS_IT_KOND_WA-KAWRT TO GS_IT_KOND_TX_W-KAWRT,
GS_IT_KOND_WA-KWERT TO GS_IT_KOND_TX_W-KWERT.
MODIFY GS_IT_KOND_TX FROM GS_IT_KOND_TX_W
TRANSPORTING KAWRT KWERT
WHERE MWSKZ = GS_IT_KOND_TX_W-MWSKZ .
ELSE.
APPEND GS_IT_KOND_WA TO GS_IT_KOND_TX.
ENDIF.
ENDIF.

APPEND GS_IT_KOND_WA TO GS_IT_KOND.

ENDLOOP.

READ TABLE GS_IT_KOND INTO GS_IT_KOND_WA INDEX 1 .
MOVE GS_IT_KOND_WA-KBETR TO GS_PRICE.
MOVE GS_IT_KOND_WA TO GS_IT_PRICE.



