DATA: WA_T166A TYPE T166A.
DATA: WT_TEXTS TYPE TABLE OF TY_TEXT.
DATA: WA_TEXT TYPE TY_TEXT.
WA_TEXT-TDOBJECT = 'EKKO'.
WA_TEXT-TDSPRAS  = GV_LANGUAGE.
WA_TEXT-TDNAME   = IS_EKKO-EBELN.

CLEAR GT_SUP_TEXTS.

CALL FUNCTION 'SELECT_TEXT'
EXPORTING
OBJECT     = WA_TEXT-TDOBJECT
NAME       = WA_TEXT-TDNAME
ID         = '*'
LANGUAGE   = WA_TEXT-TDSPRAS
TABLES
SELECTIONS = WT_TEXTS.
IF SY-SUBRC <> 0.
* MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
*         WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
ENDIF.
SORT WT_TEXTS BY TDID.

* append texts allowed to GT_SUP_TEXTS
* Supplement Text Part
CLEAR WA_TEXT.
LOOP AT WT_TEXTS INTO WA_TEXT.
SELECT SINGLE *
FROM T166A INTO WA_T166A
WHERE DRUVO = IV_DRUVO  AND
BSTYP = IS_EKKO-BSTYP  AND
BSART = IS_EKKO-BSART  AND
TDOBJECT = WA_TEXT-TDOBJECT AND
TDID  = WA_TEXT-TDID.
IF SY-SUBRC = 0.
APPEND WA_TEXT TO GT_SUP_TEXTS.
ENDIF.
CLEAR WA_TEXT.
ENDLOOP.


















