PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZNOVEDADBANCO CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZNOVEDADBANCO-SOCIEDAD .
    FIELD ZNOVEDADBANCO-BANCO .
    FIELD ZNOVEDADBANCO-NOMINA .
    FIELD ZNOVEDADBANCO-FECHA .
    FIELD ZNOVEDADBANCO-HORA .
    FIELD ZNOVEDADBANCO-IDENTIF .
    FIELD ZNOVEDADBANCO-NUMEMP .
    FIELD ZNOVEDADBANCO-RUTEMI .
    FIELD ZNOVEDADBANCO-CUENTA .
    FIELD ZNOVEDADBANCO-NOMBEN .
    FIELD ZNOVEDADBANCO-RUTBEN .
    FIELD ZNOVEDADBANCO-MONTOW .
    FIELD ZNOVEDADBANCO-NUMCHE .
    FIELD ZNOVEDADBANCO-ESTPAG .
    FIELD ZNOVEDADBANCO-CENPAG .
    FIELD ZNOVEDADBANCO-FECREC .
    FIELD ZNOVEDADBANCO-NUMLOT .
    FIELD ZNOVEDADBANCO-FECPRO .
    FIELD ZNOVEDADBANCO-FECPAG .
    FIELD ZNOVEDADBANCO-FECEST .
    FIELD ZNOVEDADBANCO-ESTADO .
    FIELD ZNOVEDADBANCO-MOTELI .
    FIELD ZNOVEDADBANCO-FECELI .
    FIELD ZNOVEDADBANCO-HORELI .
    FIELD ZNOVEDADBANCO-USRELI .
    FIELD ZNOVEDADBANCO-INGRES .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZNOVEDADBANCO-SOCIEDAD .
    FIELD ZNOVEDADBANCO-BANCO .
    FIELD ZNOVEDADBANCO-NOMINA .
    FIELD ZNOVEDADBANCO-FECHA .
    FIELD ZNOVEDADBANCO-HORA .
    FIELD ZNOVEDADBANCO-IDENTIF .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
