REPORT Z_OBLIGA_ISA1_DIARIO message-id 26 line-size 255

no standard page heading.
* Z_OBLIGA_ISA1_DIARIO.
PARAMETER DOWNLOAD(1) DEFAULT 'S' lower case. "N-svr,Y-clnt
PARAMETER EXECMODE(1) DEFAULT 'D' lower case. "D-dlg,B-btch
PARAMETER OUT_DIR(230) DEFAULT "output file dir
'\\172.31.100.100\' lower case.
PARAMETER IN_DIR(230) DEFAULT "input file dir
'\\172.31.100.100\' lower case.
PARAMETER P_DEST TYPE RFCDES-RFCDEST DEFAULT
'NONE'.
PARAMETER P_PROGID TYPE RFCOPT-RFCEXEC DEFAULT
SPACE.
PARAMETER P_GWHOST TYPE RFCOPT-RFCGWHOST DEFAULT
SPACE.
PARAMETER P_GWSERV TYPE RFCOPT-RFCGWSERV DEFAULT
SPACE.
PARAMETER P_SRVFM(30) DEFAULT "Server Callback function
SPACE.
PARAMETER P_PKGSZ TYPE I DEFAULT "Stream package size
5000.
PARAMETER P_SNC_ON(1) DEFAULT "X-on SPACE-off
SPACE.

PARAMETER $PARAM1(4) TYPE C.

PARAMETER $PARAM2 TYPE D.

PARAMETER $PARAM3 TYPE D.

PARAMETER P_DF_VK(40) DEFAULT "ABAP data flow object key
'' lower case.
PARAMETER P_DI_GEN(40) DEFAULT "DI version that generated ABAP
'' lower case.

*** Machine generated ABAP. Do not modify.            ***
*** (C)Copyright Business Objects S.A.  All rights reserved. ***
*
* Date Time:
*    08/24/21 12:32:47
* SAP used for generated this ABAP:
*    Release: 750
*    Host   : 172.31.100.100
*
* ABAP Dataflow Name:
*    ABAP_BSAK_1_2
* ABAP program name in SAP:
*  Z_OBLIGA_ISA1_DIARIO
* Generated ABAP file name:
*  C:/ProgramData/SAP BusinessObjects/Data Services/workspace/Z_O
*BLI
*    GA_ISA1_DIARIO
TABLES BKPF.
TABLES BSAK.
TABLES LFA1.
TABLES REGUH.

DATA: begin of ITAB3 occurs 0,
BUKRS(4) TYPE C,
BELNR(10) TYPE C,
GJAHR(4) TYPE N,
XBLNR(16) TYPE C,
STBLG(10) TYPE C,
BKTXT(25) TYPE C,
AWKEY(20) TYPE C,
XREF2_HD(20) TYPE C,
LIFNR(10) TYPE C,
BUDAT TYPE D,
BLDAT TYPE D,
CPUDT TYPE D,
AUGBL(10) TYPE C,
AUGDT TYPE D,
ZUONR(18) TYPE C,
BLART(2) TYPE C,
SHKZG(1) TYPE C,
DMBTR(16) TYPE P DECIMALS 2,
SGTXT(50) TYPE C,
HKONT(10) TYPE C,
ZFBDT TYPE D,
ZLSCH(1) TYPE C,
HBKID(5) TYPE C,
XREF1(12) TYPE C,
XREF2(12) TYPE C,
XREF3(20) TYPE C,
ZZMOT_EMIS(10) TYPE C,
ZZRUT_TERC(10) TYPE C,
ZZ_AGENCIA(10) TYPE C,
BVTYP(4) TYPE C,
BUZEI(3) TYPE N.
DATA: end of ITAB3.

DATA: begin of ITAB6 occurs 0,
AIColumn60(4) TYPE C,
AIColumn61(10) TYPE C,
AIColumn62(4) TYPE N,
AIColumn63(16) TYPE C,
AIColumn64(10) TYPE C,
AIColumn65(25) TYPE C,
AIColumn66(20) TYPE C,
AIColumn67(20) TYPE C,
AIColumn68(10) TYPE C,
AIColumn69(16) TYPE C,
AIColumn70(71) TYPE C,
AIColumn71 TYPE D,
AIColumn72 TYPE D,
AIColumn73 TYPE D,
AIColumn74(10) TYPE C,
AIColumn75 TYPE D,
AIColumn76(18) TYPE C,
AIColumn77(2) TYPE C,
AIColumn78(1) TYPE C,
AIColumn79(16) TYPE P DECIMALS 2,
AIColumn80(50) TYPE C,
AIColumn81(10) TYPE C,
AIColumn82 TYPE D,
AIColumn83(1) TYPE C,
AIColumn84(5) TYPE C,
AIColumn85(12) TYPE C,
AIColumn86(12) TYPE C,
AIColumn87(20) TYPE C,
AIColumn88(10) TYPE C,
AIColumn89(10) TYPE C,
AIColumn90(10) TYPE C,
AIColumn91(3) TYPE N,
BUKRS(4) TYPE C,
LIFNR(10) TYPE C,
AUGBL(10) TYPE C,
BUDAT TYPE D,
AIColumn92(10) TYPE C.
DATA: end of ITAB6.

DATA: begin of ITAB7 occurs 0,
BUKRS(4) TYPE C,
BELNR(10) TYPE C,
GJAHR(4) TYPE N,
XBLNR(16) TYPE C,
STBLG(10) TYPE C,
BKTXT(25) TYPE C,
AWKEY(20) TYPE C,
XREF2_HD(20) TYPE C,
LIFNR(10) TYPE C,
STCD1(16) TYPE C,
NOMBRE(76) TYPE C,
BUDAT TYPE D,
BLDAT TYPE D,
CPUDT TYPE D,
AUGBL(10) TYPE C,
AUGDT TYPE D,
ZUONR(18) TYPE C,
BLART(2) TYPE C,
SHKZG(1) TYPE C,
DMBTR(16) TYPE P DECIMALS 2,
SGTXT(50) TYPE C,
HKONT(10) TYPE C,
ZFBDT TYPE D,
ZLSCH(1) TYPE C,
HBKID(5) TYPE C,
XREF1(12) TYPE C,
XREF2(12) TYPE C,
XREF3(20) TYPE C,
ZZMOT_EMIS(10) TYPE C,
ZZRUT_TERC(10) TYPE C,
ZZ_AGENCIA(10) TYPE C,
LAUFD TYPE D,
LAUFI(6) TYPE C,
IDENTIF_PAGO(15) TYPE C,
FECHA_ENVIO TYPE D,
USUARIO_ENVIO(12) TYPE C,
IND_PAGO(1) TYPE C,
FECHA_PAGO TYPE D,
IND_DEVUELTO(1) TYPE C,
FECHA_DEVUELTO TYPE D,
IND_RECHAZO(1) TYPE C,
FECHA_RECHAZO TYPE D,
BELNR_DEV(10) TYPE C,
GJAHR_DEV(4) TYPE N,
IND_CUSTODIA(1) TYPE C,
FECHA_CUSTODIA TYPE D,
MOTIVO_RECHAZO(40) TYPE C,
IND_ENTREGADO(1) TYPE C,
FECHA_ENTREGADO TYPE D,
IND_RESCATADO(1) TYPE C,
FECHA_RESCATADO TYPE D,
IND_REDEPO(1) TYPE C,
FECHA_REDEPO TYPE D,
GLOSA_REDEPO(25) TYPE C,
ZBVTY(4) TYPE C,
BUZEI(3) TYPE N,
ZBNKL(15) TYPE C,
ZBNKN(18) TYPE C.
DATA: end of ITAB7.

DATA: begin of ITAB8 occurs 0,
BUKRS(4) TYPE C,
BELNR(10) TYPE C,
GJAHR(4) TYPE N,
XBLNR(16) TYPE C,
STBLG(10) TYPE C,
BKTXT(25) TYPE C,
AWKEY(20) TYPE C,
XREF2_HD(20) TYPE C,
LIFNR(10) TYPE C,
STCD1(16) TYPE C,
NOMBRE(76) TYPE C,
BUDAT TYPE D,
BLDAT TYPE D,
CPUDT TYPE D,
AUGBL(10) TYPE C,
AUGDT TYPE D,
ZUONR(18) TYPE C,
BLART(2) TYPE C,
SHKZG(1) TYPE C,
DMBTR(16) TYPE P DECIMALS 2,
SGTXT(50) TYPE C,
HKONT(10) TYPE C,
ZFBDT TYPE D,
ZLSCH(1) TYPE C,
HBKID(5) TYPE C,
XREF1(12) TYPE C,
XREF2(12) TYPE C,
XREF3(20) TYPE C,
ZZMOT_EMIS(10) TYPE C,
ZZRUT_TERC(10) TYPE C,
ZZ_AGENCIA(10) TYPE C,
LAUFD TYPE D,
LAUFI(6) TYPE C,
IDENTIF_PAGO(15) TYPE C,
FECHA_ENVIO TYPE D,
USUARIO_ENVIO(12) TYPE C,
IND_PAGO(1) TYPE C,
FECHA_PAGO TYPE D,
IND_DEVUELTO(1) TYPE C,
FECHA_DEVUELTO TYPE D,
IND_RECHAZO(1) TYPE C,
FECHA_RECHAZO TYPE D,
BELNR_DEV(10) TYPE C,
GJAHR_DEV(4) TYPE N,
IND_CUSTODIA(1) TYPE C,
FECHA_CUSTODIA TYPE D,
MOTIVO_RECHAZO(40) TYPE C,
IND_ENTREGADO(1) TYPE C,
FECHA_ENTREGADO TYPE D,
IND_RESCATADO(1) TYPE C,
FECHA_RESCATADO TYPE D,
IND_REDEPO(1) TYPE C,
FECHA_REDEPO TYPE D,
GLOSA_REDEPO(25) TYPE C,
ZBVTY(4) TYPE C,
BUZEI(3) TYPE N,
ZBNKL(15) TYPE C,
ZBNKN(18) TYPE C.
DATA: end of ITAB8.

data: append_flag(1) value ' ',
      cntbuf type i,
      delimleng type i,last_batch(1) value ' '.

CONSTANTS C_DF_VK(40) VALUE '486'.
CONSTANTS C_DI_GEN(40) VALUE '14.2.13.2467'.
DATA WARN_MSG(50).


start-of-selection.


  IF DOWNLOAD = 'S' OR
     DOWNLOAD = 'N' OR
     DOWNLOAD = 'Y'.
      .
  ELSE.
     DATA: m_xfer_err_msg(700).
     CONCATENATE
'ABAP program does not recognize this new '
'data transfer method: ' DOWNLOAD
'. Regenerate the ABAP program and upload to this system.'
     INTO m_xfer_err_msg.
     MESSAGE  E240(S#) WITH m_xfer_err_msg.
  ENDIF.

  IF EXECMODE = 'B' OR
     EXECMODE = 'D'.
      .
  ELSE.
     DATA: m_exec_err_msg(700).
     CONCATENATE
'ABAP program does not recognize this new '
'execution option: ' EXECMODE
'. Regenerate the ABAP program and upload to this system.'
     INTO m_exec_err_msg.
     MESSAGE  E240(S#) WITH m_exec_err_msg.
  ENDIF.

  IF DOWNLOAD = 'S'.
     PERFORM CONNECT_RFCDEST_TO_PROGID.
  ENDIF.



PERFORM FORM4.
PERFORM FORM6.
FREE ITAB3.
PERFORM FORM7.
FREE ITAB6.
PERFORM FORM9.
FREE ITAB8.
last_batch = 'X'.
PERFORM FORM8.
FREE ITAB7.
  IF DOWNLOAD = 'S'.
     PERFORM DISCONNECT_RFCDEST_FROM_PROGID.
  ENDIF.


end-of-selection.

CLEAR WARN_MSG.

IF NOT P_DF_VK IS INITIAL.
  IF P_DF_VK <> C_DF_VK.
     CONCATENATE '$$Warning$'
                 C_DF_VK
                 '$' INTO WARN_MSG.
  ENDIF.
ENDIF.
IF NOT P_DI_GEN IS INITIAL.
  IF P_DI_GEN <> C_DI_GEN.
     IF WARN_MSG IS INITIAL.
       CONCATENATE '$$Warning$$'
                   C_DI_GEN
                   INTO WARN_MSG.
     ELSE.
       CONCATENATE WARN_MSG
                   C_DI_GEN
                   INTO WARN_MSG.
     ENDIF.
  ENDIF.
ENDIF.

IF NOT WARN_MSG IS INITIAL.
  IF EXECMODE = 'D'.
    WRITE WARN_MSG.
    NEW-LINE.
  ELSE.
    MESSAGE S240(S#) with WARN_MSG.
  ENDIF.
ENDIF.


write  '* Program Complete *'.
write
 '(C)Copyright Business Objects S.A.  All rights reserved.'.

FORM FORM4.
STATICS rowCount TYPE i VALUE 0.
DATA ALTMP1(4) TYPE C.
DATA ALTMP2(10) TYPE C.
DATA ALTMP3(4) TYPE N.
DATA ALTMP4(16) TYPE C.
DATA ALTMP5(10) TYPE C.
DATA ALTMP6(25) TYPE C.
DATA ALTMP7(20) TYPE C.
DATA ALTMP8(20) TYPE C.
DATA ALTMP9(10) TYPE C.
DATA ALTMP10 TYPE D.
DATA ALTMP11 TYPE D.
DATA ALTMP12 TYPE D.
DATA ALTMP13(10) TYPE C.
DATA ALTMP14 TYPE D.
DATA ALTMP15(18) TYPE C.
DATA ALTMP16(2) TYPE C.
DATA ALTMP17(1) TYPE C.
DATA ALTMP18(16) TYPE P DECIMALS 2.
DATA ALTMP19(50) TYPE C.
DATA ALTMP20(10) TYPE C.
DATA ALTMP21 TYPE D.
DATA ALTMP22(1) TYPE C.
DATA ALTMP23(5) TYPE C.
DATA ALTMP24(12) TYPE C.
DATA ALTMP25(12) TYPE C.
DATA ALTMP26(20) TYPE C.
DATA ALTMP27(10) TYPE C.
DATA ALTMP28(10) TYPE C.
DATA ALTMP29(10) TYPE C.
DATA ALTMP30(4) TYPE C.
DATA ALTMP31(3) TYPE N.

DATA BKPF9BUKRS LIKE BKPF-BUKRS.
DATA BKPF9BELNR LIKE BKPF-BELNR.
DATA BKPF9GJAHR LIKE BKPF-GJAHR.
DATA BKPF9XBLNR LIKE BKPF-XBLNR.
DATA BKPF9STBLG LIKE BKPF-STBLG.
DATA BKPF9BKTXT LIKE BKPF-BKTXT.
DATA BKPF9AWKEY LIKE BKPF-AWKEY.
DATA BKPF9XREF2_HD LIKE BKPF-XREF2_HD.
DATA BSAK9LIFNR LIKE BSAK-LIFNR.
DATA BSAK9BUDAT LIKE BSAK-BUDAT.
DATA BSAK9BLDAT LIKE BSAK-BLDAT.
DATA BSAK9CPUDT LIKE BSAK-CPUDT.
DATA BSAK9AUGBL LIKE BSAK-AUGBL.
DATA BSAK9AUGDT LIKE BSAK-AUGDT.
DATA BSAK9ZUONR LIKE BSAK-ZUONR.
DATA BSAK9BLART LIKE BSAK-BLART.
DATA BSAK9SHKZG LIKE BSAK-SHKZG.
DATA BSAK9DMBTR LIKE BSAK-DMBTR.
DATA BSAK9SGTXT LIKE BSAK-SGTXT.
DATA BSAK9HKONT LIKE BSAK-HKONT.
DATA BSAK9ZFBDT LIKE BSAK-ZFBDT.
DATA BSAK9ZLSCH LIKE BSAK-ZLSCH.
DATA BSAK9HBKID LIKE BSAK-HBKID.
DATA BSAK9XREF1 LIKE BSAK-XREF1.
DATA BSAK9XREF2 LIKE BSAK-XREF2.
DATA BSAK9XREF3 LIKE BSAK-XREF3.
DATA BSAK9ZZMOT_EMIS LIKE BSAK-ZZMOT_EMIS.
DATA BSAK9ZZRUT_TERC LIKE BSAK-ZZRUT_TERC.
DATA BSAK9ZZ_AGENCIA LIKE BSAK-ZZ_AGENCIA.
DATA BSAK9BVTYP LIKE BSAK-BVTYP.
DATA BSAK9BUZEI LIKE BSAK-BUZEI.



SELECT DISTINCT
  BKPF9~BUKRS
  BKPF9~BELNR
  BKPF9~GJAHR
  BKPF9~XBLNR
  BKPF9~STBLG
  BKPF9~BKTXT
  BKPF9~AWKEY
  BKPF9~XREF2_HD
  BSAK9~LIFNR
  BSAK9~BUDAT
  BSAK9~BLDAT
  BSAK9~CPUDT
  BSAK9~AUGBL
  BSAK9~AUGDT
  BSAK9~ZUONR
  BSAK9~BLART
  BSAK9~SHKZG
  BSAK9~DMBTR
  BSAK9~SGTXT
  BSAK9~HKONT
  BSAK9~ZFBDT
  BSAK9~ZLSCH
  BSAK9~HBKID
  BSAK9~XREF1
  BSAK9~XREF2
  BSAK9~XREF3
  BSAK9~ZZMOT_EMIS
  BSAK9~ZZRUT_TERC
  BSAK9~ZZ_AGENCIA
  BSAK9~BVTYP
  BSAK9~BUZEI
into (BKPF9BUKRS,
  BKPF9BELNR,
  BKPF9GJAHR,
  BKPF9XBLNR,
  BKPF9STBLG,
  BKPF9BKTXT,
  BKPF9AWKEY,
  BKPF9XREF2_HD,
  BSAK9LIFNR,
  BSAK9BUDAT,
  BSAK9BLDAT,
  BSAK9CPUDT,
  BSAK9AUGBL,
  BSAK9AUGDT,
  BSAK9ZUONR,
  BSAK9BLART,
  BSAK9SHKZG,
  BSAK9DMBTR,
  BSAK9SGTXT,
  BSAK9HKONT,
  BSAK9ZFBDT,
  BSAK9ZLSCH,
  BSAK9HBKID,
  BSAK9XREF1,
  BSAK9XREF2,
  BSAK9XREF3,
  BSAK9ZZMOT_EMIS,
  BSAK9ZZRUT_TERC,
  BSAK9ZZ_AGENCIA,
  BSAK9BVTYP,
  BSAK9BUZEI)
FROM BSAK AS BSAK9
 INNER JOIN BKPF AS BKPF9
 ON ( ( BKPF9~GJAHR = BSAK9~GJAHR )
 AND ( ( BKPF9~BELNR = BSAK9~BELNR )
 AND ( BKPF9~BUKRS = BSAK9~BUKRS ) ) )
WHERE ( BSAK9~BLART IN ('ZP')
 AND ( BSAK9~ZLSCH IN ('V',
'T')
 AND ( ( BSAK9~AUGDT <= $PARAM3 )
 AND ( ( BSAK9~AUGDT >= $PARAM2 )
 AND ( BKPF9~BUKRS = $PARAM1 ) ) ) ) ).
ALTMP1 = BKPF9BUKRS.
ALTMP2 = BKPF9BELNR.
ALTMP3 = BKPF9GJAHR.
ALTMP4 = BKPF9XBLNR.
ALTMP5 = BKPF9STBLG.
ALTMP6 = BKPF9BKTXT.
ALTMP7 = BKPF9AWKEY.
ALTMP8 = BKPF9XREF2_HD.
ALTMP9 = BSAK9LIFNR.
ALTMP10 = BSAK9BUDAT.
ALTMP11 = BSAK9BLDAT.
ALTMP12 = BSAK9CPUDT.
ALTMP13 = BSAK9AUGBL.
ALTMP14 = BSAK9AUGDT.
ALTMP15 = BSAK9ZUONR.
ALTMP16 = BSAK9BLART.
ALTMP17 = BSAK9SHKZG.
ALTMP18 = BSAK9DMBTR.
ALTMP19 = BSAK9SGTXT.
ALTMP20 = BSAK9HKONT.
ALTMP21 = BSAK9ZFBDT.
ALTMP22 = BSAK9ZLSCH.
ALTMP23 = BSAK9HBKID.
ALTMP24 = BSAK9XREF1.
ALTMP25 = BSAK9XREF2.
ALTMP26 = BSAK9XREF3.
ALTMP27 = BSAK9ZZMOT_EMIS.
ALTMP28 = BSAK9ZZRUT_TERC.
ALTMP29 = BSAK9ZZ_AGENCIA.
ALTMP30 = BSAK9BVTYP.
ALTMP31 = BSAK9BUZEI.
 move ALTMP1 to ITAB3-BUKRS.
 move ALTMP2 to ITAB3-BELNR.
 move ALTMP3 to ITAB3-GJAHR.
 move ALTMP4 to ITAB3-XBLNR.
 move ALTMP5 to ITAB3-STBLG.
 move ALTMP6 to ITAB3-BKTXT.
 move ALTMP7 to ITAB3-AWKEY.
 move ALTMP8 to ITAB3-XREF2_HD.
 move ALTMP9 to ITAB3-LIFNR.
 move ALTMP10 to ITAB3-BUDAT.
 move ALTMP11 to ITAB3-BLDAT.
 move ALTMP12 to ITAB3-CPUDT.
 move ALTMP13 to ITAB3-AUGBL.
 move ALTMP14 to ITAB3-AUGDT.
 move ALTMP15 to ITAB3-ZUONR.
 move ALTMP16 to ITAB3-BLART.
 move ALTMP17 to ITAB3-SHKZG.
 move ALTMP18 to ITAB3-DMBTR.
 move ALTMP19 to ITAB3-SGTXT.
 move ALTMP20 to ITAB3-HKONT.
 move ALTMP21 to ITAB3-ZFBDT.
 move ALTMP22 to ITAB3-ZLSCH.
 move ALTMP23 to ITAB3-HBKID.
 move ALTMP24 to ITAB3-XREF1.
 move ALTMP25 to ITAB3-XREF2.
 move ALTMP26 to ITAB3-XREF3.
 move ALTMP27 to ITAB3-ZZMOT_EMIS.
 move ALTMP28 to ITAB3-ZZRUT_TERC.
 move ALTMP29 to ITAB3-ZZ_AGENCIA.
 move ALTMP30 to ITAB3-BVTYP.
 move ALTMP31 to ITAB3-BUZEI.
 append ITAB3.
rowCount = rowCount + 1.
IF ( download = 'S' ).
 IF ( rowCount = P_PKGSZ ).
   PERFORM FORM6.
   REFRESH ITAB3.
   rowCount = 0.
 ENDIF.
ELSE.
 IF ( rowCount = 5000 ).
   PERFORM FORM6.
   REFRESH ITAB3.
   rowCount = 0.
 ENDIF.
ENDIF.
ENDSELECT.
ENDFORM.

FORM FORM6.
STATICS rowCount TYPE i VALUE 0.
STATICS firstRun(1) TYPE C VALUE 'Y'.
DATA ALTMP32(4) TYPE C.
DATA ALTMP33(10) TYPE C.
DATA ALTMP34(4) TYPE N.
DATA ALTMP35(16) TYPE C.
DATA ALTMP36(10) TYPE C.
DATA ALTMP37(25) TYPE C.
DATA ALTMP38(20) TYPE C.
DATA ALTMP39(20) TYPE C.
DATA ALTMP40(10) TYPE C.
DATA ALTMP41(16) TYPE C.
DATA ALTMP42(36) TYPE C.
DATA ALTMP43(71) TYPE C.
DATA ALTMP44 TYPE D.
DATA ALTMP45 TYPE D.
DATA ALTMP46 TYPE D.
DATA ALTMP47(10) TYPE C.
DATA ALTMP48 TYPE D.
DATA ALTMP49(18) TYPE C.
DATA ALTMP50(2) TYPE C.
DATA ALTMP51(1) TYPE C.
DATA ALTMP52(16) TYPE P DECIMALS 2.
DATA ALTMP53(50) TYPE C.
DATA ALTMP54(10) TYPE C.
DATA ALTMP55 TYPE D.
DATA ALTMP56(1) TYPE C.
DATA ALTMP57(5) TYPE C.
DATA ALTMP58(12) TYPE C.
DATA ALTMP59(12) TYPE C.
DATA ALTMP60(20) TYPE C.
DATA ALTMP61(10) TYPE C.
DATA ALTMP62(10) TYPE C.
DATA ALTMP63(10) TYPE C.
DATA ALTMP64(3) TYPE N.
DATA ALTMP65(4) TYPE C.
DATA ALTMP66(10) TYPE C.
DATA ALTMP67(10) TYPE C.
DATA ALTMP68 TYPE D.
DATA ALTMP69(10) TYPE C.
DATA ALOJF0 TYPE C.
DATA ALOJF1 TYPE C.



LOOP AT ITAB3.
ALTMP32 = ITAB3-BUKRS.
ALTMP33 = ITAB3-BELNR.
ALTMP34 = ITAB3-GJAHR.
ALTMP35 = ITAB3-XBLNR.
ALTMP36 = ITAB3-STBLG.
ALTMP37 = ITAB3-BKTXT.
ALTMP38 = ITAB3-AWKEY.
ALTMP39 = ITAB3-XREF2_HD.
ALTMP44 = ITAB3-BUDAT.
ALTMP45 = ITAB3-BLDAT.
ALTMP46 = ITAB3-CPUDT.
ALTMP47 = ITAB3-AUGBL.
ALTMP48 = ITAB3-AUGDT.
ALTMP49 = ITAB3-ZUONR.
ALTMP50 = ITAB3-BLART.
ALTMP51 = ITAB3-SHKZG.
ALTMP52 = ITAB3-DMBTR.
ALTMP53 = ITAB3-SGTXT.
ALTMP54 = ITAB3-HKONT.
ALTMP55 = ITAB3-ZFBDT.
ALTMP56 = ITAB3-ZLSCH.
ALTMP57 = ITAB3-HBKID.
ALTMP58 = ITAB3-XREF1.
ALTMP59 = ITAB3-XREF2.
ALTMP60 = ITAB3-XREF3.
ALTMP61 = ITAB3-ZZMOT_EMIS.
ALTMP62 = ITAB3-ZZRUT_TERC.
ALTMP63 = ITAB3-ZZ_AGENCIA.
ALTMP64 = ITAB3-BUZEI.
ALTMP65 = ITAB3-BUKRS.
ALTMP66 = ITAB3-LIFNR.
ALTMP67 = ITAB3-AUGBL.
ALTMP68 = ITAB3-BUDAT.
ALOJF0 = 'Y'.
ALOJF1 = 'N'.
IF ( ALOJF0 = 'Y' ).

SELECT
  LIFNR
  STCD1
  NAME1
  NAME2
INTO CORRESPONDING FIELDS OF LFA1
FROM LFA1
WHERE ( LIFNR = ITAB3-LIFNR ).
ALTMP40 = LFA1-LIFNR.
ALTMP41 = LFA1-STCD1.
concatenate LFA1-NAME1 ' ' into ALTMP42.
concatenate ALTMP42 LFA1-NAME2 into ALTMP43.
ALTMP69 = LFA1-LIFNR.
ALOJF1 = 'Y'.
 move ALTMP32 to ITAB6-AIColumn60.
 move ALTMP33 to ITAB6-AIColumn61.
 move ALTMP34 to ITAB6-AIColumn62.
 move ALTMP35 to ITAB6-AIColumn63.
 move ALTMP36 to ITAB6-AIColumn64.
 move ALTMP37 to ITAB6-AIColumn65.
 move ALTMP38 to ITAB6-AIColumn66.
 move ALTMP39 to ITAB6-AIColumn67.
 move ALTMP40 to ITAB6-AIColumn68.
 move ALTMP41 to ITAB6-AIColumn69.
 move ALTMP43 to ITAB6-AIColumn70.
 move ALTMP44 to ITAB6-AIColumn71.
 move ALTMP45 to ITAB6-AIColumn72.
 move ALTMP46 to ITAB6-AIColumn73.
 move ALTMP47 to ITAB6-AIColumn74.
 move ALTMP48 to ITAB6-AIColumn75.
 move ALTMP49 to ITAB6-AIColumn76.
 move ALTMP50 to ITAB6-AIColumn77.
 move ALTMP51 to ITAB6-AIColumn78.
 move ALTMP52 to ITAB6-AIColumn79.
 move ALTMP53 to ITAB6-AIColumn80.
 move ALTMP54 to ITAB6-AIColumn81.
 move ALTMP55 to ITAB6-AIColumn82.
 move ALTMP56 to ITAB6-AIColumn83.
 move ALTMP57 to ITAB6-AIColumn84.
 move ALTMP58 to ITAB6-AIColumn85.
 move ALTMP59 to ITAB6-AIColumn86.
 move ALTMP60 to ITAB6-AIColumn87.
 move ALTMP61 to ITAB6-AIColumn88.
 move ALTMP62 to ITAB6-AIColumn89.
 move ALTMP63 to ITAB6-AIColumn90.
 move ALTMP64 to ITAB6-AIColumn91.
 move ALTMP65 to ITAB6-BUKRS.
 move ALTMP66 to ITAB6-LIFNR.
 move ALTMP67 to ITAB6-AUGBL.
 move ALTMP68 to ITAB6-BUDAT.
 move ALTMP69 to ITAB6-AIColumn92.
 append ITAB6.
firstRun = 'N' .
rowCount = rowCount + 1.
IF ( download = 'S' ).
 IF ( rowCount = P_PKGSZ ).
   PERFORM FORM7.
   REFRESH ITAB6.
   rowCount = 0.
 ENDIF.
ELSE.
 IF ( rowCount = 5000 ).
   PERFORM FORM7.
   REFRESH ITAB6.
   rowCount = 0.
 ENDIF.
ENDIF.
ENDSELECT.
ENDIF.
IF ( ALOJF1 = 'N' ).
clear LFA1-LIFNR.
clear LFA1-STCD1.
clear LFA1-NAME1.
clear LFA1-NAME2.
clear ALTMP40.
clear ALTMP41.
clear ALTMP42.
clear ALTMP43.
clear ALTMP69.
 move ALTMP32 to ITAB6-AIColumn60.
 move ALTMP33 to ITAB6-AIColumn61.
 move ALTMP34 to ITAB6-AIColumn62.
 move ALTMP35 to ITAB6-AIColumn63.
 move ALTMP36 to ITAB6-AIColumn64.
 move ALTMP37 to ITAB6-AIColumn65.
 move ALTMP38 to ITAB6-AIColumn66.
 move ALTMP39 to ITAB6-AIColumn67.
 move ALTMP40 to ITAB6-AIColumn68.
 move ALTMP41 to ITAB6-AIColumn69.
 move ALTMP43 to ITAB6-AIColumn70.
 move ALTMP44 to ITAB6-AIColumn71.
 move ALTMP45 to ITAB6-AIColumn72.
 move ALTMP46 to ITAB6-AIColumn73.
 move ALTMP47 to ITAB6-AIColumn74.
 move ALTMP48 to ITAB6-AIColumn75.
 move ALTMP49 to ITAB6-AIColumn76.
 move ALTMP50 to ITAB6-AIColumn77.
 move ALTMP51 to ITAB6-AIColumn78.
 move ALTMP52 to ITAB6-AIColumn79.
 move ALTMP53 to ITAB6-AIColumn80.
 move ALTMP54 to ITAB6-AIColumn81.
 move ALTMP55 to ITAB6-AIColumn82.
 move ALTMP56 to ITAB6-AIColumn83.
 move ALTMP57 to ITAB6-AIColumn84.
 move ALTMP58 to ITAB6-AIColumn85.
 move ALTMP59 to ITAB6-AIColumn86.
 move ALTMP60 to ITAB6-AIColumn87.
 move ALTMP61 to ITAB6-AIColumn88.
 move ALTMP62 to ITAB6-AIColumn89.
 move ALTMP63 to ITAB6-AIColumn90.
 move ALTMP64 to ITAB6-AIColumn91.
 move ALTMP65 to ITAB6-BUKRS.
 move ALTMP66 to ITAB6-LIFNR.
 move ALTMP67 to ITAB6-AUGBL.
 move ALTMP68 to ITAB6-BUDAT.
 move ALTMP69 to ITAB6-AIColumn92.
 append ITAB6.
firstRun = 'N' .
rowCount = rowCount + 1.
IF ( download = 'S' ).
 IF ( rowCount = P_PKGSZ ).
   PERFORM FORM7.
   REFRESH ITAB6.
   rowCount = 0.
 ENDIF.
ELSE.
 IF ( rowCount = 5000 ).
   PERFORM FORM7.
   REFRESH ITAB6.
   rowCount = 0.
 ENDIF.
ENDIF.
ENDIF.
ENDLOOP.
ENDFORM.

FORM FORM7.
STATICS firstRun(1) TYPE C VALUE 'Y'.
DATA ALTMP70(4) TYPE C.
DATA ALTMP71(10) TYPE C.
DATA ALTMP72(4) TYPE N.
DATA ALTMP73(16) TYPE C.
DATA ALTMP74(10) TYPE C.
DATA ALTMP75(25) TYPE C.
DATA ALTMP76(20) TYPE C.
DATA ALTMP77(20) TYPE C.
DATA ALTMP78(10) TYPE C.
DATA ALTMP79(16) TYPE C.
DATA ALTMP80(71) TYPE C.
DATA ALTMP81 TYPE D.
DATA ALTMP82 TYPE D.
DATA ALTMP83 TYPE D.
DATA ALTMP84(10) TYPE C.
DATA ALTMP85 TYPE D.
DATA ALTMP86(18) TYPE C.
DATA ALTMP87(2) TYPE C.
DATA ALTMP88(1) TYPE C.
DATA ALTMP89(16) TYPE P DECIMALS 2.
DATA ALTMP90(50) TYPE C.
DATA ALTMP91(10) TYPE C.
DATA ALTMP92 TYPE D.
DATA ALTMP93(1) TYPE C.
DATA ALTMP94(5) TYPE C.
DATA ALTMP95(12) TYPE C.
DATA ALTMP96(12) TYPE C.
DATA ALTMP97(20) TYPE C.
DATA ALTMP98(10) TYPE C.
DATA ALTMP99(10) TYPE C.
DATA ALTMP100(10) TYPE C.
DATA ALTMP101 TYPE D.
DATA ALTMP102(6) TYPE C.
DATA ALTMP103(15) TYPE C.
DATA ALTMP104 TYPE D.
DATA ALTMP105(12) TYPE C.
DATA ALTMP106(1) TYPE C.
DATA ALTMP107 TYPE D.
DATA ALTMP108(1) TYPE C.
DATA ALTMP109 TYPE D.
DATA ALTMP110(1) TYPE C.
DATA ALTMP111 TYPE D.
DATA ALTMP112(10) TYPE C.
DATA ALTMP113(4) TYPE N.
DATA ALTMP114(1) TYPE C.
DATA ALTMP115 TYPE D.
DATA ALTMP116(40) TYPE C.
DATA ALTMP117(1) TYPE C.
DATA ALTMP118 TYPE D.
DATA ALTMP119(1) TYPE C.
DATA ALTMP120 TYPE D.
DATA ALTMP121(1) TYPE C.
DATA ALTMP122 TYPE D.
DATA ALTMP123(25) TYPE C.
DATA ALTMP124(4) TYPE C.
DATA ALTMP125(3) TYPE N.
DATA ALTMP126(15) TYPE C.
DATA ALTMP127(18) TYPE C.
DATA ALOJF1 TYPE C.
DATA ALOJF0 TYPE C.



LOOP AT ITAB6.
ALTMP70 = ITAB6-AIColumn60.
ALTMP71 = ITAB6-AIColumn61.
ALTMP72 = ITAB6-AIColumn62.
ALTMP73 = ITAB6-AIColumn63.
ALTMP74 = ITAB6-AIColumn64.
ALTMP75 = ITAB6-AIColumn65.
ALTMP76 = ITAB6-AIColumn66.
ALTMP77 = ITAB6-AIColumn67.
ALTMP78 = ITAB6-AIColumn68.
ALTMP79 = ITAB6-AIColumn69.
ALTMP80 = ITAB6-AIColumn70.
ALTMP81 = ITAB6-AIColumn71.
ALTMP82 = ITAB6-AIColumn72.
ALTMP83 = ITAB6-AIColumn73.
ALTMP84 = ITAB6-AIColumn74.
ALTMP85 = ITAB6-AIColumn75.
ALTMP86 = ITAB6-AIColumn76.
ALTMP87 = ITAB6-AIColumn77.
ALTMP88 = ITAB6-AIColumn78.
ALTMP89 = ITAB6-AIColumn79.
ALTMP90 = ITAB6-AIColumn80.
ALTMP91 = ITAB6-AIColumn81.
ALTMP92 = ITAB6-AIColumn82.
ALTMP93 = ITAB6-AIColumn83.
ALTMP94 = ITAB6-AIColumn84.
ALTMP95 = ITAB6-AIColumn85.
ALTMP96 = ITAB6-AIColumn86.
ALTMP97 = ITAB6-AIColumn87.
ALTMP98 = ITAB6-AIColumn88.
ALTMP99 = ITAB6-AIColumn89.
ALTMP100 = ITAB6-AIColumn90.
ALTMP125 = ITAB6-AIColumn91.
ALOJF1 = 'Y'.
ALOJF0 = 'N'.
IF ( ALOJF1 = 'Y' ).

SELECT
  LAUFD
  LAUFI
  IDENTIF_PAGO
  FECHA_ENVIO
  USUARIO_ENVIO
  IND_PAGO
  FECHA_PAGO
  IND_DEVUELTO
  FECHA_DEVUELTO
  IND_RECHAZO
  FECHA_RECHAZO
  BELNR_DEV
  GJAHR_DEV
  IND_CUSTODIA
  FECHA_CUSTODIA
  MOTIVO_RECHAZO
  IND_ENTREGADO
  FECHA_ENTREGADO
  IND_RESCATADO
  FECHA_RESCATADO
  IND_REDEPO
  FECHA_REDEPO
  GLOSA_REDEPO
  ZBVTY
  ZBNKL
  ZBNKN
  ZBUKR
  LIFNR
  VBLNR
  ZALDT
INTO CORRESPONDING FIELDS OF REGUH
FROM REGUH
WHERE ( ( ZALDT = ITAB6-BUDAT )
 AND ( ( VBLNR = ITAB6-AUGBL )
 AND ( ( LIFNR = ITAB6-LIFNR )
 AND ( ZBUKR = ITAB6-BUKRS ) ) ) ).
ALTMP101 = REGUH-LAUFD.
ALTMP102 = REGUH-LAUFI.
ALTMP103 = REGUH-IDENTIF_PAGO.
ALTMP104 = REGUH-FECHA_ENVIO.
ALTMP105 = REGUH-USUARIO_ENVIO.
ALTMP106 = REGUH-IND_PAGO.
ALTMP107 = REGUH-FECHA_PAGO.
ALTMP108 = REGUH-IND_DEVUELTO.
ALTMP109 = REGUH-FECHA_DEVUELTO.
ALTMP110 = REGUH-IND_RECHAZO.
ALTMP111 = REGUH-FECHA_RECHAZO.
ALTMP112 = REGUH-BELNR_DEV.
ALTMP113 = REGUH-GJAHR_DEV.
ALTMP114 = REGUH-IND_CUSTODIA.
ALTMP115 = REGUH-FECHA_CUSTODIA.
ALTMP116 = REGUH-MOTIVO_RECHAZO.
ALTMP117 = REGUH-IND_ENTREGADO.
ALTMP118 = REGUH-FECHA_ENTREGADO.
ALTMP119 = REGUH-IND_RESCATADO.
ALTMP120 = REGUH-FECHA_RESCATADO.
ALTMP121 = REGUH-IND_REDEPO.
ALTMP122 = REGUH-FECHA_REDEPO.
ALTMP123 = REGUH-GLOSA_REDEPO.
ALTMP124 = REGUH-ZBVTY.
ALTMP126 = REGUH-ZBNKL.
ALTMP127 = REGUH-ZBNKN.
ALOJF0 = 'Y'.
 move ALTMP70 to ITAB8-BUKRS.
 move ALTMP71 to ITAB8-BELNR.
 move ALTMP72 to ITAB8-GJAHR.
 move ALTMP73 to ITAB8-XBLNR.
 move ALTMP74 to ITAB8-STBLG.
 move ALTMP75 to ITAB8-BKTXT.
 move ALTMP76 to ITAB8-AWKEY.
 move ALTMP77 to ITAB8-XREF2_HD.
 move ALTMP78 to ITAB8-LIFNR.
 move ALTMP79 to ITAB8-STCD1.
 move ALTMP80 to ITAB8-NOMBRE.
 move ALTMP81 to ITAB8-BUDAT.
 move ALTMP82 to ITAB8-BLDAT.
 move ALTMP83 to ITAB8-CPUDT.
 move ALTMP84 to ITAB8-AUGBL.
 move ALTMP85 to ITAB8-AUGDT.
 move ALTMP86 to ITAB8-ZUONR.
 move ALTMP87 to ITAB8-BLART.
 move ALTMP88 to ITAB8-SHKZG.
 move ALTMP89 to ITAB8-DMBTR.
 move ALTMP90 to ITAB8-SGTXT.
 move ALTMP91 to ITAB8-HKONT.
 move ALTMP92 to ITAB8-ZFBDT.
 move ALTMP93 to ITAB8-ZLSCH.
 move ALTMP94 to ITAB8-HBKID.
 move ALTMP95 to ITAB8-XREF1.
 move ALTMP96 to ITAB8-XREF2.
 move ALTMP97 to ITAB8-XREF3.
 move ALTMP98 to ITAB8-ZZMOT_EMIS.
 move ALTMP99 to ITAB8-ZZRUT_TERC.
 move ALTMP100 to ITAB8-ZZ_AGENCIA.
 move ALTMP101 to ITAB8-LAUFD.
 move ALTMP102 to ITAB8-LAUFI.
 move ALTMP103 to ITAB8-IDENTIF_PAGO.
 move ALTMP104 to ITAB8-FECHA_ENVIO.
 move ALTMP105 to ITAB8-USUARIO_ENVIO.
 move ALTMP106 to ITAB8-IND_PAGO.
 move ALTMP107 to ITAB8-FECHA_PAGO.
 move ALTMP108 to ITAB8-IND_DEVUELTO.
 move ALTMP109 to ITAB8-FECHA_DEVUELTO.
 move ALTMP110 to ITAB8-IND_RECHAZO.
 move ALTMP111 to ITAB8-FECHA_RECHAZO.
 move ALTMP112 to ITAB8-BELNR_DEV.
 move ALTMP113 to ITAB8-GJAHR_DEV.
 move ALTMP114 to ITAB8-IND_CUSTODIA.
 move ALTMP115 to ITAB8-FECHA_CUSTODIA.
 move ALTMP116 to ITAB8-MOTIVO_RECHAZO.
 move ALTMP117 to ITAB8-IND_ENTREGADO.
 move ALTMP118 to ITAB8-FECHA_ENTREGADO.
 move ALTMP119 to ITAB8-IND_RESCATADO.
 move ALTMP120 to ITAB8-FECHA_RESCATADO.
 move ALTMP121 to ITAB8-IND_REDEPO.
 move ALTMP122 to ITAB8-FECHA_REDEPO.
 move ALTMP123 to ITAB8-GLOSA_REDEPO.
 move ALTMP124 to ITAB8-ZBVTY.
 move ALTMP125 to ITAB8-BUZEI.
 move ALTMP126 to ITAB8-ZBNKL.
 move ALTMP127 to ITAB8-ZBNKN.
 append ITAB8.
firstRun = 'N' .
ENDSELECT.
ENDIF.
IF ( ALOJF0 = 'N' ).
clear REGUH-LAUFD.
clear REGUH-LAUFI.
clear REGUH-IDENTIF_PAGO.
clear REGUH-FECHA_ENVIO.
clear REGUH-USUARIO_ENVIO.
clear REGUH-IND_PAGO.
clear REGUH-FECHA_PAGO.
clear REGUH-IND_DEVUELTO.
clear REGUH-FECHA_DEVUELTO.
clear REGUH-IND_RECHAZO.
clear REGUH-FECHA_RECHAZO.
clear REGUH-BELNR_DEV.
clear REGUH-GJAHR_DEV.
clear REGUH-IND_CUSTODIA.
clear REGUH-FECHA_CUSTODIA.
clear REGUH-MOTIVO_RECHAZO.
clear REGUH-IND_ENTREGADO.
clear REGUH-FECHA_ENTREGADO.
clear REGUH-IND_RESCATADO.
clear REGUH-FECHA_RESCATADO.
clear REGUH-IND_REDEPO.
clear REGUH-FECHA_REDEPO.
clear REGUH-GLOSA_REDEPO.
clear REGUH-ZBVTY.
clear REGUH-ZBNKL.
clear REGUH-ZBNKN.
clear REGUH-ZBUKR.
clear REGUH-LIFNR.
clear REGUH-VBLNR.
clear REGUH-ZALDT.
clear ALTMP101.
clear ALTMP102.
clear ALTMP103.
clear ALTMP104.
clear ALTMP105.
clear ALTMP106.
clear ALTMP107.
clear ALTMP108.
clear ALTMP109.
clear ALTMP110.
clear ALTMP111.
clear ALTMP112.
clear ALTMP113.
clear ALTMP114.
clear ALTMP115.
clear ALTMP116.
clear ALTMP117.
clear ALTMP118.
clear ALTMP119.
clear ALTMP120.
clear ALTMP121.
clear ALTMP122.
clear ALTMP123.
clear ALTMP124.
clear ALTMP126.
clear ALTMP127.
 move ALTMP70 to ITAB8-BUKRS.
 move ALTMP71 to ITAB8-BELNR.
 move ALTMP72 to ITAB8-GJAHR.
 move ALTMP73 to ITAB8-XBLNR.
 move ALTMP74 to ITAB8-STBLG.
 move ALTMP75 to ITAB8-BKTXT.
 move ALTMP76 to ITAB8-AWKEY.
 move ALTMP77 to ITAB8-XREF2_HD.
 move ALTMP78 to ITAB8-LIFNR.
 move ALTMP79 to ITAB8-STCD1.
 move ALTMP80 to ITAB8-NOMBRE.
 move ALTMP81 to ITAB8-BUDAT.
 move ALTMP82 to ITAB8-BLDAT.
 move ALTMP83 to ITAB8-CPUDT.
 move ALTMP84 to ITAB8-AUGBL.
 move ALTMP85 to ITAB8-AUGDT.
 move ALTMP86 to ITAB8-ZUONR.
 move ALTMP87 to ITAB8-BLART.
 move ALTMP88 to ITAB8-SHKZG.
 move ALTMP89 to ITAB8-DMBTR.
 move ALTMP90 to ITAB8-SGTXT.
 move ALTMP91 to ITAB8-HKONT.
 move ALTMP92 to ITAB8-ZFBDT.
 move ALTMP93 to ITAB8-ZLSCH.
 move ALTMP94 to ITAB8-HBKID.
 move ALTMP95 to ITAB8-XREF1.
 move ALTMP96 to ITAB8-XREF2.
 move ALTMP97 to ITAB8-XREF3.
 move ALTMP98 to ITAB8-ZZMOT_EMIS.
 move ALTMP99 to ITAB8-ZZRUT_TERC.
 move ALTMP100 to ITAB8-ZZ_AGENCIA.
 move ALTMP101 to ITAB8-LAUFD.
 move ALTMP102 to ITAB8-LAUFI.
 move ALTMP103 to ITAB8-IDENTIF_PAGO.
 move ALTMP104 to ITAB8-FECHA_ENVIO.
 move ALTMP105 to ITAB8-USUARIO_ENVIO.
 move ALTMP106 to ITAB8-IND_PAGO.
 move ALTMP107 to ITAB8-FECHA_PAGO.
 move ALTMP108 to ITAB8-IND_DEVUELTO.
 move ALTMP109 to ITAB8-FECHA_DEVUELTO.
 move ALTMP110 to ITAB8-IND_RECHAZO.
 move ALTMP111 to ITAB8-FECHA_RECHAZO.
 move ALTMP112 to ITAB8-BELNR_DEV.
 move ALTMP113 to ITAB8-GJAHR_DEV.
 move ALTMP114 to ITAB8-IND_CUSTODIA.
 move ALTMP115 to ITAB8-FECHA_CUSTODIA.
 move ALTMP116 to ITAB8-MOTIVO_RECHAZO.
 move ALTMP117 to ITAB8-IND_ENTREGADO.
 move ALTMP118 to ITAB8-FECHA_ENTREGADO.
 move ALTMP119 to ITAB8-IND_RESCATADO.
 move ALTMP120 to ITAB8-FECHA_RESCATADO.
 move ALTMP121 to ITAB8-IND_REDEPO.
 move ALTMP122 to ITAB8-FECHA_REDEPO.
 move ALTMP123 to ITAB8-GLOSA_REDEPO.
 move ALTMP124 to ITAB8-ZBVTY.
 move ALTMP125 to ITAB8-BUZEI.
 move ALTMP126 to ITAB8-ZBNKL.
 move ALTMP127 to ITAB8-ZBNKN.
 append ITAB8.
firstRun = 'N' .
ENDIF.
ENDLOOP.
ENDFORM.

FORM FORM9.
SORT ITAB8 BY
  BUKRS
  BELNR
  GJAHR
  XBLNR
  STBLG
  BKTXT
  AWKEY
  XREF2_HD
  LIFNR
  STCD1
  NOMBRE
  BUDAT
  BLDAT
  CPUDT
  AUGBL
  AUGDT
  ZUONR
  BLART
  SHKZG
  DMBTR
  SGTXT
  HKONT
  ZFBDT
  ZLSCH
  HBKID
  XREF1
  XREF2
  XREF3
  ZZMOT_EMIS
  ZZRUT_TERC
  ZZ_AGENCIA
  LAUFD
  LAUFI
  IDENTIF_PAGO
  FECHA_ENVIO
  USUARIO_ENVIO
  IND_PAGO
  FECHA_PAGO
  IND_DEVUELTO
  FECHA_DEVUELTO
  IND_RECHAZO
  FECHA_RECHAZO
  BELNR_DEV
  GJAHR_DEV
  IND_CUSTODIA
  FECHA_CUSTODIA
  MOTIVO_RECHAZO
  IND_ENTREGADO
  FECHA_ENTREGADO
  IND_RESCATADO
  FECHA_RESCATADO
  IND_REDEPO
  FECHA_REDEPO
  GLOSA_REDEPO
  ZBVTY
  BUZEI
  ZBNKL
  ZBNKN.
delete adjacent duplicates from ITAB8 comparing all fields.

ITAB7[] = ITAB8[].
ENDFORM.

FORM FORM8.
data: outfile(512), ldfile(50).
ldfile = 'Z_OBLIGA_ISA1_DIARIO'.
concatenate out_dir ldfile into outfile
  separated by '/'.
  IF DOWNLOAD = 'S'.
     DATA: error_message(700),mtext(800),iEOP(1).
     CALL FUNCTION P_SRVFM
          DESTINATION P_DEST
          KEEPING LOGICAL UNIT OF WORK
          EXPORTING
            EOS = last_batch
          IMPORTING
            EOP = iEOP
          TABLES
            E_TABLE = ITAB7
          EXCEPTIONS
            READ_ERROR = 1
            SYSTEM_FAILURE = 2
            MESSAGE error_message
            COMMUNICATION_FAILURE = 3
            MESSAGE error_message
            OTHERS = 4.

     IF sy-subrc ne 0.
        Case sy-subrc.
        when 1.
        CONCATENATE
        'Data Services read error. '
        'Check Data Services error log.'
        INTO mtext.
        MESSAGE  E240(S#) WITH mtext.
        when 2.
        CONCATENATE
'SAP System Failure while calling DS remote function: '
      error_message INTO mtext.
        MESSAGE  E240(S#) WITH mtext.
        when 3.
        CONCATENATE
'SAP System Failure while calling DS remote function: '
      error_message INTO mtext.
        MESSAGE  E240(S#) WITH mtext.
        when 4.
        MESSAGE  E240(S#) WITH
'Other SAP System Failure while calling DS remote function.'.
        endcase.
      ENDIF.
      IF iEOP = 'X'.
         PERFORM DISCONNECT_RFCDEST_FROM_PROGID.
         LEAVE PROGRAM.
       ENDIF.
  ELSE.
data  dlmtlen type i value '1'.
data xdlmtlen type i value '1'.
data:
  ht(1) type c,
  xht(1) type x,
  conv type ref to cl_abap_conv_in_ce.
xht = '7F'.
conv = cl_abap_conv_in_ce=>create(
  encoding = '1100'
  input = xht
).
call method conv->read(
  exporting n    = xdlmtlen
  importing data = ht
            len = dlmtlen
).
data return_code type i.
 perform write_delimited_file
           tables   ITAB7
           using    outfile
                    append_flag
                    ht
                    dlmtlen
                    download
           changing return_code.

  case return_code.
    when 1.
      IF EXECMODE = 'D'.
        WRITE: /5 'No line selected'.
      ELSE.
        MESSAGE E047(S#).
      ENDIF.
    when 2.
      IF EXECMODE = 'D'.
        WRITE: /5 'Open File Error -- ', 25 OUTFILE.
      ELSE.
        MESSAGE  E084(E0) WITH OUTFILE.
      ENDIF.
    when 3.
      IF EXECMODE = 'D'.
        WRITE: /5 'Data exceed length limit (8192) '.
      ELSE.
        MESSAGE  E240(S#) WITH
             'Data exceed length limit (8192) '.
      ENDIF.
    when 4.
      IF EXECMODE = 'D'.
        WRITE: /5 'Call function WS_DOWNLOAD error'.
      ELSE.
        MESSAGE  E240(S#) WITH
             'Call function WS_DOWNLOAD error'.
      ENDIF.
  endcase.
 ENDIF.
ENDFORM.

FORM SUBSTRING USING SRC BEG LEN CHANGING RET.

DATA: VA1 TYPE I.
DATA: VA2 TYPE I.
DATA: VA3 TYPE I.

VA3 = STRLEN( SRC ).

IF  BEG = 0.   VA1 = 0.
ELSE.
  IF  BEG < 0.
    VA1 = VA3 + BEG.
    IF  VA1 < 0.   VA1 = 0.
    ENDIF.
  ELSE.          VA1 = BEG - 1.
  ENDIF.
ENDIF.

IF  LEN < 0.   VA2 = 0.
ELSE.          VA2 = VA3 - VA1.
ENDIF.

IF  VA2 > LEN. VA2 = LEN.
ENDIF.

IF  VA2 < 1.   MOVE ''           TO RET.
ELSE.          MOVE SRC+VA1(VA2) TO RET.
ENDIF.

ENDFORM.

form write_delimited_file
           tables   datatab
           using    file
                    append
                    delimit
                    dlength
                    dwnload
          changing rc.

  data: type1,
        appd(1),
        temp(32),
        time1(8),
        date1(10),
        output(8192),
        rcount type i,
        offset type i,
        tablen type i,
        maxlen type i value '8192'.

  data: begin of clientab occurs 0,
             output(8192),
          end of clientab.

  field-symbols: <f>.
  field-symbols <delim1>.
  data delim2(16).
  data l_filename type string.

  appd = append.
  if appd is not initial.
     appd = 'X'.
  endif.
  move file to l_filename.
  describe table datatab lines tablen.


  if dwnload = 'Y'.
     clear clientab. refresh clientab.
     rcount = 0.
  else.
     if appd = space.
   open dataset file for output in text mode ENCODING UTF-8.
     else.
    open dataset file for appending in text mode ENCODING UTF-8.

     endif.
     if sy-subrc <> 0.
         rc = 2. exit.
     endif.
  endif.

  loop at datatab.
    clear: tablen, offset, output.
    do.
      assign component sy-index of
         structure datatab to <f>.
      if sy-subrc <> 0. exit. endif.
      if sy-index > 1.
         assign delimit(dlength) TO <delim1> CASTING TYPE C.
         delim2 = <delim1>.
         write delim2(dlength) to output+offset(dlength).
         add dlength to offset.
      endif.

      describe field <f> type type1.

      if type1 = 'I' or type1 = 'N'.
          type1 = 'P'.
      endif.

      case type1.
        when 'D'.
          if <f> = '00000000'.
             <f> = ' '.
          else.
             move <f> to time1.
             assign time1 to <f>.
          endif.
        when 'F'.
          if <f> = '0.0'.
            temp = '0.0'.
          else.
             write <f> to temp exponent 0.
          endif.
          condense temp no-gaps.
          translate temp using ',.'.
          assign temp to <f>.
        when 'P'.
          if <f> < 0.
             write '-' to output+offset(1).
             add 1 to offset.
             <f> = <f> * ( -1 ).
          endif.
          move <f> to temp.
          condense temp no-gaps.
          translate temp using ',.'.
          assign temp to <f>.
      endcase.

      sy-fdpos = strlen( <f> ).

      tablen = offset + sy-fdpos.
      if tablen > maxlen.
         rc = 3. exit.
      endif.
      write <f> to output+offset(sy-fdpos).
      add sy-fdpos to offset.
    enddo.

    if dwnload = 'Y'.
       clientab-output = output.
       append clientab.
       rcount = rcount + 1.
       if rcount >= 50.
          SY-BATCH = SPACE.
          CALL FUNCTION 'GUI_DOWNLOAD'
            EXPORTING
              FILENAME = l_filename
              FILETYPE = 'ASC'
              CODEPAGE = '4110'
              APPEND   = appd
              WRITE_FIELD_SEPARATOR = 'X'
*            IMPORTING
*              FILELENGTH =
            TABLES
              DATA_TAB = clientab
            EXCEPTIONS
              OTHERS = 1.
          if sy-subrc <> 0.
             rc = 4.
          endif.
          clear clientab. refresh clientab.
          rcount = 0. appd = 'A'.
       endif.
    else.
       transfer output to file.
    endif.
  endloop.

  if dwnload = 'Y'.
       SY-BATCH = SPACE.
       CALL FUNCTION 'GUI_DOWNLOAD'
         EXPORTING
           FILENAME = l_filename
           FILETYPE = 'ASC'
              CODEPAGE = '4110'
           APPEND   = appd
           WRITE_FIELD_SEPARATOR = 'X'
*         IMPORTING
*           FILELENGTH =
         TABLES
           DATA_TAB = clientab
         EXCEPTIONS
           OTHERS = 1.
          if sy-subrc <> 0.
             rc = 4.
          endif.
  else.
       close dataset file.
  endif.
endform.

FORM CONNECT_RFCDEST_TO_PROGID.
 INCLUDE rfctypes.

 DATA: len     type i,
       R3NAME(4),
       SYSTNR(2),
       uid     LIKE SYS_UID,
       options LIKE RFCOPT,
       isunicode  TYPE n.

 DATA: NTOTAL     LIKE GWY_STRUCT-NOREG,
       GWY_GWHOST LIKE GWY_STRUCT-GWHOST,
       GWY_GWSERV LIKE GWY_STRUCT-GWSERV,
       GWY_TPNAME LIKE GWY_SYSTEM-TPNAME.

 TABLES: RFCSI.

* Check program ID
 IF P_PROGID = SPACE.
    RAISE INVALID_PROGRAM_ID.
 ENDIF.

* determine if the RFC destination authority
  CALL FUNCTION 'RFC_READ_TCPIP_DESTINATION'
       EXPORTING destination = P_DEST
                 authority_check = 'X'
  IMPORTING rfcunicode = isunicode.

* Use current gateway if no info exits
 IF P_GWHOST = SPACE OR P_GWSERV = SPACE.
  CALL FUNCTION 'RFC_SYSTEM_INFO'
      IMPORTING
          RFCSI_EXPORT = RFCSI.

  len = strlen( rfcsi-rfcdest ) - 2.
  systnr = rfcsi-rfcdest+len.
  len = len - 1 - 3.
  r3name = rfcsi-rfcdest+len(3).
  len = len - 1.
  options-rfcgwhost = rfcsi-rfcdest(len).
  CONCATENATE 'sapgw' SYSTNR INTO options-rfcgwserv.
 ELSE.
   options-rfcgwhost = P_GWHOST.
   options-rfcgwserv = P_GWSERV.
 ENDIF.

* Parameters for GWY function call
  GWY_GWHOST = OPTIONS-RFCGWHOST.
  GWY_GWSERV = OPTIONS-RFCGWSERV.
  GWY_TPNAME = P_PROGID.

* Check gateway and server program registered
  CALL FUNCTION 'GWY_GET_NO_REG_PROGRAMS'
     EXPORTING
        GWHOST      = GWY_GWHOST
        GWSERV      = GWY_GWSERV
        TPNAME      = GWY_TPNAME
     IMPORTING
        NOREG_TOTAL = NTOTAL
     EXCEPTIONS
        OTHERS      = 1.

  IF sy-subrc NE 0.
     raise CONNECT_TO_GATEWAY_FAILED.
  ENDIF.

  IF NTOTAL = 0.
     raise SERVER_NOT_REGISTERED.
  ENDIF.

  IF NTOTAL GT 1.
     raise DUPLICATE_REG_PROGRAMS.
  ENDIF.

* build new connection to a registered server
  options-rfcexec   = gwy_tpname.
  options-rfcgwhost = gwy_gwhost.
  options-rfcgwserv = gwy_gwserv.
  options-rfchost   = '%%RFCSERVER%%'.
  IF P_SNC_ON = 'X'.
    options-rfcsnc  = 'X'.
  ENDIF.

  CALL 'RFCControl' ID 'CODE' FIELD 'O'
                    ID 'DESTINATION' FIELD P_DEST
                    ID 'TYPE' FIELD rfctype_external_tcp
                    ID 'OPTIONS' FIELD options.

  IF sy-subrc NE 0.
     RAISE CONNECT_TO_REG_SERVER_FAILED.
   ENDIF.

* and set exclusive mode to keep server owned
  CALL FUNCTION 'SYSTEM_SET_REG_SERVER_PROPERTY'
      EXPORTING  destination = P_DEST
                 exclusiv    = 'Y'
      EXCEPTIONS connect_to_reg_server_failed = 1
                 exclusiv_not_supported       = 2.

  IF SY-SUBRC NE 0.
     CASE SY-SUBRC.
          WHEN 1.
              RAISE CONNECT_TO_REG_SERVER_FAILED.
          WHEN 2.
              RAISE EXCLUSIV_NOT_SUPPORTED.
     ENDCASE.
  ENDIF.

ENDFORM.

FORM DISCONNECT_RFCDEST_FROM_PROGID.
* set exclusive mode to E to end the session
  CALL FUNCTION 'SYSTEM_SET_REG_SERVER_PROPERTY'
     EXPORTING
         destination = P_DEST
         exclusiv    = 'E'
     EXCEPTIONS
         connect_to_reg_server_failed = 1
         exclusiv_not_supported       = 2.
ENDFORM.
