FUNCTION ZFI_DOCUMENT_RELATION_BROWSER.
*"--------------------------------------------------------------------
*"*"Interfase local
*"  IMPORTING
*"     REFERENCE(I_OBJTYPE) TYPE  BORIDENT-OBJTYPE DEFAULT 'BKPF'
*"     REFERENCE(I_BUKRS) TYPE  BUKRS
*"     REFERENCE(I_BELNR) TYPE  BELNR_D
*"     REFERENCE(I_GJAHR) TYPE  GJAHR
*"--------------------------------------------------------------------

  DATA: BEGIN OF KEYDATA,
          BUKRS LIKE BKPF-BUKRS,
          BELNR LIKE BKPF-BELNR,
          GJAHR LIKE BKPF-GJAHR,
        END OF KEYDATA.
  DATA: L_BORIDENT LIKE BORIDENT.

  L_BORIDENT-OBJTYPE = I_OBJTYPE.
* accept only pattern BKPF/BKPFF
  if L_BORIDENT-OBJTYPE <> 'BKPF'
  and L_BORIDENT-OBJTYPE <> 'BKPFF'.
    L_BORIDENT-OBJTYPE = 'BKPF'.
  endif.
  KEYDATA-BUKRS = I_BUKRS.
  KEYDATA-BELNR = I_BELNR.
  KEYDATA-GJAHR = I_GJAHR.
  L_BORIDENT-OBJKEY = KEYDATA.

  GET PARAMETER ID 'FO2' FIELD RFOPT2.
  IF RFOPT2-XDRB = 'X'.
    CALL FUNCTION 'DRB_SHOW' STARTING NEW TASK 'CBCB'
      EXPORTING
        I_BORIDENT = L_BORIDENT.
  ELSE.
    CALL FUNCTION 'ASH_HIERARCHY_SHOW'
      EXPORTING
        I_BORIDENT = L_BORIDENT.
  ENDIF.

ENDFUNCTION.
