FUNCTION F4HELP_ZZEMIS .
*"----------------------------------------------------------------------
*"*"Interfase local
*"  TABLES
*"      SHLP_TAB TYPE  SHLP_DESCR_TAB_T
*"      RECORD_TAB STRUCTURE  SEAHLPRES
*"  CHANGING
*"     REFERENCE(SHLP) TYPE  SHLP_DESCR_T
*"     REFERENCE(CALLCONTROL) LIKE  DDSHF4CTRL STRUCTURE  DDSHF4CTRL
*"----------------------------------------------------------------------

  DATA: L_SELOPT   LIKE DDSHSELOPT,
        LT_KAPPL_TABLE TYPE ZMOT_EMIS OCCURS 0 WITH HEADER LINE,
        LT_KSCHL_TABLE TYPE ZMOT_EMIS OCCURS 0 WITH HEADER LINE,
        L_KAPPL        TYPE ZMOT_EMIS,
        WA_KSCHL       TYPE ZMOT_EMIS-BUKRS,
        L_KSCHL LIKE ZMOT_EMIS-BUKRS,
        FLAG_BASIS.
  DATA: BEGIN OF L_RECORD OCCURS 0,
       BUKRS TYPE BUKRS,
       ZZMOT_EMIS TYPE ZMOT_EMIS-ZZMOT_EMIS,
       ZZDESCR TYPE  ZMOT_EMIS-ZZDESCR,
  END OF L_RECORD.

  DATA AAA TYPE DDSHIFACE.


  CHECK CALLCONTROL-STEP EQ 'SELECT'.

* clear tablename for jump to Customizing
  CLEAR CALLCONTROL-CUSTTAB.

  READ TABLE SHLP-INTERFACE INTO AAA WITH KEY SHLPFIELD = 'BUKRS'.
  IF SY-SUBRC <> 0.
    GET PARAMETER ID 'BUK' FIELD L_KSCHL.
  ENDIF.

  IF L_KSCHL NE SPACE.
    SELECT * FROM  ZMOT_EMIS INTO TABLE LT_KAPPL_TABLE
             WHERE BUKRS EQ  L_KSCHL.                           "#EC "#EC CI_NOWHERE
  ELSE.
    SELECT * FROM  ZMOT_EMIS INTO TABLE LT_KAPPL_TABLE.         "#EC "#EC CI_NOWHERE
  ENDIF.

  LOOP AT LT_KAPPL_TABLE INTO L_KAPPL.
    CLEAR L_RECORD.
    L_RECORD-ZZMOT_EMIS = L_KAPPL-ZZMOT_EMIS.
    IF FLAG_BASIS NE ON.
      SELECT SINGLE ZZDESCR BUKRS FROM ZMOT_EMIS INTO (L_RECORD-ZZDESCR, L_RECORD-BUKRS)
                                 WHERE ZZMOT_EMIS EQ L_RECORD-ZZMOT_EMIS
                                 AND   BUKRS     EQ L_RECORD-BUKRS.
      IF SY-SUBRC NE 0.
        SELECT SINGLE ZZDESCR BUKRS FROM ZMOT_EMIS INTO (L_RECORD-ZZDESCR, L_RECORD-BUKRS)
                                   WHERE ZZMOT_EMIS EQ L_RECORD-ZZMOT_EMIS.

      ENDIF.

    ENDIF.
    APPEND L_RECORD.
  ENDLOOP.

* move to the table with help-values
  CALL FUNCTION 'F4UT_RESULTS_MAP'
    TABLES
      SHLP_TAB          = SHLP_TAB
      RECORD_TAB        = RECORD_TAB
      SOURCE_TAB        = L_RECORD
    CHANGING
      SHLP              = SHLP
      CALLCONTROL       = CALLCONTROL
    EXCEPTIONS
      ILLEGAL_STRUCTURE = 1
      OTHERS            = 2.
  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.
  CALLCONTROL-STEP = 'DISP'.


ENDFUNCTION.
