FUNCTION F4HELP_ZZPRESTAC .
*"----------------------------------------------------------------------
*"*"Interfase local
*"  TABLES
*"      SHLP_TAB TYPE  SHLP_DESCR_TAB_T
*"      RECORD_TAB STRUCTURE  SEAHLPRES
*"  CHANGING
*"     REFERENCE(SHLP) TYPE  SHLP_DESCR_T
*"     REFERENCE(CALLCONTROL) LIKE  DDSHF4CTRL STRUCTURE  DDSHF4CTRL
*"----------------------------------------------------------------------

  DATA: L_SELOPT   LIKE DDSHSELOPT,
        LT_KAPPL_TABLE TYPE ZPRESTACION OCCURS 0 WITH HEADER LINE,
        LT_KSCHL_TABLE TYPE ZPRESTACION OCCURS 0 WITH HEADER LINE,
        L_KAPPL        TYPE ZPRESTACION,
        WA_KSCHL       TYPE ZPRESTACION-BUKRS,
        L_KSCHL LIKE ZPRESTACION-BUKRS,
        FLAG_BASIS.
  DATA: BEGIN OF L_RECORD OCCURS 0,
       BUKRS TYPE BUKRS,
       ZZPRESTAC TYPE ZPRESTACION-ZZPRESTAC,
       ZZDESCR TYPE  ZPRESTACION-ZZDESCR,
  END OF L_RECORD.

  CHECK CALLCONTROL-STEP EQ 'SELECT'.

* clear tablename for jump to Customizing
  CLEAR CALLCONTROL-CUSTTAB.


  GET PARAMETER ID 'BUK' FIELD L_KSCHL.


  IF L_KSCHL NE SPACE.
    SELECT * FROM  ZPRESTACION INTO TABLE LT_KAPPL_TABLE
             WHERE BUKRS EQ  L_KSCHL.
  ELSE.
    SELECT * FROM  ZPRESTACION INTO TABLE LT_KAPPL_TABLE.
  ENDIF.

  LOOP AT LT_KAPPL_TABLE INTO L_KAPPL.
    CLEAR L_RECORD.
    L_RECORD-ZZPRESTAC = L_KAPPL-ZZPRESTAC.
    IF FLAG_BASIS NE ON.
      SELECT SINGLE ZZDESCR BUKRS FROM ZPRESTACION INTO (L_RECORD-ZZDESCR, L_RECORD-BUKRS)
                                 WHERE ZZPRESTAC EQ L_RECORD-ZZPRESTAC
                                 AND   BUKRS     EQ L_RECORD-BUKRS.
      IF SY-SUBRC NE 0.
        SELECT SINGLE ZZDESCR BUKRS FROM ZPRESTACION INTO (L_RECORD-ZZDESCR, L_RECORD-BUKRS)
                                   WHERE ZZPRESTAC EQ L_RECORD-ZZPRESTAC.
*                                 AND   BUKRS     EQ L_RECORD-BUKRS.

      ENDIF.

    ENDIF.
    APPEND L_RECORD.
  ENDLOOP.

* move to the table with help-values
  CALL FUNCTION 'F4UT_RESULTS_MAP'
    TABLES
      SHLP_TAB          = SHLP_TAB
      RECORD_TAB        = RECORD_TAB
      SOURCE_TAB        = L_RECORD
    CHANGING
      SHLP              = SHLP
      CALLCONTROL       = CALLCONTROL
    EXCEPTIONS
      ILLEGAL_STRUCTURE = 1
      OTHERS            = 2.
  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.
  CALLCONTROL-STEP = 'DISP'.


ENDFUNCTION.
