*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZBANCOSSBIFTOP.                   " Global Data
  INCLUDE LZBANCOSSBIFUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZBANCOSSBIFF00                         . " subprograms
  INCLUDE LZBANCOSSBIFI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZBANCOSSBIFF...                   " Subprograms
* INCLUDE LZBANCOSSBIFO...                   " PBO-Modules
* INCLUDE LZBANCOSSBIFI...                   " PAI-Modules
