*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZBMNC_LISTABCABTOP.               " Global Data
  INCLUDE LZBMNC_LISTABCABUXX.               " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZBMNC_LISTABCABF00                     . " subprograms
  INCLUDE LZBMNC_LISTABCABI00                     . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZBMNC_LISTABCABF...               " Subprograms
* INCLUDE LZBMNC_LISTABCABO...               " PBO-Modules
* INCLUDE LZBMNC_LISTABCABI...               " PAI-Modules

INCLUDE LZBMNC_LISTABCABF01.
