*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZCEBE_PRESCRIPTOP.                " Global Data
  INCLUDE LZCEBE_PRESCRIPUXX.                " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZCEBE_PRESCRIPF00                      . " subprograms
  INCLUDE LZCEBE_PRESCRIPI00                      . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZCEBE_PRESCRIPF...                " Subprograms
* INCLUDE LZCEBE_PRESCRIPO...                " PBO-Modules
* INCLUDE LZCEBE_PRESCRIPI...                " PAI-Modules
