*&---------------------------------------------------------------------*
*&  Include           ZCL_CREA_PEDIDOS_TOP
*&---------------------------------------------------------------------*
TABLES ZCABPEDEXT.
TABLES ZDETPEDEXT.

TYPE-POOLS: SLIS.
TYPES: BEGIN OF FACTSAPTRASPASO,
        SAPNUMFACTURA      TYPE C LENGTH 10,
        POS_FAC            TYPE REFPS,
        EST_PROC           TYPE C LENGTH 2,
        DES_EST            TYPE C LENGTH 15,
        SAPCLASEVENTA      TYPE C LENGTH 2,
        SAPINDELEC         TYPE C LENGTH 2,
        SAPORGVTA          TYPE C LENGTH 4,
        SAPCANALDIS        TYPE C LENGTH 2,
        SAPSECTORFACT      TYPE C LENGTH 2,
        SAPOFIVTA          TYPE C LENGTH 4,
        SAPGRUPOVEND       TYPE C LENGTH 30,
        SAPRUTFACTURA      TYPE C LENGTH 16,
        SAPNOMBREFACTURA   TYPE C LENGTH 40,
        SAPRUTPAGADOR      TYPE C LENGTH 16,
        SAPGIROCLI         TYPE C LENGTH 124,
        SAPDIRCLI          TYPE C LENGTH 60,
        SAPCOMUNA          TYPE C LENGTH 40,
        SAPCIUDAD          TYPE C LENGTH 40,
        SAPNUMFOLIOCTR     TYPE C LENGTH 13,
        SAPFECHACTR        TYPE C LENGTH 10,
        SAPNUMEVENTO       TYPE C LENGTH 18,
        SAPCONPAGO         TYPE C LENGTH 4,
        SAPINDTRASPASO     TYPE C LENGTH 1,
        SAPTARJCUENTA      TYPE C LENGTH 20,
        SAPCODBANCO        TYPE C LENGTH 5,
        SAPESTCTR          TYPE C LENGTH 1,
        SAPTIPOTARJ        TYPE C LENGTH 12,
        SAPMONEDA          TYPE C LENGTH 16,
        SAPPLANCTR         TYPE C LENGTH 10,
        SAPVIAPAGO         TYPE C LENGTH 1,
        SAPTIPOCAMBIO      TYPE C LENGTH 16,
        SAPCENTRO          TYPE C LENGTH 4,
        SAPNUMMANDATO      TYPE C LENGTH 25,
        SAPNUMENDOSO       TYPE C LENGTH 25,
        SAPAFEEXE          TYPE C LENGTH 2,
        SAPTIPOCOPAGO      TYPE C LENGTH 3,
        SAPPERIODICIDAD    TYPE C LENGTH 3,
        SAPCODPLAN         TYPE C LENGTH 10,
        SAPTOTALFACT       TYPE C LENGTH 16,
        SAPINDBLOQUEO      TYPE C LENGTH 1,
        SAPMONTOUF         TYPE C LENGTH 16,
        SAPRUTBENEFICIARIO TYPE C LENGTH 16,
        SAPCODPRODUCTO     TYPE C LENGTH 18,
        SAPCTDAD           TYPE C LENGTH 16,
        SAPVALLISTA        TYPE C LENGTH 16,
        SAPVALADIC         TYPE C LENGTH 16,
        SAPDCTOCONV        TYPE C LENGTH 16,
        SAPDCTOPERM        TYPE C LENGTH 16,
        SAPDCTOPROM        TYPE C LENGTH 16,
        SAPDCTOTEMP        TYPE C LENGTH 16,
        SAPINGBEMHELP      TYPE C LENGTH 16,
        SAPINGOTROS        TYPE C LENGTH 16,
        SAPRANGOETA        TYPE C LENGTH 2,
        SAPSECTORAFI       TYPE C LENGTH 2,
        SAPFECHAFACT       TYPE C LENGTH 10,
        SAPFECHACORE       TYPE C LENGTH 10,
        SAPFECHAVENC       TYPE C LENGTH 10,
        SAPGLOSADOC        TYPE C LENGTH 1000,
      END OF FACTSAPTRASPASO.

DATA WA_TE      TYPE FACTSAPTRASPASO.

DATA TI_PEDIDO  TYPE STANDARD TABLE OF FACTSAPTRASPASO.

DATA: BEGIN OF TI_FILE OCCURS 0,
       LINE TYPE STRING,
      END OF  TI_FILE.

DATA LS_PEDIDO   LIKE LINE OF TI_PEDIDO.
DATA DBCNT_NDOC  TYPE SYDBCNT.
DATA DBCNT_REG   TYPE SYDBCNT.
DATA POS         TYPE I.
DATA STR_DBCNT   TYPE STRING.
DATA TEXTO1      TYPE STRING.
DATA TEXTO2      TYPE STRING.
DATA EXC_REF     TYPE REF TO CX_SY_NATIVE_SQL_ERROR.
DATA ERROR_TEXT  TYPE STRING.
DATA PCONNAME    TYPE DBCON_NAME VALUE 'SAPCSC'.
DATA DBTYPE      TYPE DBCON_DBMS.
DATA INDTRAS     TYPE C.
DATA FILE        TYPE STRING.
DATA GT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV WITH HEADER LINE.
DATA GS_LAYOUT   TYPE SLIS_LAYOUT_ALV.
DATA LV_SUBRC    LIKE SY-SUBRC.
DATA LT_IT_TAB   TYPE FILETABLE.
DATA P_PA_FILE   TYPE FILE_TABLE.
