PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCONFCHK CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCONFCHK-ZBUKR .
    FIELD ZCONFCHK-HBKID .
    FIELD ZCONFCHK-HKTID .
    FIELD ZCONFCHK-FORMULARIO .
    FIELD ZCONFCHK-CANTCHK .
    FIELD ZCONFCHK-FMTO_NUEVO .
    FIELD ZCONFCHK-SMARTFORM .
    FIELD ZCONFCHK-LASER .
    FIELD ZCONFCHK-FMTOANNO .
    FIELD ZCONFCHK-CANTLIN .
    FIELD ZCONFCHK-SMARTFORM_IND .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCONFCHK-ZBUKR .
    FIELD ZCONFCHK-HBKID .
    FIELD ZCONFCHK-HKTID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
