*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZCONFCHKTOP.                      " Global Data
  INCLUDE LZCONFCHKUXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZCONFCHKF00                            . " subprograms
  INCLUDE LZCONFCHKI00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZCONFCHKF...                      " Subprograms
* INCLUDE LZCONFCHKO...                      " PBO-Modules
* INCLUDE LZCONFCHKI...                      " PAI-Modules
