*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZCTARECHAZOBCOTOP.                " Global Data
  INCLUDE LZCTARECHAZOBCOUXX.                " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZCTARECHAZOBCOF00                      . " subprograms
  INCLUDE LZCTARECHAZOBCOI00                      . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZCTARECHAZOBCOF...                " Subprograms
* INCLUDE LZCTARECHAZOBCOO...                " PBO-Modules
* INCLUDE LZCTARECHAZOBCOI...                " PAI-Modules
