*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZCTA_PRESCRIPTOP.                 " Global Data
  INCLUDE LZCTA_PRESCRIPUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZCTA_PRESCRIPF00                       . " subprograms
  INCLUDE LZCTA_PRESCRIPI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZCTA_PRESCRIPF...                 " Subprograms
* INCLUDE LZCTA_PRESCRIPO...                 " PBO-Modules
* INCLUDE LZCTA_PRESCRIPI...                 " PAI-Modules
