PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZCTARECHAZOBCO CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZCTARECHAZOBCO-BUKRS .
    FIELD ZCTARECHAZOBCO-HBKID_DEST .
    FIELD ZCTARECHAZOBCO-RZAWE .
    FIELD ZCTARECHAZOBCO-HKONT_ORIG .
    FIELD ZCTARECHAZOBCO-RZAWE_D .
    FIELD ZCTARECHAZOBCO-HKONT_DEST .
    FIELD ZCTARECHAZOBCO-HKTID_DEST .
    FIELD ZCTARECHAZOBCO-SGTXT .
    FIELD ZCTARECHAZOBCO-CTACTE_BCO .
    FIELD ZCTARECHAZOBCO-HKONT_DEP .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZCTARECHAZOBCO-BUKRS .
    FIELD ZCTARECHAZOBCO-HBKID_DEST .
    FIELD ZCTARECHAZOBCO-RZAWE .
    FIELD ZCTARECHAZOBCO-HKONT_ORIG .
    FIELD ZCTARECHAZOBCO-RZAWE_D .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
