*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZDATSOCELEC_BANTOP.               " Global Data
  INCLUDE LZDATSOCELEC_BANUXX.               " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZDATSOCELEC_BANF00                     . " subprograms
  INCLUDE LZDATSOCELEC_BANI00                     . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZDATSOCELEC_BANF...               " Subprograms
* INCLUDE LZDATSOCELEC_BANO...               " PBO-Modules
* INCLUDE LZDATSOCELEC_BANI...               " PAI-Modules
