PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZDIRECCGUIA-BUKRS .
    FIELD ZDIRECCGUIA-KOSTL .
    FIELD ZDIRECCGUIA-CORREL .
    FIELD ZDIRECCGUIA-STRAS .
    FIELD ZDIRECCGUIA-ORT01 .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZDIRECCGUIA-BUKRS .
    FIELD ZDIRECCGUIA-KOSTL .
    FIELD ZDIRECCGUIA-CORREL .
  module detail_pai.
 endchain.
