*&---------------------------------------------------------------------*
*&  Include           ZDTE_PUP_TOP
*&---------------------------------------------------------------------*
TABLES NAST.
DATA ALIGN             TYPE I.
DATA ASSIGNED_URL(255) TYPE C.
DATA CONTAINER         TYPE REF TO CL_GUI_CUSTOM_CONTAINER.
DATA DATA_TABLE        TYPE C OCCURS 0.
DATA DOCUMENT_ID(255)  TYPE C." VALUE 'HTMLCNTL_TESTEVNT_HOME'.
DATA DOCUMENT_TEXTPOOL TYPE SY-REPID.
DATA DOCUMENT_URL(255) TYPE C.
DATA FRAME(255)        TYPE C.
DATA HTML_VIEWER       TYPE REF TO CL_GUI_HTML_VIEWER.
DATA INIT              TYPE C.
DATA MERGE_TABLE       TYPE SWWW_T_MERGE_TABLE.
DATA OK_CODE           TYPE SY-UCOMM.
DATA OBJECT_ID(255)    TYPE C. "VALUE 'HTMLCNTL_TESTHTM2_SAPLOGO'.
DATA OBJECT_URL(255)   TYPE C. "VALUE 'SAPLOGO.GIF'.
DATA TYPE(4)           TYPE C VALUE 'text'.
DATA SAVE_OK           TYPE SY-UCOMM.
DATA SUBTYPE(4)        TYPE C VALUE 'html'.
DATA SIZE              TYPE I.
DATA URL(255)          TYPE C." VALUE 'HTTP://WWW.SAP-AG.DE'.
