*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZDTE_FTPTOP.                      " Global Data
  INCLUDE LZDTE_FTPUXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZDTE_FTPF00                            . " subprograms
  INCLUDE LZDTE_FTPI00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZDTE_FTPF...                      " Subprograms
* INCLUDE LZDTE_FTPO...                      " PBO-Modules
* INCLUDE LZDTE_FTPI...                      " PAI-Modules
