*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZDTE_DOC_GRTOP.                   " Global Data
  INCLUDE LZDTE_DOC_GRUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZDTE_DOC_GRF00                         . " subprograms
  INCLUDE LZDTE_DOC_GRI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZDTE_DOC_GRF...                   " Subprograms
* INCLUDE LZDTE_DOC_GRO...                   " PBO-Modules
* INCLUDE LZDTE_DOC_GRI...                   " PAI-Modules

INCLUDE LZDTE_DOC_GRF01.
