*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZDTE_VAL_GRPTOP.                  " Global Data
  INCLUDE LZDTE_VAL_GRPUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZDTE_VAL_GRPF00                        . " subprograms
  INCLUDE LZDTE_VAL_GRPI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZDTE_VAL_GRPF...                  " Subprograms
* INCLUDE LZDTE_VAL_GRPO...                  " PBO-Modules
* INCLUDE LZDTE_VAL_GRPI...                  " PAI-Modules
