PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZDTE_DOC_REC CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZDTE_DOC_REC-RUTEMISOR .
    FIELD ZDTE_DOC_REC-TIPODTE .
    FIELD ZDTE_DOC_REC-FOLIO .
    FIELD ZDTE_DOC_REC-RZNSOC .
    FIELD ZDTE_DOC_REC-RUTRECEP .
    FIELD ZDTE_DOC_REC-GIRORECEP .
    FIELD ZDTE_DOC_REC-DIRRECEP .
    FIELD ZDTE_DOC_REC-RZNRECEP .
    FIELD ZDTE_DOC_REC-FCHEMIS .
    FIELD ZDTE_DOC_REC-IVA .
    FIELD ZDTE_DOC_REC-MNTEXE .
    FIELD ZDTE_DOC_REC-MNTNETO .
    FIELD ZDTE_DOC_REC-MNTTOTAL .
    FIELD ZDTE_DOC_REC-TASAIVA .
    FIELD ZDTE_DOC_REC-FCHREC .
    FIELD ZDTE_DOC_REC-HORREC .
    FIELD ZDTE_DOC_REC-WAERS .
    FIELD ZDTE_DOC_REC-ESTADO .
    FIELD ZDTE_DOC_REC-MOTIVO_REC .
    FIELD ZDTE_DOC_REC-UNAME .
    FIELD ZDTE_DOC_REC-BELNR .
    FIELD ZDTE_DOC_REC-GJAHR .
    FIELD ZDTE_DOC_REC-TCODE .
    FIELD ZDTE_DOC_REC-ERDAT .
    FIELD ZDTE_DOC_REC-ERZET .
    FIELD ZDTE_DOC_REC-ERNAM .
    FIELD ZDTE_DOC_REC-MESSAGE .
    FIELD ZDTE_DOC_REC-URL .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZDTE_DOC_REC-RUTEMISOR .
    FIELD ZDTE_DOC_REC-TIPODTE .
    FIELD ZDTE_DOC_REC-FOLIO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
