*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZDTE_DOC_RECTOP.                  " Global Data
  INCLUDE LZDTE_DOC_RECUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZDTE_DOC_RECF00                        . " subprograms
  INCLUDE LZDTE_DOC_RECI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZDTE_DOC_RECF...                  " Subprograms
* INCLUDE LZDTE_DOC_RECO...                  " PBO-Modules
* INCLUDE LZDTE_DOC_RECI...                  " PAI-Modules
