PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZESTADOSBANCO-BANCO .
    FIELD ZESTADOSBANCO-CODBAN .
    FIELD ZESTADOSBANCO-GLOBAN .
    FIELD ZESTADOSBANCO-CODINT .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZESTADOSBANCO-BANCO .
    FIELD ZESTADOSBANCO-CODBAN .
  module detail_pai.
 endchain.
