*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVFI_OB52.......................................*
FORM GET_DATA_ZVFI_OB52.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
* BEGIN. 07-07-2026 - ATC - ATC-03
* OLD CODE
*  SELECT * FROM ZFI_OB52 WHERE
*(VIM_WHERETAB) .
*
* NEW CODE
  SELECT *
 FROM ZFI_OB52 WHERE
(VIM_WHERETAB)  ORDER BY PRIMARY KEY.

* END. 07-07-2026 - ATC - ATC-03
    CLEAR ZVFI_OB52 .
ZVFI_OB52-MANDT =
ZFI_OB52-MANDT .
ZVFI_OB52-BUKRS =
ZFI_OB52-BUKRS .
ZVFI_OB52-UNAME =
ZFI_OB52-UNAME .
ZVFI_OB52-DATUM =
ZFI_OB52-DATUM .
ZVFI_OB52-UZEIT =
ZFI_OB52-UZEIT .
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*    SELECT SINGLE * FROM T010O WHERE
*OPVAR = ZFI_OB52-BUKRS .
*
* NEW CODE
    SELECT *
    UP TO 1 ROWS  FROM T010O WHERE
OPVAR = ZFI_OB52-BUKRS  ORDER BY PRIMARY KEY.

    ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
    IF SY-SUBRC EQ 0.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*      SELECT SINGLE * FROM T010P WHERE
*OPVAR = T010O-OPVAR AND
*SPRAS = SY-LANGU .
*
* NEW CODE
      SELECT *
      UP TO 1 ROWS  FROM T010P WHERE
OPVAR = T010O-OPVAR AND
SPRAS = SY-LANGU  ORDER BY PRIMARY KEY.

      ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
      IF SY-SUBRC EQ 0.
ZVFI_OB52-OPVTX =
T010P-OPVTX .
      ENDIF.
    ENDIF.
<VIM_TOTAL_STRUC> = ZVFI_OB52.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVFI_OB52 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVFI_OB52.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVFI_OB52-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZFI_OB52 WHERE
  BUKRS = ZVFI_OB52-BUKRS .
    IF SY-SUBRC = 0.
    DELETE ZFI_OB52 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZFI_OB52 WHERE
  BUKRS = ZVFI_OB52-BUKRS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZFI_OB52.
    ENDIF.
ZFI_OB52-MANDT =
ZVFI_OB52-MANDT .
ZFI_OB52-BUKRS =
ZVFI_OB52-BUKRS .
ZFI_OB52-UNAME =
ZVFI_OB52-UNAME .
ZFI_OB52-DATUM =
ZVFI_OB52-DATUM .
ZFI_OB52-UZEIT =
ZVFI_OB52-UZEIT .
    IF SY-SUBRC = 0.
    UPDATE ZFI_OB52 ##WARN_OK.
    ELSE.
    INSERT ZFI_OB52 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVFI_OB52-UPD_FLAG,
STATUS_ZVFI_OB52-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZVFI_OB52.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE * FROM ZFI_OB52 WHERE
*BUKRS = ZVFI_OB52-BUKRS .
*
* NEW CODE
  SELECT *
  UP TO 1 ROWS  FROM ZFI_OB52 WHERE
BUKRS = ZVFI_OB52-BUKRS  ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
ZVFI_OB52-MANDT =
ZFI_OB52-MANDT .
ZVFI_OB52-BUKRS =
ZFI_OB52-BUKRS .
ZVFI_OB52-UNAME =
ZFI_OB52-UNAME .
ZVFI_OB52-DATUM =
ZFI_OB52-DATUM .
ZVFI_OB52-UZEIT =
ZFI_OB52-UZEIT .
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*    SELECT SINGLE * FROM T010O WHERE
*OPVAR = ZFI_OB52-BUKRS .
*
* NEW CODE
    SELECT *
    UP TO 1 ROWS  FROM T010O WHERE
OPVAR = ZFI_OB52-BUKRS  ORDER BY PRIMARY KEY.

    ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
    IF SY-SUBRC EQ 0.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*      SELECT SINGLE * FROM T010P WHERE
*OPVAR = T010O-OPVAR AND
*SPRAS = SY-LANGU .
*
* NEW CODE
      SELECT *
      UP TO 1 ROWS  FROM T010P WHERE
OPVAR = T010O-OPVAR AND
SPRAS = SY-LANGU  ORDER BY PRIMARY KEY.

      ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
      IF SY-SUBRC EQ 0.
ZVFI_OB52-OPVTX =
T010P-OPVTX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVFI_OB52-OPVTX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFI_OB52-OPVTX .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVFI_OB52 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVFI_OB52-BUKRS TO
ZFI_OB52-BUKRS .
MOVE ZVFI_OB52-MANDT TO
ZFI_OB52-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZFI_OB52'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZFI_OB52 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZFI_OB52'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZVFI_OB52 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZFI_OB52-MANDT =
ZVFI_OB52-MANDT .
ZFI_OB52-BUKRS =
ZVFI_OB52-BUKRS .
ZFI_OB52-UNAME =
ZVFI_OB52-UNAME .
ZFI_OB52-DATUM =
ZVFI_OB52-DATUM .
ZFI_OB52-UZEIT =
ZVFI_OB52-UZEIT .
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*    SELECT SINGLE * FROM T010O WHERE
*OPVAR = ZFI_OB52-BUKRS .
*
* NEW CODE
    SELECT *
    UP TO 1 ROWS  FROM T010O WHERE
OPVAR = ZFI_OB52-BUKRS  ORDER BY PRIMARY KEY.

    ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
    IF SY-SUBRC EQ 0.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*      SELECT SINGLE * FROM T010P WHERE
*OPVAR = T010O-OPVAR AND
*SPRAS = SY-LANGU .
*
* NEW CODE
      SELECT *
      UP TO 1 ROWS  FROM T010P WHERE
OPVAR = T010O-OPVAR AND
SPRAS = SY-LANGU  ORDER BY PRIMARY KEY.

      ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
      IF SY-SUBRC EQ 0.
ZVFI_OB52-OPVTX =
T010P-OPVTX .
      ELSE.
        CLEAR SY-SUBRC.
        CLEAR ZVFI_OB52-OPVTX .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFI_OB52-OPVTX .
    ENDIF.
ENDFORM.
*...processing: ZVFI_OB52_MAIL..................................*
FORM GET_DATA_ZVFI_OB52_MAIL.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
* BEGIN. 07-07-2026 - ATC - ATC-03
* OLD CODE
*  SELECT * FROM ZFI_OB52_MAIL WHERE
*(VIM_WHERETAB) .
*
* NEW CODE
  SELECT *
 FROM ZFI_OB52_MAIL WHERE
(VIM_WHERETAB)  ORDER BY PRIMARY KEY.

* END. 07-07-2026 - ATC - ATC-03
    CLEAR ZVFI_OB52_MAIL .
ZVFI_OB52_MAIL-MANDT =
ZFI_OB52_MAIL-MANDT .
ZVFI_OB52_MAIL-BUKRS =
ZFI_OB52_MAIL-BUKRS .
ZVFI_OB52_MAIL-BNAME =
ZFI_OB52_MAIL-BNAME .
ZVFI_OB52_MAIL-SMTP_ADDR1 =
ZFI_OB52_MAIL-SMTP_ADDR1 .
ZVFI_OB52_MAIL-SMTP_ADDR2 =
ZFI_OB52_MAIL-SMTP_ADDR2 .
ZVFI_OB52_MAIL-SMTP_ADDR3 =
ZFI_OB52_MAIL-SMTP_ADDR3 .
ZVFI_OB52_MAIL-UNAME =
ZFI_OB52_MAIL-UNAME .
ZVFI_OB52_MAIL-DATUM =
ZFI_OB52_MAIL-DATUM .
ZVFI_OB52_MAIL-UZEIT =
ZFI_OB52_MAIL-UZEIT .
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*    SELECT SINGLE * FROM USR21 WHERE
*BNAME = ZFI_OB52_MAIL-BNAME .
*
* NEW CODE
    SELECT *
    UP TO 1 ROWS  FROM USR21 WHERE
BNAME = ZFI_OB52_MAIL-BNAME  ORDER BY PRIMARY KEY.

    ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
    IF SY-SUBRC EQ 0.
* BEGIN. 07-07-2026 - ATC - ATC-03
* OLD CODE
*      SELECT * FROM ADRP WHERE
*PERSNUMBER = USR21-PERSNUMBER .
*
* NEW CODE
      SELECT *
 FROM ADRP WHERE
PERSNUMBER = USR21-PERSNUMBER  ORDER BY PRIMARY KEY.

* END. 07-07-2026 - ATC - ATC-03
ZVFI_OB52_MAIL-NAME_TEXT =
ADRP-NAME_TEXT .
        EXIT.
      ENDSELECT.
    ENDIF.
<VIM_TOTAL_STRUC> = ZVFI_OB52_MAIL.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVFI_OB52_MAIL .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVFI_OB52_MAIL.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVFI_OB52_MAIL-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZFI_OB52_MAIL WHERE
  BUKRS = ZVFI_OB52_MAIL-BUKRS AND
  BNAME = ZVFI_OB52_MAIL-BNAME .
    IF SY-SUBRC = 0.
    DELETE ZFI_OB52_MAIL .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZFI_OB52_MAIL WHERE
  BUKRS = ZVFI_OB52_MAIL-BUKRS AND
  BNAME = ZVFI_OB52_MAIL-BNAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZFI_OB52_MAIL.
    ENDIF.
ZFI_OB52_MAIL-MANDT =
ZVFI_OB52_MAIL-MANDT .
ZFI_OB52_MAIL-BUKRS =
ZVFI_OB52_MAIL-BUKRS .
ZFI_OB52_MAIL-BNAME =
ZVFI_OB52_MAIL-BNAME .
ZFI_OB52_MAIL-SMTP_ADDR1 =
ZVFI_OB52_MAIL-SMTP_ADDR1 .
ZFI_OB52_MAIL-SMTP_ADDR2 =
ZVFI_OB52_MAIL-SMTP_ADDR2 .
ZFI_OB52_MAIL-SMTP_ADDR3 =
ZVFI_OB52_MAIL-SMTP_ADDR3 .
ZFI_OB52_MAIL-UNAME =
ZVFI_OB52_MAIL-UNAME .
ZFI_OB52_MAIL-DATUM =
ZVFI_OB52_MAIL-DATUM .
ZFI_OB52_MAIL-UZEIT =
ZVFI_OB52_MAIL-UZEIT .
    IF SY-SUBRC = 0.
    UPDATE ZFI_OB52_MAIL ##WARN_OK.
    ELSE.
    INSERT ZFI_OB52_MAIL .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVFI_OB52_MAIL-UPD_FLAG,
STATUS_ZVFI_OB52_MAIL-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVFI_OB52_MAIL.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE * FROM ZFI_OB52_MAIL WHERE
*BUKRS = ZVFI_OB52_MAIL-BUKRS AND
*BNAME = ZVFI_OB52_MAIL-BNAME .
*
* NEW CODE
  SELECT *
  UP TO 1 ROWS  FROM ZFI_OB52_MAIL WHERE
BUKRS = ZVFI_OB52_MAIL-BUKRS AND
BNAME = ZVFI_OB52_MAIL-BNAME  ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
ZVFI_OB52_MAIL-MANDT =
ZFI_OB52_MAIL-MANDT .
ZVFI_OB52_MAIL-BUKRS =
ZFI_OB52_MAIL-BUKRS .
ZVFI_OB52_MAIL-BNAME =
ZFI_OB52_MAIL-BNAME .
ZVFI_OB52_MAIL-SMTP_ADDR1 =
ZFI_OB52_MAIL-SMTP_ADDR1 .
ZVFI_OB52_MAIL-SMTP_ADDR2 =
ZFI_OB52_MAIL-SMTP_ADDR2 .
ZVFI_OB52_MAIL-SMTP_ADDR3 =
ZFI_OB52_MAIL-SMTP_ADDR3 .
ZVFI_OB52_MAIL-UNAME =
ZFI_OB52_MAIL-UNAME .
ZVFI_OB52_MAIL-DATUM =
ZFI_OB52_MAIL-DATUM .
ZVFI_OB52_MAIL-UZEIT =
ZFI_OB52_MAIL-UZEIT .
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*    SELECT SINGLE * FROM USR21 WHERE
*BNAME = ZFI_OB52_MAIL-BNAME .
*
* NEW CODE
    SELECT *
    UP TO 1 ROWS  FROM USR21 WHERE
BNAME = ZFI_OB52_MAIL-BNAME  ORDER BY PRIMARY KEY.

    ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
    IF SY-SUBRC EQ 0.
* BEGIN. 07-07-2026 - ATC - ATC-03
* OLD CODE
*      SELECT * FROM ADRP WHERE
*PERSNUMBER = USR21-PERSNUMBER .
*
* NEW CODE
      SELECT *
 FROM ADRP WHERE
PERSNUMBER = USR21-PERSNUMBER  ORDER BY PRIMARY KEY.

* END. 07-07-2026 - ATC - ATC-03
ZVFI_OB52_MAIL-NAME_TEXT =
ADRP-NAME_TEXT .
        EXIT.
      ENDSELECT.
      IF SY-SUBRC NE 0.
        CLEAR SY-SUBRC.
        CLEAR ZVFI_OB52_MAIL-NAME_TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFI_OB52_MAIL-NAME_TEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVFI_OB52_MAIL USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVFI_OB52_MAIL-BUKRS TO
ZFI_OB52_MAIL-BUKRS .
MOVE ZVFI_OB52_MAIL-BNAME TO
ZFI_OB52_MAIL-BNAME .
MOVE ZVFI_OB52_MAIL-MANDT TO
ZFI_OB52_MAIL-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZFI_OB52_MAIL'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZFI_OB52_MAIL TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZFI_OB52_MAIL'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZVFI_OB52_MAIL USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZFI_OB52_MAIL-MANDT =
ZVFI_OB52_MAIL-MANDT .
ZFI_OB52_MAIL-BUKRS =
ZVFI_OB52_MAIL-BUKRS .
ZFI_OB52_MAIL-BNAME =
ZVFI_OB52_MAIL-BNAME .
ZFI_OB52_MAIL-SMTP_ADDR1 =
ZVFI_OB52_MAIL-SMTP_ADDR1 .
ZFI_OB52_MAIL-SMTP_ADDR2 =
ZVFI_OB52_MAIL-SMTP_ADDR2 .
ZFI_OB52_MAIL-SMTP_ADDR3 =
ZVFI_OB52_MAIL-SMTP_ADDR3 .
ZFI_OB52_MAIL-UNAME =
ZVFI_OB52_MAIL-UNAME .
ZFI_OB52_MAIL-DATUM =
ZVFI_OB52_MAIL-DATUM .
ZFI_OB52_MAIL-UZEIT =
ZVFI_OB52_MAIL-UZEIT .
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*    SELECT SINGLE * FROM USR21 WHERE
*BNAME = ZFI_OB52_MAIL-BNAME .
*
* NEW CODE
    SELECT *
    UP TO 1 ROWS  FROM USR21 WHERE
BNAME = ZFI_OB52_MAIL-BNAME  ORDER BY PRIMARY KEY.

    ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
    IF SY-SUBRC EQ 0.
* BEGIN. 07-07-2026 - ATC - ATC-03
* OLD CODE
*      SELECT * FROM ADRP WHERE
*PERSNUMBER = USR21-PERSNUMBER .
*
* NEW CODE
      SELECT *
 FROM ADRP WHERE
PERSNUMBER = USR21-PERSNUMBER  ORDER BY PRIMARY KEY.

* END. 07-07-2026 - ATC - ATC-03
ZVFI_OB52_MAIL-NAME_TEXT =
ADRP-NAME_TEXT .
        EXIT.
      ENDSELECT.
      IF SY-SUBRC NE 0.
        CLEAR SY-SUBRC.
        CLEAR ZVFI_OB52_MAIL-NAME_TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFI_OB52_MAIL-NAME_TEXT .
    ENDIF.
ENDFORM.
*...processing: ZVFI_OB52_T001B.................................*
FORM GET_DATA_ZVFI_OB52_T001B.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
* BEGIN. 07-07-2026 - ATC - ATC-03
* OLD CODE
*  SELECT * FROM ZFI_OB52_T001B WHERE
*    RRCTY EQ '0' AND
*    ( MKOAR EQ '+' OR
*    MKOAR EQ 'A' OR
*    MKOAR EQ 'D' OR
*    MKOAR EQ 'K' OR
*    MKOAR EQ 'M' OR
*    MKOAR EQ 'S' OR
*    MKOAR EQ 'V' OR
*    MKOAR EQ ' ' ) AND
*(VIM_WHERETAB) .
*
* NEW CODE
  SELECT *
 FROM ZFI_OB52_T001B WHERE
    RRCTY EQ '0' AND
    ( MKOAR EQ '+' OR
    MKOAR EQ 'A' OR
    MKOAR EQ 'D' OR
    MKOAR EQ 'K' OR
    MKOAR EQ 'M' OR
    MKOAR EQ 'S' OR
    MKOAR EQ 'V' OR
    MKOAR EQ ' ' ) AND
(VIM_WHERETAB)  ORDER BY PRIMARY KEY.

* END. 07-07-2026 - ATC - ATC-03
    CLEAR ZVFI_OB52_T001B .
ZVFI_OB52_T001B-MANDT =
ZFI_OB52_T001B-MANDT .
ZVFI_OB52_T001B-RRCTY =
ZFI_OB52_T001B-RRCTY .
ZVFI_OB52_T001B-BUKRS =
ZFI_OB52_T001B-BUKRS .
ZVFI_OB52_T001B-MKOAR =
ZFI_OB52_T001B-MKOAR .
ZVFI_OB52_T001B-BKONT =
ZFI_OB52_T001B-BKONT .
ZVFI_OB52_T001B-VKONT =
ZFI_OB52_T001B-VKONT .
ZVFI_OB52_T001B-FRYE1 =
ZFI_OB52_T001B-FRYE1 .
ZVFI_OB52_T001B-FRPE1 =
ZFI_OB52_T001B-FRPE1 .
ZVFI_OB52_T001B-TOYE1 =
ZFI_OB52_T001B-TOYE1 .
ZVFI_OB52_T001B-TOPE1 =
ZFI_OB52_T001B-TOPE1 .
ZVFI_OB52_T001B-FRYE2 =
ZFI_OB52_T001B-FRYE2 .
ZVFI_OB52_T001B-FRPE2 =
ZFI_OB52_T001B-FRPE2 .
ZVFI_OB52_T001B-TOYE2 =
ZFI_OB52_T001B-TOYE2 .
ZVFI_OB52_T001B-BRGRU =
ZFI_OB52_T001B-BRGRU .
ZVFI_OB52_T001B-TOPE2 =
ZFI_OB52_T001B-TOPE2 .
ZVFI_OB52_T001B-APROBAR =
ZFI_OB52_T001B-APROBAR .
ZVFI_OB52_T001B-TEXTO_AJUSTE1 =
ZFI_OB52_T001B-TEXTO_AJUSTE1 .
ZVFI_OB52_T001B-TEXTO_AJUSTE2 =
ZFI_OB52_T001B-TEXTO_AJUSTE2 .
<VIM_TOTAL_STRUC> = ZVFI_OB52_T001B.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVFI_OB52_T001B .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVFI_OB52_T001B.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVFI_OB52_T001B-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZFI_OB52_T001B WHERE
  RRCTY = ZVFI_OB52_T001B-RRCTY AND
  BUKRS = ZVFI_OB52_T001B-BUKRS AND
  MKOAR = ZVFI_OB52_T001B-MKOAR AND
  BKONT = ZVFI_OB52_T001B-BKONT .
    IF SY-SUBRC = 0.
    DELETE ZFI_OB52_T001B .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZFI_OB52_T001B WHERE
  RRCTY = ZVFI_OB52_T001B-RRCTY AND
  BUKRS = ZVFI_OB52_T001B-BUKRS AND
  MKOAR = ZVFI_OB52_T001B-MKOAR AND
  BKONT = ZVFI_OB52_T001B-BKONT .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZFI_OB52_T001B.
    ENDIF.
ZFI_OB52_T001B-MANDT =
ZVFI_OB52_T001B-MANDT .
ZFI_OB52_T001B-RRCTY =
ZVFI_OB52_T001B-RRCTY .
ZFI_OB52_T001B-BUKRS =
ZVFI_OB52_T001B-BUKRS .
ZFI_OB52_T001B-MKOAR =
ZVFI_OB52_T001B-MKOAR .
ZFI_OB52_T001B-BKONT =
ZVFI_OB52_T001B-BKONT .
ZFI_OB52_T001B-VKONT =
ZVFI_OB52_T001B-VKONT .
ZFI_OB52_T001B-FRYE1 =
ZVFI_OB52_T001B-FRYE1 .
ZFI_OB52_T001B-FRPE1 =
ZVFI_OB52_T001B-FRPE1 .
ZFI_OB52_T001B-TOYE1 =
ZVFI_OB52_T001B-TOYE1 .
ZFI_OB52_T001B-TOPE1 =
ZVFI_OB52_T001B-TOPE1 .
ZFI_OB52_T001B-FRYE2 =
ZVFI_OB52_T001B-FRYE2 .
ZFI_OB52_T001B-FRPE2 =
ZVFI_OB52_T001B-FRPE2 .
ZFI_OB52_T001B-TOYE2 =
ZVFI_OB52_T001B-TOYE2 .
ZFI_OB52_T001B-BRGRU =
ZVFI_OB52_T001B-BRGRU .
ZFI_OB52_T001B-TOPE2 =
ZVFI_OB52_T001B-TOPE2 .
ZFI_OB52_T001B-APROBAR =
ZVFI_OB52_T001B-APROBAR .
ZFI_OB52_T001B-TEXTO_AJUSTE1 =
ZVFI_OB52_T001B-TEXTO_AJUSTE1 .
ZFI_OB52_T001B-TEXTO_AJUSTE2 =
ZVFI_OB52_T001B-TEXTO_AJUSTE2 .
    IF SY-SUBRC = 0.
    UPDATE ZFI_OB52_T001B ##WARN_OK.
    ELSE.
    INSERT ZFI_OB52_T001B .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVFI_OB52_T001B-UPD_FLAG,
STATUS_ZVFI_OB52_T001B-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVFI_OB52_T001B.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE * FROM ZFI_OB52_T001B WHERE
*RRCTY = ZVFI_OB52_T001B-RRCTY AND
*BUKRS = ZVFI_OB52_T001B-BUKRS AND
*MKOAR = ZVFI_OB52_T001B-MKOAR AND
*BKONT = ZVFI_OB52_T001B-BKONT .
*
* NEW CODE
  SELECT *
  UP TO 1 ROWS  FROM ZFI_OB52_T001B WHERE
RRCTY = ZVFI_OB52_T001B-RRCTY AND
BUKRS = ZVFI_OB52_T001B-BUKRS AND
MKOAR = ZVFI_OB52_T001B-MKOAR AND
BKONT = ZVFI_OB52_T001B-BKONT  ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
ZVFI_OB52_T001B-MANDT =
ZFI_OB52_T001B-MANDT .
ZVFI_OB52_T001B-RRCTY =
ZFI_OB52_T001B-RRCTY .
ZVFI_OB52_T001B-BUKRS =
ZFI_OB52_T001B-BUKRS .
ZVFI_OB52_T001B-MKOAR =
ZFI_OB52_T001B-MKOAR .
ZVFI_OB52_T001B-BKONT =
ZFI_OB52_T001B-BKONT .
ZVFI_OB52_T001B-VKONT =
ZFI_OB52_T001B-VKONT .
ZVFI_OB52_T001B-FRYE1 =
ZFI_OB52_T001B-FRYE1 .
ZVFI_OB52_T001B-FRPE1 =
ZFI_OB52_T001B-FRPE1 .
ZVFI_OB52_T001B-TOYE1 =
ZFI_OB52_T001B-TOYE1 .
ZVFI_OB52_T001B-TOPE1 =
ZFI_OB52_T001B-TOPE1 .
ZVFI_OB52_T001B-FRYE2 =
ZFI_OB52_T001B-FRYE2 .
ZVFI_OB52_T001B-FRPE2 =
ZFI_OB52_T001B-FRPE2 .
ZVFI_OB52_T001B-TOYE2 =
ZFI_OB52_T001B-TOYE2 .
ZVFI_OB52_T001B-BRGRU =
ZFI_OB52_T001B-BRGRU .
ZVFI_OB52_T001B-TOPE2 =
ZFI_OB52_T001B-TOPE2 .
ZVFI_OB52_T001B-APROBAR =
ZFI_OB52_T001B-APROBAR .
ZVFI_OB52_T001B-TEXTO_AJUSTE1 =
ZFI_OB52_T001B-TEXTO_AJUSTE1 .
ZVFI_OB52_T001B-TEXTO_AJUSTE2 =
ZFI_OB52_T001B-TEXTO_AJUSTE2 .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVFI_OB52_T001B USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVFI_OB52_T001B-RRCTY TO
ZFI_OB52_T001B-RRCTY .
MOVE ZVFI_OB52_T001B-BUKRS TO
ZFI_OB52_T001B-BUKRS .
MOVE ZVFI_OB52_T001B-MKOAR TO
ZFI_OB52_T001B-MKOAR .
MOVE ZVFI_OB52_T001B-BKONT TO
ZFI_OB52_T001B-BKONT .
MOVE ZVFI_OB52_T001B-MANDT TO
ZFI_OB52_T001B-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZFI_OB52_T001B'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZFI_OB52_T001B TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZFI_OB52_T001B'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
*...processing: ZVFI_OB52_USER..................................*
FORM GET_DATA_ZVFI_OB52_USER.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
* BEGIN. 07-07-2026 - ATC - ATC-03
* OLD CODE
*  SELECT * FROM ZFI_OB52_USER WHERE
*(VIM_WHERETAB) .
*
* NEW CODE
  SELECT *
 FROM ZFI_OB52_USER WHERE
(VIM_WHERETAB)  ORDER BY PRIMARY KEY.

* END. 07-07-2026 - ATC - ATC-03
    CLEAR ZVFI_OB52_USER .
ZVFI_OB52_USER-MANDT =
ZFI_OB52_USER-MANDT .
ZVFI_OB52_USER-BUKRS =
ZFI_OB52_USER-BUKRS .
ZVFI_OB52_USER-BNAME =
ZFI_OB52_USER-BNAME .
ZVFI_OB52_USER-MODIFICAR =
ZFI_OB52_USER-MODIFICAR .
ZVFI_OB52_USER-APROBAR =
ZFI_OB52_USER-APROBAR .
ZVFI_OB52_USER-REPORTE =
ZFI_OB52_USER-REPORTE .
ZVFI_OB52_USER-UNAME =
ZFI_OB52_USER-UNAME .
ZVFI_OB52_USER-DATUM =
ZFI_OB52_USER-DATUM .
ZVFI_OB52_USER-UZEIT =
ZFI_OB52_USER-UZEIT .
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*    SELECT SINGLE * FROM USR21 WHERE
*BNAME = ZFI_OB52_USER-BNAME .
*
* NEW CODE
    SELECT *
    UP TO 1 ROWS  FROM USR21 WHERE
BNAME = ZFI_OB52_USER-BNAME  ORDER BY PRIMARY KEY.

    ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
    IF SY-SUBRC EQ 0.
* BEGIN. 07-07-2026 - ATC - ATC-03
* OLD CODE
*      SELECT * FROM ADRP WHERE
*PERSNUMBER = USR21-PERSNUMBER .
*
* NEW CODE
      SELECT *
 FROM ADRP WHERE
PERSNUMBER = USR21-PERSNUMBER  ORDER BY PRIMARY KEY.

* END. 07-07-2026 - ATC - ATC-03
ZVFI_OB52_USER-NAME_TEXT =
ADRP-NAME_TEXT .
        EXIT.
      ENDSELECT.
    ENDIF.
<VIM_TOTAL_STRUC> = ZVFI_OB52_USER.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVFI_OB52_USER .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVFI_OB52_USER.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVFI_OB52_USER-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZFI_OB52_USER WHERE
  BUKRS = ZVFI_OB52_USER-BUKRS AND
  BNAME = ZVFI_OB52_USER-BNAME .
    IF SY-SUBRC = 0.
    DELETE ZFI_OB52_USER .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZFI_OB52_USER WHERE
  BUKRS = ZVFI_OB52_USER-BUKRS AND
  BNAME = ZVFI_OB52_USER-BNAME .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZFI_OB52_USER.
    ENDIF.
ZFI_OB52_USER-MANDT =
ZVFI_OB52_USER-MANDT .
ZFI_OB52_USER-BUKRS =
ZVFI_OB52_USER-BUKRS .
ZFI_OB52_USER-BNAME =
ZVFI_OB52_USER-BNAME .
ZFI_OB52_USER-MODIFICAR =
ZVFI_OB52_USER-MODIFICAR .
ZFI_OB52_USER-APROBAR =
ZVFI_OB52_USER-APROBAR .
ZFI_OB52_USER-REPORTE =
ZVFI_OB52_USER-REPORTE .
ZFI_OB52_USER-UNAME =
ZVFI_OB52_USER-UNAME .
ZFI_OB52_USER-DATUM =
ZVFI_OB52_USER-DATUM .
ZFI_OB52_USER-UZEIT =
ZVFI_OB52_USER-UZEIT .
    IF SY-SUBRC = 0.
    UPDATE ZFI_OB52_USER ##WARN_OK.
    ELSE.
    INSERT ZFI_OB52_USER .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVFI_OB52_USER-UPD_FLAG,
STATUS_ZVFI_OB52_USER-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZVFI_OB52_USER.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE * FROM ZFI_OB52_USER WHERE
*BUKRS = ZVFI_OB52_USER-BUKRS AND
*BNAME = ZVFI_OB52_USER-BNAME .
*
* NEW CODE
  SELECT *
  UP TO 1 ROWS  FROM ZFI_OB52_USER WHERE
BUKRS = ZVFI_OB52_USER-BUKRS AND
BNAME = ZVFI_OB52_USER-BNAME  ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
ZVFI_OB52_USER-MANDT =
ZFI_OB52_USER-MANDT .
ZVFI_OB52_USER-BUKRS =
ZFI_OB52_USER-BUKRS .
ZVFI_OB52_USER-BNAME =
ZFI_OB52_USER-BNAME .
ZVFI_OB52_USER-MODIFICAR =
ZFI_OB52_USER-MODIFICAR .
ZVFI_OB52_USER-APROBAR =
ZFI_OB52_USER-APROBAR .
ZVFI_OB52_USER-REPORTE =
ZFI_OB52_USER-REPORTE .
ZVFI_OB52_USER-UNAME =
ZFI_OB52_USER-UNAME .
ZVFI_OB52_USER-DATUM =
ZFI_OB52_USER-DATUM .
ZVFI_OB52_USER-UZEIT =
ZFI_OB52_USER-UZEIT .
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*    SELECT SINGLE * FROM USR21 WHERE
*BNAME = ZFI_OB52_USER-BNAME .
*
* NEW CODE
    SELECT *
    UP TO 1 ROWS  FROM USR21 WHERE
BNAME = ZFI_OB52_USER-BNAME  ORDER BY PRIMARY KEY.

    ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
    IF SY-SUBRC EQ 0.
* BEGIN. 07-07-2026 - ATC - ATC-03
* OLD CODE
*      SELECT * FROM ADRP WHERE
*PERSNUMBER = USR21-PERSNUMBER .
*
* NEW CODE
      SELECT *
 FROM ADRP WHERE
PERSNUMBER = USR21-PERSNUMBER  ORDER BY PRIMARY KEY.

* END. 07-07-2026 - ATC - ATC-03
ZVFI_OB52_USER-NAME_TEXT =
ADRP-NAME_TEXT .
        EXIT.
      ENDSELECT.
      IF SY-SUBRC NE 0.
        CLEAR SY-SUBRC.
        CLEAR ZVFI_OB52_USER-NAME_TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFI_OB52_USER-NAME_TEXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVFI_OB52_USER USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVFI_OB52_USER-BUKRS TO
ZFI_OB52_USER-BUKRS .
MOVE ZVFI_OB52_USER-BNAME TO
ZFI_OB52_USER-BNAME .
MOVE ZVFI_OB52_USER-MANDT TO
ZFI_OB52_USER-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZFI_OB52_USER'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZFI_OB52_USER TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZFI_OB52_USER'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZVFI_OB52_USER USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZFI_OB52_USER-MANDT =
ZVFI_OB52_USER-MANDT .
ZFI_OB52_USER-BUKRS =
ZVFI_OB52_USER-BUKRS .
ZFI_OB52_USER-BNAME =
ZVFI_OB52_USER-BNAME .
ZFI_OB52_USER-MODIFICAR =
ZVFI_OB52_USER-MODIFICAR .
ZFI_OB52_USER-APROBAR =
ZVFI_OB52_USER-APROBAR .
ZFI_OB52_USER-REPORTE =
ZVFI_OB52_USER-REPORTE .
ZFI_OB52_USER-UNAME =
ZVFI_OB52_USER-UNAME .
ZFI_OB52_USER-DATUM =
ZVFI_OB52_USER-DATUM .
ZFI_OB52_USER-UZEIT =
ZVFI_OB52_USER-UZEIT .
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*    SELECT SINGLE * FROM USR21 WHERE
*BNAME = ZFI_OB52_USER-BNAME .
*
* NEW CODE
    SELECT *
    UP TO 1 ROWS  FROM USR21 WHERE
BNAME = ZFI_OB52_USER-BNAME  ORDER BY PRIMARY KEY.

    ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
    IF SY-SUBRC EQ 0.
* BEGIN. 07-07-2026 - ATC - ATC-03
* OLD CODE
*      SELECT * FROM ADRP WHERE
*PERSNUMBER = USR21-PERSNUMBER .
*
* NEW CODE
      SELECT *
 FROM ADRP WHERE
PERSNUMBER = USR21-PERSNUMBER  ORDER BY PRIMARY KEY.

* END. 07-07-2026 - ATC - ATC-03
ZVFI_OB52_USER-NAME_TEXT =
ADRP-NAME_TEXT .
        EXIT.
      ENDSELECT.
      IF SY-SUBRC NE 0.
        CLEAR SY-SUBRC.
        CLEAR ZVFI_OB52_USER-NAME_TEXT .
      ENDIF.
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZVFI_OB52_USER-NAME_TEXT .
    ENDIF.
ENDFORM.
