PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFI_DOC_ZPSAZR CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFI_DOC_ZPSAZR-BUKRS .
    FIELD ZFI_DOC_ZPSAZR-BELNR .
    FIELD ZFI_DOC_ZPSAZR-GJAHR .
    FIELD ZFI_DOC_ZPSAZR-ZP_BLART .
    FIELD ZFI_DOC_ZPSAZR-HBKID .
    FIELD ZFI_DOC_ZPSAZR-HKTID .
    FIELD ZFI_DOC_ZPSAZR-CPUDT .
    FIELD ZFI_DOC_ZPSAZR-BUDAT .
    FIELD ZFI_DOC_ZPSAZR-BKTXT .
    FIELD ZFI_DOC_ZPSAZR-LIFNR .
    FIELD ZFI_DOC_ZPSAZR-UBHKT .
    FIELD ZFI_DOC_ZPSAZR-LAUFD .
    FIELD ZFI_DOC_ZPSAZR-LAUFI .
    FIELD ZFI_DOC_ZPSAZR-IDENTIF_PAGO .
    FIELD ZFI_DOC_ZPSAZR-ZCOMPENS_ZP .
    FIELD ZFI_DOC_ZPSAZR-AUGDT .
    FIELD ZFI_DOC_ZPSAZR-ZNDOC_SA .
    FIELD ZFI_DOC_ZPSAZR-ZEDOC_SA .
    FIELD ZFI_DOC_ZPSAZR-SA_BLART .
    FIELD ZFI_DOC_ZPSAZR-ZFDOC_SA .
    FIELD ZFI_DOC_ZPSAZR-ZFCDOC_SA .
    FIELD ZFI_DOC_ZPSAZR-ZCOMPENS_SA .
    FIELD ZFI_DOC_ZPSAZR-ZFCOMDOC_SAZR .
    FIELD ZFI_DOC_ZPSAZR-ZNDOC_ZR .
    FIELD ZFI_DOC_ZPSAZR-ZEDOC_ZR .
    FIELD ZFI_DOC_ZPSAZR-ZR_BLART .
    FIELD ZFI_DOC_ZPSAZR-ZFDOC_ZR .
    FIELD ZFI_DOC_ZPSAZR-ZFCDOC_ZR .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFI_DOC_ZPSAZR-BUKRS .
    FIELD ZFI_DOC_ZPSAZR-BELNR .
    FIELD ZFI_DOC_ZPSAZR-GJAHR .
    FIELD ZFI_DOC_ZPSAZR-ZP_BLART .
    FIELD ZFI_DOC_ZPSAZR-HBKID .
    FIELD ZFI_DOC_ZPSAZR-HKTID .
    FIELD ZFI_DOC_ZPSAZR-CPUDT .
    FIELD ZFI_DOC_ZPSAZR-BUDAT .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
