PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFICH001 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFICH001-BUKRS .
    FIELD ZFICH001-LIFNR .
    FIELD ZFICH001-HBKID .
    FIELD ZFICH001-HKTID .
    FIELD ZFICH001-CHECT .
    FIELD ZFICH001-FECHA_REG .
    FIELD ZFICH001-HORA_REG .
    FIELD ZFICH001-BELNR .
    FIELD ZFICH001-GJAHR .
    FIELD ZFICH001-HKONT .
    FIELD ZFICH001-ESTADO .
    FIELD ZFICH001-AGENCIA .
    FIELD ZFICH001-USUARIO .
    FIELD ZFICH001-TRASPASADO .
    FIELD ZFICH001-OBSERVACION .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFICH001-BUKRS .
    FIELD ZFICH001-LIFNR .
    FIELD ZFICH001-HBKID .
    FIELD ZFICH001-HKTID .
    FIELD ZFICH001-CHECT .
    FIELD ZFICH001-FECHA_REG .
    FIELD ZFICH001-HORA_REG .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
