*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFIFPAGRECTOP.                    " Global Data
  INCLUDE LZFIFPAGRECUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFIFPAGRECF00                          . " subprograms
  INCLUDE LZFIFPAGRECI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFIFPAGRECF...                    " Subprograms
* INCLUDE LZFIFPAGRECO...                    " PBO-Modules
* INCLUDE LZFIFPAGRECI...                    " PAI-Modules
