PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZFIGIRO-BUKRS .
    FIELD ZFIGIRO-GIRO_1 .
    FIELD ZFIGIRO-GIRO_2 .
    FIELD ZFIGIRO-GIRO_3 .
    FIELD ZFIGIRO-GIRO_4 .
    FIELD ZFIGIRO-GIRO_5 .
    FIELD ZFIGIRO-GIRO_6 .
    FIELD ZFIGIRO-GIRO_7 .
    FIELD ZFIGIRO-GIRO_8 .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZFIGIRO-BUKRS .
  module detail_pai.
 endchain.
