PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFIGIRO CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFIGIRO-BUKRS .
    FIELD ZFIGIRO-GIRO_1 .
    FIELD ZFIGIRO-GIRO_2 .
    FIELD ZFIGIRO-GIRO_3 .
    FIELD ZFIGIRO-GIRO_4 .
    FIELD ZFIGIRO-GIRO_5 .
    FIELD ZFIGIRO-GIRO_6 .
    FIELD ZFIGIRO-GIRO_7 .
    FIELD ZFIGIRO-GIRO_8 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFIGIRO-BUKRS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
