FUNCTION-POOL ZFIMDP001.                    "MESSAGE-ID ..

*TYPE-POOLS:  fibl.
TYPE-POOLS: SHLP.
INCLUDE FIBLCHK_DATA1.

TABLES:
  *T012T,
  *BNKA_BF.



DATA: BEGIN OF G_RENUMBER,
      zbukr like payr-zbukr,
      hbkid like payr-hbkid,
      hktid like payr-hktid,
      OLD_CHECF LIKE PAYR-CHECF, old_chect like payr-chect,
      NEW_CHECF LIKE PAYR-CHECF, NEW_CHECT LIKE PAYR-CHECT,
      OLD_STAPF LIKE PCEC-STAPL, old_stapt like pcec-stapl,
      NEW_STAPF LIKE PCEC-STAPL, NEW_STAPT LIKE PCEC-STAPL,
*     old_pcec  LIKE pcec,
      NEW_PCEC  LIKE PCEC,
      FLG_CONNECTED_LOT TYPE C,
      FLG_PAYROLL_CHECK TYPE C,
      voidr     like payr-voidr,
      end of g_renumber.

DATA:  BEGIN OF G_SUBSCREEN,
       PROGRAM LIKE SY-REPID,
       SCREEN LIKE SY-DYNNR,
       END OF G_SUBSCREEN.
CONSTANTS:
  CON_PROGRAM_HRO LIKE SY-REPID VALUE 'SAPLFIBLCHK',
  CON_PROGRAM_ERP LIKE SY-REPID VALUE 'SAPLFIBLCHK_FI',
  CON_SUBSCREEN   LIKE SY-DYNNR VALUE 109.

INCLUDE RPC4F_0C.                      "Schnittstelle zum HR

DATA:
  G_APPLICATION_SYSTEM_TYPE TYPE CHAR01,
  TEXT_106(50) TYPE C,                 " for text box of screen 106
* global data for screen 107
  G_FORM_INFO           LIKE PC407,
  G_TAB_FORM_DATA       LIKE PC408 OCCURS 70 WITH HEADER LINE,
* global data for screen 601
  G_ORIGINAL_PAYR LIKE PAYR.
* G_FLG_PAYMENT_SCREEN TYPE C,                  "only used by screen 104

TYPES: BEGIN OF TYP_EXCHANGE,
  ZBUKR LIKE PAYR-ZBUKR,
  HBKID1 LIKE PAYR-HBKID,
  HKTID1 LIKE PAYR-HKTID,
  CHECT1 LIKE PAYR-CHECT,
  HBKID2 LIKE PAYR-HBKID,
  HKTID2 LIKE PAYR-HKTID,
  CHECT2 LIKE PAYR-CHECT,
       END OF TYP_EXCHANGE.
CONSTANTS:
  CON_HRONLY            LIKE SCREEN-GROUP1 VALUE 'HRO'.
