PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZFIMOTEMISAN-BUKRS .
    FIELD ZFIMOTEMISAN-ZMOTIV .
    FIELD ZFIMOTEMISAN-ZNUMERO .
    FIELD ZFIMOTEMISAN-ZLETRAS .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZFIMOTEMISAN-BUKRS .
    FIELD ZFIMOTEMISAN-ZMOTIV .
  module detail_pai.
 endchain.
