
PROCESS BEFORE OUTPUT.
  MODULE STATUS_0100.
   CALL SUBSCREEN A_SUB0101 INCLUDING SY-REPID '0101'.

PROCESS AFTER INPUT.
  CALL SUBSCREEN: A_SUB0101.

  CHAIN.
    FIELD BUKRS.
    MODULE TCC_MODIFY_BUKRS.
  ENDCHAIN.

  CHAIN.
    FIELD HBKID.
    MODULE TCC_MODIFY_HBKID.
  ENDCHAIN.

  CHAIN.
    FIELD HKTID.
    MODULE TCC_MODIFY_HKTID.
  ENDCHAIN.

  MODULE USER_COMMAND_0100.

PROCESS ON VALUE-REQUEST.
  FIELD HKTID MODULE MODULE_MATCH1.
