*&---------------------------------------------------------------------*
*& Report  ZFIMRP005
*&
*&---------------------------------------------------------------------*
*& Descripcion : reporte para cambio de estado cheques en forma masiva,
*&               llamado por un job desde el programa ZFIMDP001
*& F. creacion : 30.11.2009
*& programador : Luis Sereño S.
*&
*&---------------------------------------------------------------------*

REPORT  ZFIMRP005.
TYPE-POOLS: SLIS.

TABLES: ZPAYR, BKPF,APQI,ZMOT_PRESCRIP.
RANGES: T_CTA FOR BSEG-HKONT.
FIELD-SYMBOLS: <F>, <F1>.

DATA: G_REPID LIKE SY-REPID,
GS_PRINT            TYPE SLIS_PRINT_ALV,
GT_LIST_TOP_OF_PAGE TYPE SLIS_T_LISTHEADER,
GT_EVENTS           TYPE SLIS_T_EVENT,
GT_SORT             TYPE SLIS_T_SORTINFO_ALV,
GS_LAYOUT           TYPE SLIS_LAYOUT_ALV,
GT_FIELDCAT         TYPE SLIS_T_FIELDCAT_ALV,
FIELDCAT_LN LIKE LINE OF GT_FIELDCAT,

COL_POS TYPE I.

DATA LS_TOOLBAR TYPE STB_BUTTON.

DATA: USER_COMMAND LIKE SY-UCOMM,
      SAVE_CODE    LIKE SY-UCOMM.

DATA  HBKID        TYPE HBKID.
DATA  BUKRS        TYPE BUKRS.
DATA  HKTID        TYPE HKTID.
DATA  CHECT        TYPE CHECT.
DATA  DES_CTA(51)  TYPE C.
DATA  G_EXIS(1)    TYPE C.
CONSTANTS G_Desf(51) TYPE C VALUE 'Fecha Emisión de Cheque Posterior a Fecha Ejecución'.
DATA: G_VALID_CTA  TYPE I.
DATA : GROUP(30) TYPE C.
DATA : G_VOIDR TYPE PAYR-VOIDR.

*- Tabla de parámetros pa' "submitir" el RSBDCSUB. -*
DATA: BEGIN OF I_TABLSUBM OCCURS 0.
        INCLUDE STRUCTURE RSPARAMS.
DATA: END OF I_TABLSUBM.

DATA : G_BLDAT TYPE BLDAT.

DATA: BEGIN OF T_OK OCCURS 0,
  BUKRS LIKE  BSEG-BUKRS,
  BELNR LIKE  BSEG-BELNR,
  BUZEI LIKE  BSEG-BUZEI,
  GJAHR LIKE  BSEG-GJAHR,
  HKONT LIKE  BSEG-HKONT,
  STATUS LIKE ICON-ID,
  CHEK1(1) TYPE C,
  WRBTR LIKE BSEG-WRBTR,
  CHECT LIKE  PAYR-CHECT,
  HKONTD LIKE  BSEG-HKONT, " se deja cuenta de destino.
  SGTXT  LIKE  BSEG-SGTXT, " TEXTO
  DATEV  TYPE I,
  ESTADO(51) TYPE C,
  VBLNR  LIKE  PAYR-VBLNR,
  WAERS LIKE BKPF-WAERS,
  HBKID  LIKE  PAYR-HBKID,
  HKTID  LIKE  PAYR-HKTID,
  LIFNR  LIKE  PAYR-LIFNR,
  PBUDAT LIKE  PAYR-GJAHR,
  BLDAT    LIKE  BKPF-BLDAT,
  LITTLE(40) TYPE  C,
  ZALDT    LIKE  PAYR-ZALDT,
  ZNME1    LIKE  PAYR-ZNME1,
  ZMOTE    LIKE  bseg-ZZMOT_EMIS,
  BELNRACT LIKE  BSEG-BELNR,
END OF T_OK.



*DATA:
DATA G_LITTLE(40)   TYPE C.
DATA : P_ZMOT_EMIS TYPE BSEG-ZZMOT_EMIS.
DATA : IT_PAYR LIKE PAYR OCCURS 0 WITH HEADER LINE.
DATA: IT_REVERSA LIKE ZREVERSACHEQUE OCCURS 0 WITH HEADER LINE.
DATA : TI_ZCTAP LIKE ZCTA_PRESCRIP OCCURS 0 WITH HEADER LINE.
DATA: P_CTAREVERSA TYPE  BSEG-HKONT.
DATA: P_BELNRANT   TYPE  ZREVERSACHEQUE-BELNR.
DATA: it_rf05r_acct LIKE RF05R_ACCT OCCURS 0 WITH HEADER LINE.



* info messages as popup, log or no info
SELECTION-SCREEN: BEGIN OF BLOCK b1 WITH FRAME TITLE text-t01.

SELECT-OPTIONS: S_BUKRS FOR ZPAYR-ZBUKR,
                S_HBKID FOR ZPAYR-HBKID,
                S_HKTID FOR ZPAYR-HKTID,
                S_PBUDAT FOR SY-DATUM,
                PSEL     FOR ZPAYR-CHECT.
SELECTION-SCREEN  END OF BLOCK b1.

SELECTION-SCREEN SKIP 1.
SELECTION-SCREEN BEGIN OF BLOCK BL1 WITH FRAME TITLE TEXT-001.
PARAMETERS: XELE  TYPE c RADIOBUTTON GROUP RBL1,
            XFIS  type c RADIOBUTTON GROUP RBL1.
SELECTION-SCREEN END   OF BLOCK BL1.


START-OF-SELECTION.

 IF XELE EQ 'X'. "masivo electronico"
 BKPF-BUDAT = S_PBUDAT-LOW.
        SAVE_CODE ='PR0_01'.
        PERFORM CADUCA_ELEC_MASIV     TABLES PSEL
                                      T_OK
                                      USING S_BUKRS-LOW S_HBKID-LOW S_HKTID-LOW S_PBUDAT-LOW.


*     PERFORM REPORTE.
      PERFORM EJEC_MAS.


 ENDIF.

 IF XFIS EQ 'X'. "PRESCRIBIR"
    BKPF-BUDAT = S_PBUDAT-LOW.
        SAVE_CODE ='PR0_04'.
        PERFORM PRESCRIBIR     TABLES PSEL
                                      T_OK
                                      USING S_BUKRS-LOW S_HBKID-LOW S_HKTID-LOW S_PBUDAT-LOW.


*      PERFORM REPORTE.
       PERFORM EJEC_MAS.
 ENDIF.


INCLUDE ZFIMRP005_INC.
