*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFIMTVRECHZTOP.                   " Global Data
  INCLUDE LZFIMTVRECHZUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFIMTVRECHZF00                         . " subprograms
  INCLUDE LZFIMTVRECHZI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFIMTVRECHZF...                   " Subprograms
* INCLUDE LZFIMTVRECHZO...                   " PBO-Modules
* INCLUDE LZFIMTVRECHZI...                   " PAI-Modules
