
PROCESS BEFORE OUTPUT.
  MODULE TABLE_INIT.
  MODULE STATUS_0100.
  MODULE DYNPRO_MODIFICATION_1100.
  MODULE T_001_ACTIVE_TAB_SET.
  MODULE BALANCE.

  CALL SUBSCREEN T_001_SCA
    INCLUDING G_T_001-PROG G_T_001-SUBSCREEN.

  LOOP AT   G_TABLE_ITAB
       INTO G_TABLE_WA
       WITH CONTROL TABLE
       CURSOR TABLE-TOP_LINE.
    MODULE TABLE_GET_LINES.
  ENDLOOP.

PROCESS AFTER INPUT.
  CALL SUBSCREEN T_001_SCA.


  LOOP AT G_TABLE_ITAB.
    CHAIN.
      FIELD ZACGL_ITEM_TBCTR-STATE.
      FIELD ZACGL_ITEM_TBCTR-BUKRS.
      FIELD ZACGL_ITEM_TBCTR-SHKZG.
      FIELD ZACGL_ITEM_TBCTR-MWSKZ.
      FIELD ZACGL_ITEM_TBCTR-WRBTR.
      FIELD ZACGL_ITEM_TBCTR-VALUT.
      FIELD ZACGL_ITEM_TBCTR-ZUONR.
      FIELD ZACGL_ITEM_TBCTR-SGTXT.
      FIELD ZACGL_ITEM_TBCTR-KOKRS.
      FIELD ZACGL_ITEM_TBCTR-KOSTL.
      FIELD ZACGL_ITEM_TBCTR-AUFNR.
      FIELD ZACGL_ITEM_TBCTR-ANBWA.
      FIELD ZACGL_ITEM_TBCTR-HKONT.
      FIELD ZACGL_ITEM_TBCTR-PRCTR.
      FIELD ZACGL_ITEM_TBCTR-KONTO_TXT.
      FIELD ZACGL_ITEM_TBCTR-ZZPRESTAC.
      FIELD ZACGL_ITEM_TBCTR-ZZUNID_PRO.
      FIELD ZACGL_ITEM_TBCTR-ZZDESC_EST.
      FIELD ZACGL_ITEM_TBCTR-ZZMOT_EMIS.
      FIELD ZACGL_ITEM_TBCTR-ZZRUT_TERC.
      FIELD ZACGL_ITEM_TBCTR-ZZ_AGENCIA.
      FIELD ZACGL_ITEM_TBCTR-ANLN1.
      FIELD ZACGL_ITEM_TBCTR-ANLN2.
      FIELD ZACGL_ITEM_TBCTR-BSCHL.
      FIELD ZACGL_ITEM_TBCTR-MARKSP.
      MODULE TABLE_MODIFY ON CHAIN-REQUEST.
    ENDCHAIN.

    CHAIN.
      FIELD ZACGL_ITEM_TBCTR-STATE.
      FIELD ZACGL_ITEM_TBCTR-BUKRS.
      FIELD ZACGL_ITEM_TBCTR-SHKZG.
      FIELD ZACGL_ITEM_TBCTR-MWSKZ.
      FIELD ZACGL_ITEM_TBCTR-WRBTR.
      FIELD ZACGL_ITEM_TBCTR-VALUT.
      FIELD ZACGL_ITEM_TBCTR-ZUONR.
      FIELD ZACGL_ITEM_TBCTR-SGTXT.
      FIELD ZACGL_ITEM_TBCTR-KOKRS.
      FIELD ZACGL_ITEM_TBCTR-KOSTL.
      FIELD ZACGL_ITEM_TBCTR-AUFNR.
      FIELD ZACGL_ITEM_TBCTR-ANBWA.
      FIELD ZACGL_ITEM_TBCTR-HKONT.
      FIELD ZACGL_ITEM_TBCTR-PRCTR.
      FIELD ZACGL_ITEM_TBCTR-KONTO_TXT.
      FIELD ZACGL_ITEM_TBCTR-ZZPRESTAC.
      FIELD ZACGL_ITEM_TBCTR-ZZUNID_PRO.
      FIELD ZACGL_ITEM_TBCTR-ZZDESC_EST.
      FIELD ZACGL_ITEM_TBCTR-ZZMOT_EMIS.
      FIELD ZACGL_ITEM_TBCTR-ZZRUT_TERC.
      FIELD ZACGL_ITEM_TBCTR-ZZ_AGENCIA.
      FIELD ZACGL_ITEM_TBCTR-ANLN1.
      FIELD ZACGL_ITEM_TBCTR-ANLN2.
      FIELD ZACGL_ITEM_TBCTR-BSCHL.
      FIELD ZACGL_ITEM_TBCTR-MARKSP.
      MODULE SCHNELLERFASSUNG_0100    ON CHAIN-INPUT.
      MODULE ATRIBUTOS_Z              ON CHAIN-INPUT.
      MODULE VAL_OBJETO_CO            ON CHAIN-INPUT.
      MODULE LIMPIA_OBJET             ON CHAIN-INPUT.

    ENDCHAIN.
    FIELD ZACGL_ITEM_TBCTR-MARKSP
    MODULE TABLE_MARK ON REQUEST.
  ENDLOOP.
  MODULE TABLE_USER_COMMAND.

  MODULE T_001_ACTIVE_TAB_GET.
  MODULE BALANCE_SAL.
  MODULE USER_COMMAND_0100.

PROCESS ON VALUE-REQUEST.
  FIELD ZACGL_ITEM_TBCTR-SGTXT MODULE F4_SGTXT.
  FIELD ZACGL_ITEM_TBCTR-MWSKZ MODULE F4_MWSKZ.
