
PROCESS BEFORE OUTPUT.
* MODULE STATUS_0110.
*
PROCESS AFTER INPUT.
  CHAIN.
    FIELD ZINVFO-HKONT.
    FIELD ZINVFO-BKTXT.
    FIELD ZINVFO-XREF1.
    FIELD ZINVFO-XREF2.
    FIELD ZINVFO-XREF3.
    FIELD ZINVFO-FDLEV.
    MODULE GET_FORM_0050.
   MODULE SET_PANTALLA3.
  ENDCHAIN.

  FIELD ZINVFO-HKONT MODULE REC_ACCOUNT_CHANGE ON REQUEST.
  FIELD ZINVFO-BKTXT MODULE TEXT_MANDATORY_FROM_DOC_TYPE.

PROCESS ON VALUE-REQUEST.
  FIELD ZINVFO-HKONT MODULE HLP_HKONT.
