*&---------------------------------------------------------------------*
*& Report  ZFIMRP001
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT  ZFIMRP001.
TABLES: PAYR,ZREVERSACHEQUE.
TYPE-POOLS: SLIS.

DATA: G_REPID LIKE SY-REPID,
GS_PRINT            TYPE SLIS_PRINT_ALV,
GT_LIST_TOP_OF_PAGE TYPE SLIS_T_LISTHEADER,
GT_EVENTS           TYPE SLIS_T_EVENT,
GT_SORT             TYPE SLIS_T_SORTINFO_ALV,
GS_LAYOUT           TYPE SLIS_LAYOUT_ALV,
GT_FIELDCAT         TYPE SLIS_T_FIELDCAT_ALV,
FIELDCAT_LN LIKE LINE OF GT_FIELDCAT,
COL_POS TYPE I.

DATA LS_TOOLBAR TYPE STB_BUTTON.

DATA : BEGIN OF T_OK OCCURS 0,
      CODUSUARIO TYPE ZCODUSUARIO,
      BUKRS	     TYPE ZREVERSACHEQUE-BUKRS,
      HBKID	     TYPE ZREVERSACHEQUE-HBKID,
      HKTID	     TYPE ZREVERSACHEQUE-HKTID,
      BUDAT	     TYPE ZREVERSACHEQUE-BUDAT,
      ESTREVER   TYPE ZESTREVER,
      VBLNR	     TYPE ZREVERSACHEQUE-VBLNR,
      BELNR	     TYPE ZBELNR,
      BELNRACT   TYPE ZBELNR,
      BUZEI	     TYPE ZREVERSACHEQUE-BUZEI,
      GJAHR	     TYPE ZREVERSACHEQUE-GJAHR,
      FECPROCESO TYPE  ZFECPROCESO,
      HORAPROCESO	TYPE ZUZEIT,
      HKONT	      TYPE ZREVERSACHEQUE-HKONT,
      WRBTR	      TYPE ZREVERSACHEQUE-WRBTR,
      WAERS	      TYPE ZREVERSACHEQUE-WRBTR,
      CHECT	      TYPE ZREVERSACHEQUE-CHECT,
      HKONTD      TYPE ZHKONTD,
      ESTADO      TYPE ZESTADOCH,
      ESTADOC     TYPE ZESTADOCH, " SE AGREGO ESTA NUIEVA COLUMAN EN LA ESTRUCTURA
      BLDAT	      TYPE ZBLDAT,
      LIFNR	      TYPE ZREVERSACHEQUE-LIFNR,
      ZALDT	      TYPE DZALDT,
      ZDOCREV     TYPE ZDOCREV,
    END OF T_OK.


SELECTION-SCREEN: BEGIN OF BLOCK b1 WITH FRAME TITLE text-t01.
 SELECT-OPTIONS:  SBUKRS FOR PAYR-ZBUKR OBLIGATORY . " SOCIEDAD
 SELECT-OPTIONS:  SHBKID FOR PAYR-HBKID OBLIGATORY. "  BANCO
 SELECT-OPTIONS:  SHKTID FOR PAYR-HKTID OBLIGATORY. " CUENTA
 SELECT-OPTIONS:  SCHECT FOR PAYR-CHECT OBLIGATORY . " CHEQUE
SELECTION-SCREEN: END OF BLOCK b1.

START-OF-SELECTION.

PERFORM LLENA_ESTRUCTURA.
PERFORM REPORTE.

INCLUDE ZFIMRP001_INC.

INCLUDE ZFIMRP002_INC.
