
PROCESS BEFORE OUTPUT.
  MODULE SET_SOCIEDAD_FI.
  MODULE SET_DEFAULT_VALUES_0010.

PROCESS AFTER INPUT.

  FIELD ZINVFO-WAERS MODULE GET_WAERS.
  CHAIN.
    FIELD ZINVFO-BLDAT.
    FIELD ZINVFO-BUDAT.
    FIELD ZINVFO-MWSKZ.
    FIELD ZINVFO-XBLNR.
    FIELD ZINVFO-BLART.
    FIELD ZINVFO-WAERS.
    FIELD ZINVFO-WRBTR.
    FIELD ZINVFO-SGTXT.
    FIELD ZINVFO-LIFNR.
    FIELD ZINVFO-ZZMOT_EMIS.
    FIELD ZINVFO-ZZRUT_TERC.
    FIELD ZINVFO-ZZ_AGENCIA.
    MODULE GET_FORM.
  ENDCHAIN.

  CHAIN.
    FIELD  ZINVFO-BLDAT.
    MODULE CHECK_REINDAT.
  ENDCHAIN.
  MODULE READ_COMP_CODE.

  FIELD ZINVFO-BLART MODULE BLART_PRECHECK ON REQUEST.

  MODULE SET_GENERAL_TAX_DATA.

  CHAIN.
    FIELD ZINVFO-BLDAT.
    FIELD ZINVFO-BUDAT.
    MODULE CHECK_DATE.
  ENDCHAIN.

  CHAIN.
    FIELD ZINVFO-BLDAT.
    FIELD ZINVFO-BUDAT.
    MODULE GET_PERIOD.
  ENDCHAIN.

  CHAIN.
    FIELD ZINVFO-XBLNR.
    FIELD ZINVFO-BLART.
    MODULE CHECK_DOCUMENT_TYPE.
    MODULE CHECK_DOCUMENT_NUMBER.
    MODULE OFF_NUMBER_GLOBAL_CHECK.
    MODULE SET_PANTALLA.
  ENDCHAIN.

PROCESS ON VALUE-REQUEST.
  FIELD ZINVFO-MWSKZ MODULE HLP_MWSKZ.
  FIELD ZINVFO-SGTXT MODULE HLP_SGTXT.
  FIELD ZINVFO-BLART MODULE HLP_BLART.
