
PROCESS BEFORE OUTPUT.
  MODULE SET_FEC.
*
PROCESS AFTER INPUT.
  CHAIN.
    FIELD ZINVFO-ZLSCH.
    FIELD ZINVFO-KIDNO.
    FIELD ZINVFO-ZFBDT.
    FIELD ZINVFO-ZLSCH.
    FIELD ZINVFO-ZLSPR.
    FIELD ZINVFO-ZTERM.
    FIELD ZINVFO-ZBD1T.
    FIELD ZINVFO-REBZG.
    FIELD ZINVFO-REBZJ.
    FIELD ZINVFO-REBZZ.
    FIELD ZINVFO-KIDNO.
    FIELD ZINVFO-HBKID.
    FIELD ZINVFO-HKTID.
    MODULE GET_FORM_0020.
  ENDCHAIN.


  FIELD ZINVFO-ZLSCH MODULE CHECK_PAYMENT_METHOD ON INPUT.
  FIELD ZINVFO-KIDNO MODULE CHECK_PAYMENT_REFERENCE ON INPUT.

  CHAIN.
    FIELD ZINVFO-ZFBDT.
    FIELD ZINVFO-ZLSCH.
    FIELD ZINVFO-ZLSPR.
    FIELD ZINVFO-ZTERM.
    FIELD ZINVFO-ZBD1T.
    FIELD ZINVFO-REBZG.
    FIELD ZINVFO-REBZJ.
    FIELD ZINVFO-REBZZ.
    FIELD ZINVFO-KIDNO.
    FIELD ZINVFO-NETDT.
    MODULE INVOICE_REFERENCE.
    MODULE PAYMENT_CONDITIONS_PROCESS.
    MODULE RESET_CASH_FORECAST ON CHAIN-REQUEST.
  ENDCHAIN.

  CHAIN.
    FIELD ZINVFO-HBKID MODULE HOUSEBANK             ON INPUT.
    FIELD ZINVFO-HKTID.
    MODULE SET_PANTALLA2.
  ENDCHAIN.
  FIELD ZINVFO-KIDNO MODULE CHECK_PAYMENT_REFERENCE ON INPUT.
  MODULE CHECK_DOCUMENT_TYPE.
  MODULE TEXT_MANDATORY_FROM_DOC_TYPE.

PROCESS ON VALUE-REQUEST.
  FIELD ZINVFO-ZTERM MODULE HLP_ZTERM.
  FIELD ZINVFO-EMPFB MODULE HLP_EMPFB.
