PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFIPG002_DET CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFIPG002_DET-BUKRS .
    FIELD ZFIPG002_DET-NPROCESO .
    FIELD ZFIPG002_DET-LAUFI .
    FIELD ZFIPG002_DET-LAUFD .
    FIELD ZFIPG002_DET-HBKID .
    FIELD ZFIPG002_DET-ZLSCH .
    FIELD ZFIPG002_DET-XZZMOT_EMIS .
    FIELD ZFIPG002_DET-ZFBDT .
    FIELD ZFIPG002_DET-NCHEQU_S .
    FIELD ZFIPG002_DET-ESTADO .
    FIELD ZFIPG002_DET-IMPR_USUARIO .
    FIELD ZFIPG002_DET-IMPR_FECHA .
    FIELD ZFIPG002_DET-IMPR_HORA .
    FIELD ZFIPG002_DET-NDOCU .
    FIELD ZFIPG002_DET-MONTOP .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFIPG002_DET-BUKRS .
    FIELD ZFIPG002_DET-NPROCESO .
    FIELD ZFIPG002_DET-LAUFI .
    FIELD ZFIPG002_DET-LAUFD .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
