*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFIPG002_DETTOP.                  " Global Data
  INCLUDE LZFIPG002_DETUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFIPG002_DETF00                        . " subprograms
  INCLUDE LZFIPG002_DETI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFIPG002_DETF...                  " Subprograms
* INCLUDE LZFIPG002_DETO...                  " PBO-Modules
* INCLUDE LZFIPG002_DETI...                  " PAI-Modules
