PROCESS BEFORE OUTPUT.

  MODULE STATUS_0100.

  MODULE LLENO-GRILLA.

  LOOP WITH CONTROL TABLA.

    MODULE FILL_TABLE_CONTROL.
  ENDLOOP.

PROCESS AFTER INPUT.

  module user_command_exit_0100 at exit-command.

  LOOP WITH CONTROL TABLA.
    CHAIN.
      FIELD ZFIPG201_EST-SEL.

      MODULE VALIDA-GRILLA.
    ENDCHAIN.

  ENDLOOP.

  MODULE USER_COMMAND_0100.
