FUNCTION-POOL ZFIRFC001.                    "MESSAGE-ID ..

* Definicion de varibles Globales.
DATA: T_ERROR TYPE SY-SUBRC.

* Tabla de interna que registrara los errores de validacion de datos en las estructuras.
DATA: BEGIN OF TI_ERROR_CAB OCCURS 0.
        INCLUDE STRUCTURE ZCABECERA.
DATA: END OF TI_ERROR_CAB.
DATA: BEGIN OF TI_ERROR_DET OCCURS 0.
        INCLUDE STRUCTURE ZDETALLE.
DATA: END OF TI_ERROR_DET.
* Tabla de interna que registrara los documentos a contabiliozar.
DATA: BEGIN OF TI_CONT_CAB OCCURS 0.
DATA: TIPO(2) TYPE C.
        INCLUDE STRUCTURE ZCABECERA.
DATA: END OF TI_CONT_CAB.
DATA: BEGIN OF TI_CONT_DET OCCURS 0.
        INCLUDE STRUCTURE ZDETALLE.
DATA: TIPO(2) TYPE C.
DATA: END OF TI_CONT_DET.
DATA: TI_CONT_DET_PASO LIKE TI_CONT_DET.
DATA:
      DOCUMENTHEADER LIKE BAPIACHE09 OCCURS 0 WITH HEADER LINE,
      CUSTOMERCPD LIKE BAPIACPA09,
      CONTRACTHEADER LIKE BAPIACCAHD,
      ACCOUNTGL LIKE BAPIACGL09 OCCURS 0  WITH HEADER LINE,
      ACCOUNTRECEIVABLE LIKE BAPIACAR09 OCCURS 0 WITH HEADER LINE,
      ACCOUNTPAYABLE LIKE BAPIACAP09 OCCURS 0  WITH HEADER LINE,
      ACCOUNTTAX LIKE BAPIACTX09 OCCURS 0 WITH HEADER LINE,
      CURRENCYAMOUNT LIKE BAPIACCR09 OCCURS 0 WITH HEADER LINE,
      CRITERIA LIKE BAPIACKEC9 OCCURS 0,
      VALUEFIELD LIKE BAPIACKEV9 OCCURS 0,
      REALESTATE LIKE BAPIACRE09 OCCURS 0,
      EXTENSION1 LIKE BAPIACEXTC OCCURS  0 WITH HEADER LINE,
      EXTENSION2 LIKE BAPIPAREX OCCURS 0,
      RETURN LIKE BAPIRET2 OCCURS 0  WITH HEADER LINE,
       RETURN2 LIKE BAPIRET2 OCCURS 0  WITH HEADER LINE,
      PAYMENTCARD LIKE BAPIACPC09 OCCURS 0,
      CONTRACTITEM LIKE BAPIACCAIT OCCURS 0,
      WITHHOLDINGTAX LIKE BAPIACWT09 OCCURS 0,
      ACCOUNTWT LIKE BAPIACWT09 OCCURS 0  WITH HEADER LINE,
      T_MWDAT LIKE RTAX1U15 OCCURS 0  WITH HEADER LINE.
