*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFIRMADIGITALTOP.                 " Global Data
  INCLUDE LZFIRMADIGITALUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFIRMADIGITALF00                       . " subprograms
  INCLUDE LZFIRMADIGITALI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFIRMADIGITALF...                 " Subprograms
* INCLUDE LZFIRMADIGITALO...                 " PBO-Modules
* INCLUDE LZFIRMADIGITALI...                 " PAI-Modules
