PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZFIRFC03-BUKRS .
    FIELD ZFIRFC03-GRUPO .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZFIRFC03-BUKRS .
    FIELD ZFIRFC03-GRUPO .
  module detail_pai.
 endchain.
