FUNCTION ZBAPI_CREDITOR_GETDETAIL.
*"----------------------------------------------------------------------
*"*"Interfase local
*"  IMPORTING
*"     VALUE(CREDITORID) LIKE  BAPI1008-VENDOR
*"     VALUE(COMPANYCODE) LIKE  BAPI1008-COMP_CODE OPTIONAL
*"  EXPORTING
*"     VALUE(CREDITOR_GENERAL_DETAIL) LIKE  LFA1 STRUCTURE  LFA1
*"     VALUE(CREDITOR_COMPANY_DETAIL) LIKE  LFB1 STRUCTURE  LFB1
*"     VALUE(RETURN) LIKE  BAPIRETURN STRUCTURE  BAPIRETURN
*"  TABLES
*"      CREDITOR_BANK_DETAIL STRUCTURE  LFBK OPTIONAL
*"      LFBW STRUCTURE  LFBW OPTIONAL
*"      LFZA STRUCTURE  LFZA OPTIONAL
*"----------------------------------------------------------------------

  CLEAR:   LM_GENERAL_DETAIL, LM_COMPANY_DETAIL.
  CLEAR:   RETURN, LM_BANK_DETAIL.
  REFRESH: LM_BANK_DETAIL.
  PERFORM AUTHORITYCHECK_F_LFA1_APP USING 'F' RETURN.
  CHECK RETURN IS INITIAL.
  SELECT SINGLE * INTO CORRESPONDING FIELDS OF LM_GENERAL_DETAIL  FROM LFA1 WHERE LIFNR = CREDITORID.
  IF SY-SUBRC NE 0.
    CLEAR MESSAGE.
    MESSAGE = 'EFN521'.
    MESSAGE-MSGTY = 'E'.
    MESSAGE-MSGID = 'FN'.
    MESSAGE-MSGNO = '521'.
    MESSAGE-MSGV1 = CREDITORID.
    PERFORM SET_RETURN_MESSAGE USING    MESSAGE
                               CHANGING RETURN.
    IF 1 = 2.
      MESSAGE E521(FN) WITH CREDITORID.
    ENDIF.
  ENDIF.
  CHECK RETURN IS INITIAL.
  PERFORM AUTHORITYCHECK_F_LFA1_GRP USING LFA1-KTOKK RETURN.
  CHECK RETURN IS INITIAL.
  PERFORM AUTHORITYCHECK_F_LFA1_GEN USING RETURN.
  CHECK RETURN IS INITIAL.
  PERFORM AUTHORITYCHECK_F_LFA1_BEK USING LFA1-BEGRU RETURN.

  CHECK RETURN IS INITIAL.


  IF NOT COMPANYCODE IS INITIAL.
    PERFORM AUTHORITYCHECK_F_LFA1_BUK USING COMPANYCODE RETURN.
    CHECK RETURN IS INITIAL.
    SELECT SINGLE * INTO CORRESPONDING FIELDS OF LM_COMPANY_DETAIL FROM LFB1 WHERE LIFNR = CREDITORID
                                AND BUKRS = COMPANYCODE.
    IF SY-SUBRC NE 0.
      CLEAR MESSAGE.
      MESSAGE-MSGTY = 'E'.
      MESSAGE-MSGID = 'FN'.
      MESSAGE-MSGNO = '522'.
      MESSAGE-MSGV1 = CREDITORID.
      MESSAGE-MSGV2 = COMPANYCODE.
      PERFORM SET_RETURN_MESSAGE USING    MESSAGE
                                 CHANGING RETURN.
      IF 1 = 2.
        MESSAGE E522(FN) WITH CREDITORID COMPANYCODE.
      ENDIF.
    ELSE.
      PERFORM AUTHORITYCHECK_F_LFA1_BEK USING LFB1-BEGRU RETURN.
    ENDIF.
  ENDIF.



  SELECT * FROM  LFBW
           INTO  CORRESPONDING FIELDS OF LFBW
           WHERE LIFNR = CREDITORID
    AND BUKRS = COMPANYCODE.
    APPEND LFBW.
  ENDSELECT.


  SELECT * FROM  LFZA
           INTO  CORRESPONDING FIELDS OF LFZA
           WHERE LIFNR = CREDITORID.
    APPEND LFZA.
  ENDSELECT.


  CHECK RETURN IS INITIAL.
  SELECT * FROM  LFBK
           INTO  CORRESPONDING FIELDS OF LM_BANK_DETAIL
           WHERE LIFNR = CREDITORID.
    APPEND LM_BANK_DETAIL.
  ENDSELECT.
  IF SY-SUBRC NE 0.
    CLEAR MESSAGE.
    MESSAGE-MSGTY = 'I'.
    MESSAGE-MSGID = 'FN'.
    MESSAGE-MSGNO = '524'.
    MESSAGE-MSGV1 = CREDITORID.
    PERFORM SET_RETURN_MESSAGE USING    MESSAGE
                               CHANGING RETURN.
    IF 1 = 2.
      MESSAGE I524(FN) WITH CREDITORID.
    ENDIF.
  ENDIF.

  MOVE LM_GENERAL_DETAIL  TO CREDITOR_GENERAL_DETAIL.
  MOVE LM_COMPANY_DETAIL  TO CREDITOR_COMPANY_DETAIL.
  CREDITOR_BANK_DETAIL[]  = LM_BANK_DETAIL[].
  LFBW[] = LFBW[].
  LFZA[] = LFZA[].
ENDFUNCTION.
