*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZV_ZFITR004.....................................*
FORM GET_DATA_ZV_ZFITR004.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZFITR004 WHERE
(VIM_WHERETAB) .
    CLEAR ZV_ZFITR004 .
ZV_ZFITR004-MANDT =
ZFITR004-MANDT .
ZV_ZFITR004-BUKRS =
ZFITR004-BUKRS .
ZV_ZFITR004-FECHA_REM =
ZFITR004-FECHA_REM .
ZV_ZFITR004-SECUENCIA =
ZFITR004-SECUENCIA .
ZV_ZFITR004-BELNR =
ZFITR004-BELNR .
ZV_ZFITR004-GJAHR =
ZFITR004-GJAHR .
ZV_ZFITR004-XBLNR =
ZFITR004-XBLNR .
ZV_ZFITR004-LIFNR =
ZFITR004-LIFNR .
ZV_ZFITR004-ESTADO =
ZFITR004-ESTADO .
<VIM_TOTAL_STRUC> = ZV_ZFITR004.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZV_ZFITR004 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZV_ZFITR004.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZV_ZFITR004-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZFITR004 WHERE
  BUKRS = ZV_ZFITR004-BUKRS AND
  FECHA_REM = ZV_ZFITR004-FECHA_REM AND
  SECUENCIA = ZV_ZFITR004-SECUENCIA AND
  BELNR = ZV_ZFITR004-BELNR AND
  GJAHR = ZV_ZFITR004-GJAHR AND
  XBLNR = ZV_ZFITR004-XBLNR AND
  LIFNR = ZV_ZFITR004-LIFNR .
    IF SY-SUBRC = 0.
    DELETE ZFITR004 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZFITR004 WHERE
  BUKRS = ZV_ZFITR004-BUKRS AND
  FECHA_REM = ZV_ZFITR004-FECHA_REM AND
  SECUENCIA = ZV_ZFITR004-SECUENCIA AND
  BELNR = ZV_ZFITR004-BELNR AND
  GJAHR = ZV_ZFITR004-GJAHR AND
  XBLNR = ZV_ZFITR004-XBLNR AND
  LIFNR = ZV_ZFITR004-LIFNR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZFITR004.
    ENDIF.
ZFITR004-MANDT =
ZV_ZFITR004-MANDT .
ZFITR004-BUKRS =
ZV_ZFITR004-BUKRS .
ZFITR004-FECHA_REM =
ZV_ZFITR004-FECHA_REM .
ZFITR004-SECUENCIA =
ZV_ZFITR004-SECUENCIA .
ZFITR004-BELNR =
ZV_ZFITR004-BELNR .
ZFITR004-GJAHR =
ZV_ZFITR004-GJAHR .
ZFITR004-XBLNR =
ZV_ZFITR004-XBLNR .
ZFITR004-LIFNR =
ZV_ZFITR004-LIFNR .
ZFITR004-ESTADO =
ZV_ZFITR004-ESTADO .
    IF SY-SUBRC = 0.
    UPDATE ZFITR004 ##WARN_OK.
    ELSE.
    INSERT ZFITR004 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZV_ZFITR004-UPD_FLAG,
STATUS_ZV_ZFITR004-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZV_ZFITR004.
  SELECT SINGLE * FROM ZFITR004 WHERE
BUKRS = ZV_ZFITR004-BUKRS AND
FECHA_REM = ZV_ZFITR004-FECHA_REM AND
SECUENCIA = ZV_ZFITR004-SECUENCIA AND
BELNR = ZV_ZFITR004-BELNR AND
GJAHR = ZV_ZFITR004-GJAHR AND
XBLNR = ZV_ZFITR004-XBLNR AND
LIFNR = ZV_ZFITR004-LIFNR .
ZV_ZFITR004-MANDT =
ZFITR004-MANDT .
ZV_ZFITR004-BUKRS =
ZFITR004-BUKRS .
ZV_ZFITR004-FECHA_REM =
ZFITR004-FECHA_REM .
ZV_ZFITR004-SECUENCIA =
ZFITR004-SECUENCIA .
ZV_ZFITR004-BELNR =
ZFITR004-BELNR .
ZV_ZFITR004-GJAHR =
ZFITR004-GJAHR .
ZV_ZFITR004-XBLNR =
ZFITR004-XBLNR .
ZV_ZFITR004-LIFNR =
ZFITR004-LIFNR .
ZV_ZFITR004-ESTADO =
ZFITR004-ESTADO .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZV_ZFITR004 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZV_ZFITR004-BUKRS TO
ZFITR004-BUKRS .
MOVE ZV_ZFITR004-FECHA_REM TO
ZFITR004-FECHA_REM .
MOVE ZV_ZFITR004-SECUENCIA TO
ZFITR004-SECUENCIA .
MOVE ZV_ZFITR004-BELNR TO
ZFITR004-BELNR .
MOVE ZV_ZFITR004-GJAHR TO
ZFITR004-GJAHR .
MOVE ZV_ZFITR004-XBLNR TO
ZFITR004-XBLNR .
MOVE ZV_ZFITR004-LIFNR TO
ZFITR004-LIFNR .
MOVE ZV_ZFITR004-MANDT TO
ZFITR004-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZFITR004'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZFITR004 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZFITR004'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
