*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFITR020_T05TOP.                  " Global Data
  INCLUDE LZFITR020_T05UXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFITR020_T05F00                        . " subprograms
  INCLUDE LZFITR020_T05I00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFITR020_T05F...                  " Subprograms
* INCLUDE LZFITR020_T05O...                  " PBO-Modules
* INCLUDE LZFITR020_T05I...                  " PAI-Modules
