PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFITR004 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFITR004-BUKRS .
    FIELD ZFITR004-FECHA_REM .
    FIELD ZFITR004-SECUENCIA .
    FIELD ZFITR004-BELNR .
    FIELD ZFITR004-GJAHR .
    FIELD ZFITR004-XBLNR .
    FIELD ZFITR004-LIFNR .
    FIELD ZFITR004-ESTADO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFITR004-BUKRS .
    FIELD ZFITR004-FECHA_REM .
    FIELD ZFITR004-SECUENCIA .
    FIELD ZFITR004-BELNR .
    FIELD ZFITR004-GJAHR .
    FIELD ZFITR004-XBLNR .
    FIELD ZFITR004-LIFNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
