PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFITR005 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFITR005-BUKRS .
    FIELD ZFITR005-HBKID .
    FIELD ZFITR005-ZMOTIV .
    FIELD ZFITR005-ZDESC .
    FIELD ZFITR005-ZFORMAT .
    FIELD ZFITR005-ZFLAG .
    FIELD ZFITR005-ZCTACTE .
    FIELD ZFITR005-ZCTAVTA .
    FIELD ZFITR005-ZCODSERV .
    FIELD ZFITR005-ZCLAVEMIS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFITR005-BUKRS .
    FIELD ZFITR005-HBKID .
    FIELD ZFITR005-ZMOTIV .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
