*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFITR009TOP.                      " Global Data
  INCLUDE LZFITR009UXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFITR009F00                            . " subprograms
  INCLUDE LZFITR009I00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFITR009F...                      " Subprograms
* INCLUDE LZFITR009O...                      " PBO-Modules
* INCLUDE LZFITR009I...                      " PAI-Modules

INCLUDE LZFITR009I01.

INCLUDE LZFITR009I02.
