*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFITR006TOP.                      " Global Data
  INCLUDE LZFITR006UXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFITR006F00                            . " subprograms
  INCLUDE LZFITR006I00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFITR006F...                      " Subprograms
* INCLUDE LZFITR006O...                      " PBO-Modules
* INCLUDE LZFITR006I...                      " PAI-Modules
