PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZFITR005-BUKRS .
    FIELD ZFITR005-HBKID .
    FIELD ZFITR005-ZMOTIV .
    FIELD ZFITR005-ZDESC .
    FIELD ZFITR005-ZFORMAT .
    FIELD ZFITR005-ZFLAG .
    FIELD ZFITR005-ZCTACTE .
    FIELD ZFITR005-ZCTAVTA .
    FIELD ZFITR005-ZCODSERV .
    FIELD ZFITR005-ZCLAVEMIS .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZFITR005-BUKRS .
    FIELD ZFITR005-HBKID .
    FIELD ZFITR005-ZMOTIV .
  module detail_pai.
 endchain.
