PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZV_ZFITR004 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
 MODULE FILL_SUBSTFLDS.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZV_ZFITR004-SECUENCIA .
    FIELD ZV_ZFITR004-BELNR .
    FIELD ZV_ZFITR004-GJAHR .
    FIELD ZV_ZFITR004-XBLNR .
    FIELD ZV_ZFITR004-LIFNR .
    FIELD ZV_ZFITR004-ESTADO .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZV_ZFITR004-SECUENCIA .
    FIELD ZV_ZFITR004-BELNR .
    FIELD ZV_ZFITR004-GJAHR .
    FIELD ZV_ZFITR004-XBLNR .
    FIELD ZV_ZFITR004-LIFNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
