PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFITR020_T05 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFITR020_T05-BUKRS .
    FIELD ZFITR020_T05-HBKID .
    FIELD ZFITR020_T05-HKTID .
    FIELD ZFITR020_T05-CTA_SALDO .
    FIELD ZFITR020_T05-CTA_DEPOS .
    FIELD ZFITR020_T05-CTA_CHEQS .
    FIELD ZFITR020_T05-CTA_CARGOS .
    FIELD ZFITR020_T05-CTA_ABONOS .
    FIELD ZFITR020_T05-CTA_TRANS .
    FIELD ZFITR020_T05-CTA_CDCO_F .
    FIELD ZFITR020_T05-CTA_CDCO_E .
    FIELD ZFITR020_T05-CTA_CDCO_F2 .
    FIELD ZFITR020_T05-REVALIDAD .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFITR020_T05-BUKRS .
    FIELD ZFITR020_T05-HBKID .
    FIELD ZFITR020_T05-HKTID .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
