PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFITR030 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFITR030-BUKRS .
    FIELD ZFITR030-ZCOD_PLANILLA .
    FIELD ZFITR030-ZCONCEPTO .
    FIELD ZFITR030-SENTIDO .
    FIELD ZFITR030-HKONT .
    FIELD ZFITR030-SGTXT .
    FIELD ZFITR030-ZVALOR .
    FIELD ZFITR030-ZRUTACREEDOR .
    FIELD ZFITR030-ZAUX3 .
    FIELD ZFITR030-ZLSCH .
    FIELD ZFITR030-ZZ_AGENCIA .
    FIELD ZFITR030-ZZMOT_EMIS .
    FIELD ZFITR030-HBKID .
    FIELD ZFITR030-ZTERM .
    FIELD ZFITR030-ZUONR .
    FIELD ZFITR030-FECHA_PAGO .
    FIELD ZFITR030-ZZRUT_TERC .
    FIELD ZFITR030-ZZDESC_EST .
    FIELD ZFITR030-ZTIPO_CONT .
    FIELD ZFITR030-KOSTL .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFITR030-BUKRS .
    FIELD ZFITR030-ZCOD_PLANILLA .
    FIELD ZFITR030-ZCONCEPTO .
    FIELD ZFITR030-SENTIDO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
