PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZFITR002-BUKRS .
    FIELD ZFITR002-ZMODSER .
    FIELD ZFITR002-ZRUTPRO .
    FIELD ZFITR002-ZDRRPOR .
    FIELD ZFITR002-ZUNIDAD .
    FIELD ZFITR002-ZNOMBRE .
    FIELD ZFITR002-ZMEDAVI .
    FIELD ZFITR002-ZDIRAVI .
    FIELD ZFITR002-ZCODCOM .
    FIELD ZFITR002-ZFORPAG .
    FIELD ZFITR002-ZCODBCO .
    FIELD ZFITR002-ZCTACTE .
    FIELD ZFITR002-ZSUCCTA .
    FIELD ZFITR002-ZTIPDOC .
    FIELD ZFITR002-ZNUMDOC .
    FIELD ZFITR002-ZDOCREL .
    FIELD ZFITR002-ZMONINF .
    FIELD ZFITR002-ZMONPAG .
    FIELD ZFITR002-ZESTPAG .
    FIELD ZFITR002-ZFECVCT .
    FIELD ZFITR002-ZFECPAG .
    FIELD ZFITR002-ZGLOSA .
    FIELD ZFITR002-ZRUTRE1 .
    FIELD ZFITR002-ZDVRRE1 .
    FIELD ZFITR002-ZAPPRE1 .
    FIELD ZFITR002-ZAPMRE1 .
    FIELD ZFITR002-ZNOMRE1 .
    FIELD ZFITR002-ZRUTRE2 .
    FIELD ZFITR002-ZDVRRE2 .
    FIELD ZFITR002-ZAPPRE2 .
    FIELD ZFITR002-ZAPMRE2 .
    FIELD ZFITR002-ZNOMRE2 .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZFITR002-BUKRS .
  module detail_pai.
 endchain.
