*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFITR_TESDOCPAGOTOP.              " Global Data
  INCLUDE LZFITR_TESDOCPAGOUXX.              " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFITR_TESDOCPAGOF00                    . " subprograms
  INCLUDE LZFITR_TESDOCPAGOI00                    . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFITR_TESDOCPAGOF...              " Subprograms
* INCLUDE LZFITR_TESDOCPAGOO...              " PBO-Modules
* INCLUDE LZFITR_TESDOCPAGOI...              " PAI-Modules
