PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFITR026 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFITR026-BUKRS .
    FIELD ZFITR026-BANKS .
    FIELD ZFITR026-BANKL .
    FIELD ZFITR026-RUTN .
    FIELD ZFITR026-RUTD .
    FIELD ZFITR026-APELLIDOP .
    FIELD ZFITR026-APELLIDOM .
    FIELD ZFITR026-NOMBRES .
    FIELD ZFITR026-RUTN2 .
    FIELD ZFITR026-RUTD2 .
    FIELD ZFITR026-APELLIDOP2 .
    FIELD ZFITR026-APELLIDOM2 .
    FIELD ZFITR026-NOMBRES2 .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFITR026-BUKRS .
    FIELD ZFITR026-BANKS .
    FIELD ZFITR026-BANKL .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
