PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFITR_TESDOCPAGO CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFITR_TESDOCPAGO-BUKRS .
    FIELD ZFITR_TESDOCPAGO-LAUFD .
    FIELD ZFITR_TESDOCPAGO-LAUFI .
    FIELD ZFITR_TESDOCPAGO-STATUS .
    FIELD ZFITR_TESDOCPAGO-USNAM .
    FIELD ZFITR_TESDOCPAGO-DATE_ACT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFITR_TESDOCPAGO-BUKRS .
    FIELD ZFITR_TESDOCPAGO-LAUFD .
    FIELD ZFITR_TESDOCPAGO-LAUFI .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
