*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFITR020_T02TOP.                  " Global Data
  INCLUDE LZFITR020_T02UXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFITR020_T02F00                        . " subprograms
  INCLUDE LZFITR020_T02I00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFITR020_T02F...                  " Subprograms
* INCLUDE LZFITR020_T02O...                  " PBO-Modules
* INCLUDE LZFITR020_T02I...                  " PAI-Modules
