PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFITR009 CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFITR009-USNAM .
    FIELD ZFITR009-DATAB .
    FIELD ZFITR009-DATBI .
    FIELD ZFITR009-UBNAME .
    FIELD ZFITR009-DATUM .
    FIELD ZFITR009-UZEIT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFITR009-USNAM .
    FIELD ZFITR009-DATAB .
    FIELD ZFITR009-DATBI .
        MODULE datos.
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
  MODULE control.
 MODULE LISTE_AFTER_LOOP.
