*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFOLIO_PAGOBANCOTOP.              " Global Data
  INCLUDE LZFOLIO_PAGOBANCOUXX.              " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFOLIO_PAGOBANCOF00                    . " subprograms
  INCLUDE LZFOLIO_PAGOBANCOI00                    . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFOLIO_PAGOBANCOF...              " Subprograms
* INCLUDE LZFOLIO_PAGOBANCOO...              " PBO-Modules
* INCLUDE LZFOLIO_PAGOBANCOI...              " PAI-Modules
