*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZFOLIOSNULOSTOP.                  " Global Data
  INCLUDE LZFOLIOSNULOSUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZFOLIOSNULOSF00                        . " subprograms
  INCLUDE LZFOLIOSNULOSI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZFOLIOSNULOSF...                  " Subprograms
* INCLUDE LZFOLIOSNULOSO...                  " PBO-Modules
* INCLUDE LZFOLIOSNULOSI...                  " PAI-Modules
