PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZFOLIOSNULOS CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZFOLIOSNULOS-BUKRS .
    FIELD ZFOLIOSNULOS-GJAHR .
    FIELD ZFOLIOSNULOS-MONAT .
    FIELD ZFOLIOSNULOS-XBLNR .
    FIELD ZFOLIOSNULOS-BLART .
    FIELD ZFOLIOSNULOS-FECANU .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZFOLIOSNULOS-BUKRS .
    FIELD ZFOLIOSNULOS-GJAHR .
    FIELD ZFOLIOSNULOS-MONAT .
    FIELD ZFOLIOSNULOS-XBLNR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
