FUNCTION ZVALANUL.
*"----------------------------------------------------------------------
*"*"Interfase local
*"  IMPORTING
*"     VALUE(ZBUKRS) TYPE  BUKRS
*"     VALUE(ZBELNR) TYPE  /BEV3/CHTXT10
*"     VALUE(ZGJAHR) TYPE  GJAHR
*"  EXPORTING
*"     VALUE(ESTBLG) TYPE  STBLG
*"     VALUE(EMENSAJE) TYPE  KLTXT
*"----------------------------------------------------------------------

TYPES ty_numero TYPE p LENGTH 4 DECIMALS 2.
DATA: resultado TYPE ty_numero,
ref_exc TYPE REF TO cx_root,
msg TYPE string.

*TRY.
CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
 EXPORTING
  INPUT = ZBELNR
 IMPORTING
  OUTPUT = ZBELNR.
*CATCH CX_SY_CONVERSION_NO_NUMBER.
*EMENSAJE := 'DOCUMENTO NO EXISTE'.
*CATCH CX_SY_CONVERSION_DATA_LOSS.
*EMENSAJE := 'DOCUMENTO NO EXISTE'.
*CATCH CX_ST_DESERIALIZATION_ERROR.
*EMENSAJE :='DOCUMENTO NO EXISTE'.
*ENDTRY.

SELECT SINGLE BKPF~STBLG INTO ESTBLG
FROM BKPF
WHERE BKPF~BUKRS  EQ ZBUKRS
AND   BKPF~BELNR  EQ ZBELNR
AND   BKPF~GJAHR  EQ ZGJAHR.




   IF sy-subrc <> 0.
      ESTBLG :=''.
      EMENSAJE :='DOCUMENTO NO EXISTE'.
    ELSE.
     IF ESTBLG IS INITIAL.
      ESTBLG :=  ''.
      EMENSAJE :='DOCUMENTO NO NULO'.
     ELSE.
      EMENSAJE :='DOCUMENTO NULO'.
     ENDIF.
    ENDIF.



ENDFUNCTION.
