PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZVBWROOSFIELD CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZVBWROOSFIELD-OLTPSOURCE .
    FIELD ZVBWROOSFIELD-OBJVERS .
    FIELD ZVBWROOSFIELD-FIELD .
    FIELD ZVBWROOSFIELD-SELECTION .
    FIELD ZVBWROOSFIELD-UNIFIELDNM .
    FIELD ZVBWROOSFIELD-STORNO .
    FIELD ZVBWROOSFIELD-F4TYPE .
    FIELD ZVBWROOSFIELD-F4EXTRAKT .
    FIELD ZVBWROOSFIELD-NOTEXREL .
    FIELD ZVBWROOSFIELD-KEYFLAG_DS .
    FIELD ZVBWROOSFIELD-SELOPTS .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZVBWROOSFIELD-OLTPSOURCE .
    FIELD ZVBWROOSFIELD-OBJVERS .
    FIELD ZVBWROOSFIELD-FIELD .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
