*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZGFOPEBCOTOP.                     " Global Data
  INCLUDE LZGFOPEBCOUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZGFOPEBCOF00                           . " subprograms
  INCLUDE LZGFOPEBCOI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZGFOPEBCOF...                     " Subprograms
* INCLUDE LZGFOPEBCOO...                     " PBO-Modules
* INCLUDE LZGFOPEBCOI...                     " PAI-Modules
