*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZGRP_LIB_LEGTOP.                  " Global Data
  INCLUDE LZGRP_LIB_LEGUXX.                  " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZGRP_LIB_LEGF00                        . " subprograms
  INCLUDE LZGRP_LIB_LEGI00                        . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZGRP_LIB_LEGF...                  " Subprograms
* INCLUDE LZGRP_LIB_LEGO...                  " PBO-Modules
* INCLUDE LZGRP_LIB_LEGI...                  " PAI-Modules
