PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZDATSOCELEC CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZDATSOCELEC-BUKRS .
    FIELD ZDATSOCELEC-RUT_CONTR .
    FIELD ZDATSOCELEC-RUT_ENVIA .
    FIELD ZDATSOCELEC-FEC_RES .
    FIELD ZDATSOCELEC-NUM_RES .
    FIELD ZDATSOCELEC-TIP_OPERA .
    FIELD ZDATSOCELEC-TIP_LIB .
    FIELD ZDATSOCELEC-TIP_ENV .
    FIELD ZDATSOCELEC-FOLIO_NOT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZDATSOCELEC-BUKRS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
