*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZGRP_MNTTOP.                      " Global Data
  INCLUDE LZGRP_MNTUXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZGRP_MNTF00                            . " subprograms
  INCLUDE LZGRP_MNTI00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZGRP_MNTF...                      " Subprograms
* INCLUDE LZGRP_MNTO...                      " PBO-Modules
* INCLUDE LZGRP_MNTI...                      " PAI-Modules
