FUNCTION-POOL ZINT_HELP.                    "MESSAGE-ID ..

DATA BINARY      TYPE FLAG.
DATA CLIENT      TYPE REF TO IF_HTTP_CLIENT.
DATA COM_ACC     TYPE STRING.
DATA CONTENT     TYPE STRING.
DATA ERRORTEXT   TYPE STRING.
DATA FOLIO       TYPE STRING.
DATA HOST        TYPE STRING.
DATA HTTP_RC     TYPE SYSUBRC.
DATA OFF         TYPE I.
DATA PATH        TYPE STRING.
DATA PORT        TYPE STRING.
DATA RC          TYPE SYSUBRC.
DATA RESP_ACEPTA TYPE STRING.
DATA SCHEME      TYPE I.
DATA STR_DAT     TYPE STRING.
DATA SUBRC       TYPE I.
DATA TIMEOUT     TYPE I.
DATA TMP         TYPE STRING.
DATA XCONTENT    TYPE XSTRING.
