FUNCTION ZWS_MOD_CONTRATOS.
*"----------------------------------------------------------------------
*"*"Interfase local
*"  IMPORTING
*"     VALUE(STR_CONTRATO) TYPE  ZSD_CONTRATO
*"  TABLES
*"      RETURN STRUCTURE  BAPIRET2
*"----------------------------------------------------------------------
  DATA TMP_FEC  TYPE C LENGTH 10.

  SELECT SINGLE * FROM ADRC WHERE SORT2 EQ STR_CONTRATO-SORT2.
  IF SY-SUBRC = 0.
    SELECT SINGLE * FROM KNA1 WHERE ADRNR EQ ADRC-ADDRNUMBER.
  ENDIF.
  IF NOT KNA1-KUNNR IS INITIAL.
    PERFORM BDC_DYNPRO USING 'SAPMF02D'        '0101'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'      'RF02D-D0310'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'      '/00'.
    PERFORM BDC_FIELD  USING 'RF02D-KUNNR'     KNA1-KUNNR.
    PERFORM BDC_FIELD  USING 'RF02D-VKORG'     STR_CONTRATO-VKORG.
    PERFORM BDC_FIELD  USING 'RF02D-VTWEG'     STR_CONTRATO-VTWEG.
    PERFORM BDC_FIELD  USING 'RF02D-SPART'     STR_CONTRATO-SPART.
    PERFORM BDC_FIELD  USING 'RF02D-D0110'     'X'.

    PERFORM BDC_DYNPRO USING 'SAPMF02D'        '0110'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'      '=KLAS'.
    PERFORM BDC_FIELD  USING 'KNA1-NAME1'      STR_CONTRATO-NAME1.
    PERFORM BDC_FIELD  USING 'KNA1-LAND1'      'CL'.

    PERFORM BDC_DYNPRO USING 'SAPLCLCA'        '0602'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'      'RMCLF-KLART'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'      '=ENTE'.
    PERFORM BDC_FIELD  USING 'RMCLF-KLART'     '011'.

    PERFORM BDC_DYNPRO USING 'SAPLCLFM'        '0500'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'      'RMCLF-CLASS(01)'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'      '=AUSW'.

    PERFORM BDC_DYNPRO USING 'SAPLCTMS'        '0109'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'      'RCTMS-MWERT(01)'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'      '=BACK'.

    CLEAR TMP_FEC.
    CONCATENATE STR_CONTRATO-FEC_SUS+6(2) STR_CONTRATO-FEC_SUS+4(2) STR_CONTRATO-FEC_SUS(4) INTO TMP_FEC.
    PERFORM BDC_FIELD  USING 'RCTMS-MNAME(01)'  'ZFEC_SUSCRIPCION'.
    PERFORM BDC_FIELD  USING 'RCTMS-MWERT(01)'  TMP_FEC.
*
    CLEAR TMP_FEC.
    CONCATENATE STR_CONTRATO-FEC_CAJ+6(2) STR_CONTRATO-FEC_CAJ+4(2) STR_CONTRATO-FEC_CAJ(4) INTO TMP_FEC.
    PERFORM BDC_FIELD  USING 'RCTMS-MNAME(02)'    'ZFEC_CAJA'.
    PERFORM BDC_FIELD  USING 'RCTMS-MWERT(02)'    TMP_FEC.
*
*
    PERFORM BDC_FIELD  USING 'RCTMS-MNAME(03)'    'ZRUT_VENDEDOR'.
    PERFORM BDC_FIELD  USING 'RCTMS-MWERT(03)'    STR_CONTRATO-RUT_VEN.
*
    PERFORM BDC_FIELD  USING 'RCTMS-MNAME(04)'    'ZMONEDA'.
    PERFORM BDC_FIELD  USING 'RCTMS-MWERT(04)'    STR_CONTRATO-MONEDA.
*
    PERFORM BDC_FIELD  USING 'RCTMS-MNAME(05)'    'ZGRUPO_VENTA'.
    PERFORM BDC_FIELD  USING 'RCTMS-MWERT(05)'    STR_CONTRATO-GRP_VTA.
*
    PERFORM BDC_FIELD  USING 'RCTMS-MNAME(06)'    'ZCOMPANIA'.
    PERFORM BDC_FIELD  USING 'RCTMS-MWERT(06)'    STR_CONTRATO-COMPANIA.
*
    PERFORM BDC_FIELD  USING 'RCTMS-MNAME(07)'    'ZMCPA'.
    PERFORM BDC_FIELD  USING 'RCTMS-MWERT(07)'    STR_CONTRATO-ZMCPA.
*
    PERFORM BDC_FIELD  USING 'RCTMS-MNAME(08)'    'ZPACCR'.
    PERFORM BDC_FIELD  USING 'RCTMS-MWERT(08)'    STR_CONTRATO-ZPACCR.
*
    PERFORM BDC_FIELD  USING 'RCTMS-MNAME(09)'    'ZBETA'.
    PERFORM BDC_FIELD  USING 'RCTMS-MWERT(09)'    STR_CONTRATO-ZBETA.
*
    PERFORM BDC_FIELD  USING 'RCTMS-MNAME(10)'    'ZMCOB'.
    PERFORM BDC_FIELD  USING 'RCTMS-MWERT(10)'    STR_CONTRATO-ZMCOB.
*
    PERFORM BDC_DYNPRO USING 'SAPLCLFM'           '0500'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'         'RMCLF-CLASS(01)'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'         '=AUSW'.
*    PERFORM BDC_FIELD  USING 'RMCLF-PAGPOS'       '1'.
    PERFORM BDC_FIELD  USING 'RMCLF-KREUZ(01)'    'X'.

    PERFORM BDC_DYNPRO USING 'SAPLCTMS'           '0109'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'         'RCTMS-MWERT(10)'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'         'BACK'.
*
    PERFORM BDC_FIELD  USING 'RCTMS-MNAME(01)'    'ZOMEGA'.
    PERFORM BDC_FIELD  USING 'RCTMS-MWERT(01)'    STR_CONTRATO-ZOMEGA.
*
    PERFORM BDC_FIELD  USING 'RCTMS-MNAME(02)'    'ZALFA'.
    PERFORM BDC_FIELD  USING 'RCTMS-MWERT(02)'    STR_CONTRATO-ZALFA.
*
    PERFORM BDC_FIELD  USING 'RCTMS-MNAME(03)'    'ZREAJUSTE_IPC'.
    PERFORM BDC_FIELD  USING 'RCTMS-MWERT(03)'    STR_CONTRATO-ZREAJUSTE_IPC.
*
    PERFORM BDC_FIELD  USING 'RCTMS-MNAME(04)'    'ZREAJUSTE_TARIFA'.
    PERFORM BDC_FIELD  USING 'RCTMS-MWERT(04)'    STR_CONTRATO-ZREAJUSTE_TARIFA.
*
    PERFORM BDC_FIELD  USING 'RCTMS-MNAME(05)'    'ZNUMERO_CONVENIO'.
    PERFORM BDC_FIELD  USING 'RCTMS-MWERT(05)'    STR_CONTRATO-ZNUM_CONVENIO.
*
    PERFORM BDC_FIELD  USING 'RCTMS-MNAME(06)'    'ZVERSION_CONVENIO'.
    PERFORM BDC_FIELD  USING 'RCTMS-MWERT(06)'    STR_CONTRATO-ZVER_CONVENIO.
*
    PERFORM BDC_FIELD  USING 'RCTMS-MNAME(07)'    'ZRUT_PAGADOR'.
    PERFORM BDC_FIELD  USING 'RCTMS-MWERT(07)'    STR_CONTRATO-ZRUT_PAG.
*
    PERFORM BDC_FIELD  USING 'RCTMS-MNAME(08)'    'ZSISTEMA_PAGO'.
    PERFORM BDC_FIELD  USING 'RCTMS-MWERT(08)'    STR_CONTRATO-ZSIS_PAGO.
*
    PERFORM BDC_FIELD  USING 'RCTMS-MNAME(09)'    'ZMARCA1'.
    PERFORM BDC_FIELD  USING 'RCTMS-MWERT(09)'    STR_CONTRATO-ZMARCA1.
*
    PERFORM BDC_FIELD  USING 'RCTMS-MNAME(10)'    'ZMARCA2'.
    PERFORM BDC_FIELD  USING 'RCTMS-MWERT(10)'    STR_CONTRATO-ZMARCA2.
*
    PERFORM BDC_DYNPRO USING 'SAPLCLFM'           '0500'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'         'RMCLF-CLASS(01)'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'         '=AUSW'.
    PERFORM BDC_FIELD  USING 'RMCLF-KREUZ(01)'    'X'.

    PERFORM BDC_DYNPRO USING 'SAPLCTMS'           '0109'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'         'RCTMS-MWERT(02)'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'         '=BACK'.
*
    PERFORM BDC_FIELD  USING 'RCTMS-MNAME(01)'    'ZMARCA3'.
    PERFORM BDC_FIELD  USING 'RCTMS-MWERT(01)'    STR_CONTRATO-ZMARCA3.
*
    PERFORM BDC_FIELD  USING 'RCTMS-MNAME(02)'    'ZTIPO_PLAN'.
    PERFORM BDC_FIELD  USING 'RCTMS-MWERT(02)'    STR_CONTRATO-ZTIPO_PLAN.
*
    PERFORM BDC_DYNPRO USING 'SAPLCLFM'        '0500'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'      'RMCLF-CLASS(01)'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'      '=ENDE'.
*    PERFORM BDC_FIELD  USING 'RMCLF-PAGPOS'    '1'.

    PERFORM BDC_DYNPRO USING 'SAPMF02D'        '0110'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'      '=UPDA'.

    FREE MESSTAB.
    CALL TRANSACTION 'XD02' USING BDCDATA MODE CTUMODE
          UPDATE CUPDATE MESSAGES INTO MESSTAB.
    FREE BDCDATA.

    READ TABLE MESSTAB INTO LS_MESS WITH KEY MSGTYP = 'S'
                                             MSGID  = 'F2'
                                             MSGNR  = '056'.
    IF SY-SUBRC EQ 0.
      RETURN-TYPE       = LS_MESS-MSGTYP.
      RETURN-ID         = LS_MESS-MSGID.
      RETURN-NUMBER     = LS_MESS-MSGNR.
      CONCATENATE 'El contrato' STR_CONTRATO-SORT2 'se ha actualizado exitosamente en SAP.'
      INTO RETURN-MESSAGE SEPARATED BY SPACE.
      RETURN-LOG_NO     = SPACE.
      RETURN-LOG_MSG_NO = SPACE.
      RETURN-MESSAGE_V1 = LS_MESS-MSGV1.
      RETURN-MESSAGE_V2 = LS_MESS-MSGV2.
      RETURN-MESSAGE_V3 = LS_MESS-MSGV3.
      RETURN-MESSAGE_V4 = LS_MESS-MSGV4.
      RETURN-PARAMETER  = SPACE.
      RETURN-ROW        = SPACE.
      RETURN-FIELD      = SPACE.
      RETURN-SYSTEM     = SPACE.
      APPEND RETURN.
      CLEAR RETURN.
    ELSE.
      LOOP AT MESSTAB INTO LS_MESS.
        SELECT SINGLE TEXT INTO RETURN-MESSAGE FROM T100 WHERE SPRSL EQ SY-LANGU
                                                           AND ARBGB EQ LS_MESS-MSGID
                                                           AND MSGNR EQ LS_MESS-MSGNR.
        REPLACE '&' INTO RETURN-MESSAGE WITH LS_MESS-MSGV1.
        REPLACE '&' INTO RETURN-MESSAGE WITH LS_MESS-MSGV2.
        REPLACE '&' INTO RETURN-MESSAGE WITH LS_MESS-MSGV3.
        REPLACE '&' INTO RETURN-MESSAGE WITH LS_MESS-MSGV4.
        RETURN-TYPE       = LS_MESS-MSGTYP.
        RETURN-ID         = LS_MESS-MSGID.
        RETURN-NUMBER     = LS_MESS-MSGNR.
        RETURN-LOG_NO     = SPACE.
        RETURN-LOG_MSG_NO = SPACE.
        RETURN-MESSAGE_V1 = LS_MESS-MSGV1.
        RETURN-MESSAGE_V2 = LS_MESS-MSGV2.
        RETURN-MESSAGE_V3 = LS_MESS-MSGV3.
        RETURN-MESSAGE_V4 = LS_MESS-MSGV4.
        RETURN-PARAMETER  = SPACE.
        RETURN-ROW        = SPACE.
        RETURN-FIELD      = SPACE.
        RETURN-SYSTEM     = SPACE.
        APPEND RETURN.
        CLEAR RETURN.
      ENDLOOP.
    ENDIF.
  ELSE.
    RETURN-TYPE       = LS_MESS-MSGTYP.
    RETURN-ID         = LS_MESS-MSGID.
    RETURN-NUMBER     = LS_MESS-MSGNR.
    CONCATENATE 'El contrato' STR_CONTRATO-SORT2 'no existe en el sistema SAP' INTO RETURN-MESSAGE.
    RETURN-LOG_NO     = SPACE.
    RETURN-LOG_MSG_NO = SPACE.
    RETURN-MESSAGE_V1 = LS_MESS-MSGV1.
    RETURN-MESSAGE_V2 = LS_MESS-MSGV2.
    RETURN-MESSAGE_V3 = LS_MESS-MSGV3.
    RETURN-MESSAGE_V4 = LS_MESS-MSGV4.
    RETURN-PARAMETER  = SPACE.
    RETURN-ROW        = SPACE.
    RETURN-FIELD      = SPACE.
    RETURN-SYSTEM     = SPACE.
    APPEND RETURN.
    CLEAR RETURN.
  ENDIF.

ENDFUNCTION.
