*&---------------------------------------------------------------------*
*& Report: < ZEY_GDS_CORRECTION > *
*& Author: < EY_DES01 > *
*& Description: < ReSQ Correction > *
*& Date: <19-12-2019> *
*& Transport Number: < ECDK917080 > *
*&---------------------------------------------------------------------*
FUNCTION ZWS_ELI_AGR_INT_CLIENTES.
*"----------------------------------------------------------------------
*"*"Interfase local
*"  IMPORTING
*"     VALUE(ACTION) TYPE  CHAR01
*"  TABLES
*"      T_INT_CLI STRUCTURE  ZSD_BI_CLI_INT
*"      RETURN STRUCTURE  BAPIRET2
*"----------------------------------------------------------------------
  DATA WA_DATA_INT_AUX  LIKE ZSD_BI_CLI_INT.
  DATA STR_KUNNR TYPE STRING.
  FREE: BDCDATA, RETURN, MESSTAB.
  CLEAR: BDCDATA, RETURN, MESSTAB.

*Begin of change: ReSQ Correction INDEX READ on an unsorted Internal TABLE 19/12/2019 EY_DES01 ECDK917080 *
SORT T_INT_CLI .
*End of change: ReSQ Correction for INDEX READ on an unsorted Internal TABLE 19/12/2019 EY_DES01 ECDK917080 *
  READ TABLE T_INT_CLI INTO WA_DATA_INT_AUX INDEX 1.
  IF SY-SUBRC = 0.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*    SELECT SINGLE * FROM KNA1 WHERE STCD1 EQ WA_DATA_INT_AUX-NROCLIENTE.
*
* NEW CODE
    SELECT *
    UP TO 1 ROWS  FROM KNA1 WHERE STCD1 EQ WA_DATA_INT_AUX-NROCLIENTE ORDER BY PRIMARY KEY.

    ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
    IF SY-SUBRC = 0.
      PERFORM BDC_DYNPRO USING 'SAPMF02D'    '0101'.
      PERFORM BDC_FIELD  USING 'BDC_CURSOR'  'RF02D-D0324'.
      PERFORM BDC_FIELD  USING 'BDC_OKCODE'  '/00'.
      PERFORM BDC_FIELD  USING 'RF02D-KUNNR' KNA1-KUNNR.
      PERFORM BDC_FIELD  USING 'RF02D-VKORG' WA_DATA_INT_AUX-OVENTAS.
      PERFORM BDC_FIELD  USING 'RF02D-VTWEG' WA_DATA_INT_AUX-CANAL.
      PERFORM BDC_FIELD  USING 'RF02D-SPART' WA_DATA_INT_AUX-SECTOR.
      PERFORM BDC_FIELD  USING 'RF02D-D0324' 'X'.
*
      LOOP AT T_INT_CLI INTO WA_DATA_INT_AUX.
        IF NOT WA_DATA_INT_AUX-CODIGOINT IS INITIAL.
          WHILE WA_DATA_INT_AUX-CODIGOINT(1) = '0'.
            SHIFT WA_DATA_INT_AUX-CODIGOINT LEFT.
          ENDWHILE.
        ENDIF.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*        SELECT SINGLE * FROM ADRC WHERE SORT2 EQ WA_DATA_INT_AUX-CODIGOINT.
*
* NEW CODE
        SELECT *
        UP TO 1 ROWS  FROM ADRC WHERE SORT2 EQ WA_DATA_INT_AUX-CODIGOINT ORDER BY PRIMARY KEY.

        ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
        IF SY-SUBRC = 0.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*          SELECT SINGLE * FROM KNA1 WHERE ADRNR EQ ADRC-ADDRNUMBER.
*
* NEW CODE
          SELECT *
          UP TO 1 ROWS  FROM KNA1 WHERE ADRNR EQ ADRC-ADDRNUMBER ORDER BY PRIMARY KEY.

          ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
        ENDIF.
        CASE ACTION.
          WHEN 'A'.
            PERFORM BDC_DYNPRO USING 'SAPMF02D'        '0324'.
            PERFORM BDC_FIELD  USING 'BDC_CURSOR'      'RF02D-KTONR(02)'.
            PERFORM BDC_FIELD  USING 'BDC_OKCODE'      '=ENTR'.
            PERFORM BDC_FIELD  USING 'KNVP-PARVW(02)'  WA_DATA_INT_AUX-FUNCIONINT.
            PERFORM BDC_FIELD  USING 'RF02D-KTONR(02)' KNA1-KUNNR.
          WHEN 'E'.
            PERFORM BDC_DYNPRO USING 'SAPMF02D'        '0324'.
            PERFORM BDC_FIELD  USING 'BDC_CURSOR'      '*RF02D-KTONR'.
            PERFORM BDC_FIELD  USING 'BDC_OKCODE'      '=ENTR'.
            PERFORM BDC_FIELD  USING '*KNVP-PARVW'     WA_DATA_INT_AUX-FUNCIONINT.
            PERFORM BDC_FIELD  USING '*RF02D-KTONR'    KNA1-KUNNR.
*
            PERFORM BDC_DYNPRO USING 'SAPMF02D'        '0324'.
            PERFORM BDC_FIELD  USING 'BDC_OKCODE'      'LDEL'.
        ENDCASE.
      ENDLOOP.
      PERFORM BDC_DYNPRO USING 'SAPMF02D'   '0324'.
      PERFORM BDC_FIELD  USING 'BDC_CURSOR' 'KNVP-PARVW(01)'.
      PERFORM BDC_FIELD  USING 'BDC_OKCODE' '=UPDA'.

      CALL TRANSACTION 'XD02' USING BDCDATA
                       MODE   CTUMODE
                       UPDATE CUPDATE
                       MESSAGES INTO MESSTAB.

      READ TABLE MESSTAB INTO LS_MESS WITH KEY MSGTYP = 'E'.
      IF SY-SUBRC = 0.
        LOOP AT MESSTAB INTO LS_MESS.
          IF LS_MESS-MSGNR = '630' AND LS_MESS-MSGID = 'F2'.
            CLEAR STR_KUNNR.
            CONCATENATE '%' LS_MESS-MSGV1 '%' INTO STR_KUNNR.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*            SELECT SINGLE * FROM KNA1 WHERE KUNNR LIKE STR_KUNNR.
*
* NEW CODE
            SELECT *
            UP TO 1 ROWS  FROM KNA1 WHERE KUNNR LIKE STR_KUNNR ORDER BY PRIMARY KEY.

            ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
            IF SY-SUBRC = 0.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*              SELECT SINGLE SORT2 INTO LS_MESS-MSGV1 FROM ADRC WHERE ADDRNUMBER EQ ADRC-ADDRNUMBER.
*
* NEW CODE
              SELECT SORT2
              UP TO 1 ROWS  INTO LS_MESS-MSGV1 FROM ADRC WHERE ADDRNUMBER EQ ADRC-ADDRNUMBER ORDER BY PRIMARY KEY.

              ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
            ENDIF.
          ENDIF.

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*          SELECT SINGLE TEXT INTO RETURN-MESSAGE FROM T100 WHERE SPRSL EQ SY-LANGU
*                                                       AND ARBGB EQ LS_MESS-MSGID
*                                                       AND MSGNR EQ LS_MESS-MSGNR.
*
* NEW CODE
          SELECT TEXT
          UP TO 1 ROWS  INTO RETURN-MESSAGE FROM T100 WHERE SPRSL EQ SY-LANGU
                                                       AND ARBGB EQ LS_MESS-MSGID
                                                       AND MSGNR EQ LS_MESS-MSGNR ORDER BY PRIMARY KEY.

          ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
          PERFORM MAKE_MESSAGE USING LS_MESS-MSGV1 CHANGING RETURN-MESSAGE.
          PERFORM MAKE_MESSAGE USING LS_MESS-MSGV2 CHANGING RETURN-MESSAGE.
          PERFORM MAKE_MESSAGE USING LS_MESS-MSGV3 CHANGING RETURN-MESSAGE.
          PERFORM MAKE_MESSAGE USING LS_MESS-MSGV4 CHANGING RETURN-MESSAGE.
          RETURN-TYPE       = LS_MESS-MSGTYP.
          RETURN-ID         = LS_MESS-MSGID.
          RETURN-NUMBER     = LS_MESS-MSGNR.
          RETURN-LOG_NO     = SPACE.
          RETURN-LOG_MSG_NO = SPACE.
          RETURN-MESSAGE_V1 = LS_MESS-MSGV1.
          RETURN-MESSAGE_V2 = LS_MESS-MSGV2.
          RETURN-MESSAGE_V3 = LS_MESS-MSGV3.
          RETURN-MESSAGE_V4 = LS_MESS-MSGV4.
          RETURN-PARAMETER  = SPACE.
          RETURN-ROW        = SPACE.
          RETURN-FIELD      = SPACE.
          RETURN-SYSTEM     = SPACE.
          APPEND RETURN.
          CLEAR RETURN.
        ENDLOOP.
      ELSE.
        RETURN-TYPE       = LS_MESS-MSGTYP.
        RETURN-ID         = LS_MESS-MSGID.
        RETURN-NUMBER     = LS_MESS-MSGNR.
        CONCATENATE 'El cliente' WA_DATA_INT_AUX-NROCLIENTE 'se ha actualizado exitosamente en SAP'
        INTO RETURN-MESSAGE separated by space.
        RETURN-LOG_NO     = SPACE.
        RETURN-LOG_MSG_NO = SPACE.
        RETURN-MESSAGE_V1 = LS_MESS-MSGV1.
        RETURN-MESSAGE_V2 = LS_MESS-MSGV2.
        RETURN-MESSAGE_V3 = LS_MESS-MSGV3.
        RETURN-MESSAGE_V4 = LS_MESS-MSGV4.
        RETURN-PARAMETER  = SPACE.
        RETURN-ROW        = SPACE.
        RETURN-FIELD      = SPACE.
        RETURN-SYSTEM     = SPACE.
        APPEND RETURN.
        CLEAR RETURN.
      ENDIF.
    ELSE.
      RETURN-TYPE       = 'E'.
      RETURN-ID         = LS_MESS-MSGID.
      RETURN-NUMBER     = LS_MESS-MSGNR.
      CONCATENATE 'No existe el cliente' WA_DATA_INT_AUX-NROCLIENTE INTO RETURN-MESSAGE.
      RETURN-LOG_NO     = SPACE.
      RETURN-LOG_MSG_NO = SPACE.
      RETURN-MESSAGE_V1 = 'No existe el cliente'.
      RETURN-MESSAGE_V2 = WA_DATA_INT_AUX-NROCLIENTE.
      RETURN-MESSAGE_V3 = SPACE.
      RETURN-MESSAGE_V4 = SPACE.
      RETURN-PARAMETER  = SPACE.
      RETURN-ROW        = SPACE.
      RETURN-FIELD      = SPACE.
      RETURN-SYSTEM     = SPACE.
      APPEND RETURN.
      CLEAR RETURN.
    ENDIF.
  ELSE.
    RETURN-TYPE       = 'E'.
    RETURN-ID         = LS_MESS-MSGID.
    RETURN-NUMBER     = LS_MESS-MSGNR.
    RETURN-MESSAGE    = 'Es necesario ingresar al menos 1 interlocutor'.
    RETURN-LOG_NO     = SPACE.
    RETURN-LOG_MSG_NO = SPACE.
    RETURN-MESSAGE_V1 = 'Es necesario ingresar al menos 1 interlocutor'.
    RETURN-MESSAGE_V2 = SPACE.
    RETURN-MESSAGE_V3 = SPACE.
    RETURN-MESSAGE_V4 = SPACE.
    RETURN-PARAMETER  = SPACE.
    RETURN-ROW        = SPACE.
    RETURN-FIELD      = SPACE.
    RETURN-SYSTEM     = SPACE.
    APPEND RETURN.
    CLEAR RETURN.
  ENDIF.

ENDFUNCTION.
