FUNCTION ZCONSUL_CTA_CTE.
*"----------------------------------------------------------------------
*"*"Interfase local
*"  IMPORTING
*"     VALUE(P_BUKRS) LIKE  BSID-BUKRS
*"     VALUE(P_STCD1) LIKE  KNA1-STCD1
*"  TABLES
*"      STR_CTA_CTE STRUCTURE  ZSAPCTACTEBSID
*"----------------------------------------------------------------------
  TABLES BSAD.
  TABLES BSID.

  DATA TMP_KUNNR LIKE KNA1-KUNNR.
  DATA      amount_display like wmto_s-amount.
  DATA      amount_sap like wmto_s-amount.

  TYPES BEGIN OF TI_DATA_BSID.
          INCLUDE STRUCTURE ZSAPCTACTEBSID.
  TYPES END OF TI_DATA_BSID.
*  DATA STR_CTA_CTE TYPE STANDARD TABLE OF TI_DATA_BSID WITH HEADER LINE.

  FREE STR_CTA_CTE.
  CLEAR STR_CTA_CTE.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE KUNNR INTO TMP_KUNNR FROM KNA1 WHERE STCD1 EQ P_STCD1.
*
* NEW CODE
  SELECT KUNNR
  UP TO 1 ROWS  INTO TMP_KUNNR FROM KNA1 WHERE STCD1 EQ P_STCD1 ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
* BEGIN. 07-07-2026 - ATC - ATC-03
* OLD CODE
*  SELECT * FROM BSID WHERE BUKRS EQ P_BUKRS
*                       AND KUNNR EQ TMP_KUNNR.
*
* NEW CODE
  SELECT *
 FROM BSID WHERE BUKRS EQ P_BUKRS
                       AND KUNNR EQ TMP_KUNNR ORDER BY PRIMARY KEY.

* END. 07-07-2026 - ATC - ATC-03
    MOVE-CORRESPONDING BSID TO STR_CTA_CTE.

    CALL FUNCTION 'CONVERSION_EXIT_ALPHA_OUTPUT'
      EXPORTING
        INPUT  = BSID-VERTN
      IMPORTING
        OUTPUT = STR_CTA_CTE-VERTN.
*------------------------------
* INICIO STR_CTA_CTE-DMBTR
*------------------------------
amount_sap = BSID-DMBTR.

    CALL FUNCTION 'CURRENCY_AMOUNT_SAP_TO_DISPLAY'
        EXPORTING
          CURRENCY              = BSID-WAERS
          AMOUNT_INTERNAL       = amount_sap
       IMPORTING
         AMOUNT_DISPLAY        = amount_display.

    WRITE amount_display TO STR_CTA_CTE-DMBTR.
    REPLACE '.' WITH SPACE INTO STR_CTA_CTE-DMBTR.
    CONDENSE STR_CTA_CTE-DMBTR NO-GAPS.
*------------------------------
* FIN TOTAL STR_CTA_CTE-DMBTR
*------------------------------
*------------------------------
* INICIO STR_CTA_CTE-WRBTR
*------------------------------
amount_sap = BSID-WRBTR.

    CALL FUNCTION 'CURRENCY_AMOUNT_SAP_TO_DISPLAY'
        EXPORTING
          CURRENCY              = BSID-WAERS
          AMOUNT_INTERNAL       = amount_sap
       IMPORTING
         AMOUNT_DISPLAY        = amount_display.

    WRITE amount_display TO STR_CTA_CTE-WRBTR.
    REPLACE '.' WITH SPACE INTO STR_CTA_CTE-WRBTR.
    CONDENSE STR_CTA_CTE-WRBTR NO-GAPS.
*------------------------------
* FIN STR_CTA_CTE-WRBTR
*------------------------------
*------------------------------
* INICIO STR_CTA_CTE-MWSTS
*------------------------------
amount_sap = BSID-MWSTS.

    CALL FUNCTION 'CURRENCY_AMOUNT_SAP_TO_DISPLAY'
        EXPORTING
          CURRENCY              = BSID-WAERS
          AMOUNT_INTERNAL       = amount_sap
       IMPORTING
         AMOUNT_DISPLAY        = amount_display.


    WRITE amount_display TO STR_CTA_CTE-MWSTS.
    REPLACE '.' WITH SPACE INTO STR_CTA_CTE-MWSTS.
    CONDENSE STR_CTA_CTE-MWSTS NO-GAPS.

*------------------------------
* FIN STR_CTA_CTE-MWSTS
*------------------------------

*------------------------------
* INICIO STR_CTA_CTE-SKFBT
*------------------------------
amount_sap = BSID-SKFBT.

    CALL FUNCTION 'CURRENCY_AMOUNT_SAP_TO_DISPLAY'
        EXPORTING
          CURRENCY              = BSID-WAERS
          AMOUNT_INTERNAL       = amount_sap
       IMPORTING
         AMOUNT_DISPLAY        = amount_display.

    WRITE amount_display TO STR_CTA_CTE-SKFBT.
    REPLACE '.' WITH SPACE INTO STR_CTA_CTE-SKFBT.
    CONDENSE STR_CTA_CTE-SKFBT NO-GAPS.
*------------------------------
* FIN STR_CTA_CTE-SKFBT
*------------------------------
*------------------------------
* INICIO STR_CTA_CTE-SKNTO
*------------------------------
amount_sap = BSID-SKNTO.

    CALL FUNCTION 'CURRENCY_AMOUNT_SAP_TO_DISPLAY'
        EXPORTING
          CURRENCY              = BSID-WAERS
          AMOUNT_INTERNAL       = amount_sap
       IMPORTING
         AMOUNT_DISPLAY        = amount_display.

    WRITE amount_display TO STR_CTA_CTE-SKNTO.
    REPLACE '.' WITH SPACE INTO STR_CTA_CTE-SKNTO.
    CONDENSE STR_CTA_CTE-SKNTO NO-GAPS.
*------------------------------
* FIN STR_CTA_CTE-SKNTO
*------------------------------
*------------------------------
* INICIO STR_CTA_CTE-WSKTO
*------------------------------
amount_sap = BSID-WSKTO.

    CALL FUNCTION 'CURRENCY_AMOUNT_SAP_TO_DISPLAY'
        EXPORTING
          CURRENCY              = BSID-WAERS
          AMOUNT_INTERNAL       = amount_sap
       IMPORTING
         AMOUNT_DISPLAY        = amount_display.

    WRITE amount_display TO STR_CTA_CTE-WSKTO.
    REPLACE '.' WITH SPACE INTO STR_CTA_CTE-WSKTO.
    CONDENSE STR_CTA_CTE-WSKTO NO-GAPS.
*------------------------------
* FIN STR_CTA_CTE-WSKTO
*------------------------------

*-----------------------------------------
*OBTENER     DATOS  DESDE zfac_anex 20131219
*-----------------------------------------


* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
* SELECT SINGLE ZFEC_CONT
*    INTO  STR_CTA_CTE-ZFEC_CONT
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
 SELECT ZFEC_CONT
 UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZFEC_CONT
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

 ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01


* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*    SELECT SINGLE ZRUT_BENEF
*    INTO  STR_CTA_CTE-ZRUT_BENEF
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
    SELECT ZRUT_BENEF
    UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZRUT_BENEF
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

    ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZSECTOR
*    INTO  STR_CTA_CTE-ZSECTOR
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
  SELECT ZSECTOR
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZSECTOR
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*    SELECT SINGLE ZR_ETAREO
*    INTO  STR_CTA_CTE-ZR_ETAREO
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
    SELECT ZR_ETAREO
    UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZR_ETAREO
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

    ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
* SELECT SINGLE ZRUT_CLI_PAGADOR
*    INTO  STR_CTA_CTE-ZRUT_CLI_PAGADOR
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
 SELECT ZRUT_CLI_PAGADOR
 UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZRUT_CLI_PAGADOR
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

 ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
* SELECT SINGLE ZRUT_CLI_FACT
*    INTO  STR_CTA_CTE-ZRUT_CLI_FACT
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
 SELECT ZRUT_CLI_FACT
 UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZRUT_CLI_FACT
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

 ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01



* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*    SELECT SINGLE ZNOM_CLI_FACT
*    INTO  STR_CTA_CTE-ZNOM_CLI_FACT
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
    SELECT ZNOM_CLI_FACT
    UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZNOM_CLI_FACT
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

    ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZGIRO_CLI_FACT
*    INTO  STR_CTA_CTE-ZGIRO_CLI_FACT
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
  SELECT ZGIRO_CLI_FACT
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZGIRO_CLI_FACT
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZDIR_FACT
*    INTO  STR_CTA_CTE-ZDIR_FACT
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
  SELECT ZDIR_FACT
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZDIR_FACT
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZCOMUNA_FACT
*    INTO  STR_CTA_CTE-ZCOMUNA_FACT
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
  SELECT ZCOMUNA_FACT
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZCOMUNA_FACT
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*   SELECT SINGLE ZCIUDAD_FACT
*    INTO  STR_CTA_CTE-ZCIUDAD_FACT
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
   SELECT ZCIUDAD_FACT
   UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZCIUDAD_FACT
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

   ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01


* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
* SELECT SINGLE ZBLART
*    INTO  STR_CTA_CTE-ZBLART
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
 SELECT ZBLART
 UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZBLART
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

 ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01



* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE ZELECTRONICO
*    INTO  STR_CTA_CTE-ZELECTRONICO
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
SELECT ZELECTRONICO
UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZELECTRONICO
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZVKORG
*    INTO  STR_CTA_CTE-ZVKORG
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
  SELECT ZVKORG
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZVKORG
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE ZVTWEG
*    INTO  STR_CTA_CTE-ZVTWEG
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
SELECT ZVTWEG
UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZVTWEG
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE ZKVGR3
*    INTO  STR_CTA_CTE-ZKVGR3
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
SELECT ZKVGR3
UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZKVGR3
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01


* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZCENTRO
*    INTO  STR_CTA_CTE-ZCENTRO
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
  SELECT ZCENTRO
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZCENTRO
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*     SELECT SINGLE ZNUM_MANDATO
*    INTO  STR_CTA_CTE-ZNUM_MANDATO
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
     SELECT ZNUM_MANDATO
     UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZNUM_MANDATO
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

     ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

*V1 18.08.2017
*     SELECT SINGLE ZCOD_RECHAZO
*    INTO  STR_CTA_CTE-ZCOD_RECHAZO
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZURL
*    INTO  STR_CTA_CTE-ZURL
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
  SELECT ZURL
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZURL
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01





* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZTIP_CAMBIO_REF
*    INTO  STR_CTA_CTE-ZTIP_CAMBIO_REF
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
  SELECT ZTIP_CAMBIO_REF
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZTIP_CAMBIO_REF
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZNUM_DOC_CORE
*    INTO  STR_CTA_CTE-ZNUM_DOC_CORE
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
  SELECT ZNUM_DOC_CORE
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZNUM_DOC_CORE
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZNUM_ENDOSO
*    INTO  STR_CTA_CTE-ZNUM_ENDOSO
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
  SELECT ZNUM_ENDOSO
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZNUM_ENDOSO
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZKVGR4
*    INTO  STR_CTA_CTE-ZKVGR4
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
  SELECT ZKVGR4
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZKVGR4
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZIND_AFECTO
*    INTO  STR_CTA_CTE-ZIND_AFECTO
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
  SELECT ZIND_AFECTO
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZIND_AFECTO
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZIND_TRASPASO
*    INTO  STR_CTA_CTE-ZIND_TRASPASO
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
  SELECT ZIND_TRASPASO
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZIND_TRASPASO
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZCOPAGO_PLAN
*    INTO  STR_CTA_CTE-ZCOPAGO_PLAN
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
  SELECT ZCOPAGO_PLAN
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZCOPAGO_PLAN
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZPLAN
*    INTO  STR_CTA_CTE-ZPLAN
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
  SELECT ZPLAN
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZPLAN
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZBLOQ_PAGO
*    INTO  STR_CTA_CTE-ZBLOQ_PAGO
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
  SELECT ZBLOQ_PAGO
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZBLOQ_PAGO
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01


* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZMONTO_TOTAL
*    INTO  STR_CTA_CTE-ZMONTO_TOTAL
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
  SELECT ZMONTO_TOTAL
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZMONTO_TOTAL
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZMONTO_UF
*    INTO  STR_CTA_CTE-ZMONTO_UF
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSID-BUKRS
*    AND   BELNR  EQ BSID-BELNR
*    AND   GJAHR EQ BSID-GJAHR
*    AND   BUZEI EQ BSID-BUZEI.
*
* NEW CODE
  SELECT ZMONTO_UF
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZMONTO_UF
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSID-BUKRS
    AND   BELNR  EQ BSID-BELNR
    AND   GJAHR EQ BSID-GJAHR
    AND   BUZEI EQ BSID-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
*-----------------------------------------
*FIN OBTENER     DATOS  DESDE zfac_anex 20131219
*-----------------------------------------


    APPEND STR_CTA_CTE.
  ENDSELECT.

* BEGIN. 07-07-2026 - ATC - ATC-03
* OLD CODE
*  SELECT * FROM BSAD WHERE BUKRS EQ P_BUKRS
*                       AND KUNNR EQ TMP_KUNNR.
*
* NEW CODE
  SELECT *
 FROM BSAD WHERE BUKRS EQ P_BUKRS
                       AND KUNNR EQ TMP_KUNNR ORDER BY PRIMARY KEY.

* END. 07-07-2026 - ATC - ATC-03
    MOVE-CORRESPONDING BSAD TO STR_CTA_CTE.
    CALL FUNCTION 'CONVERSION_EXIT_ALPHA_OUTPUT'
      EXPORTING
        INPUT  = BSAD-VERTN
      IMPORTING
        OUTPUT = STR_CTA_CTE-VERTN.

*------------------------------
* INICIO BSAD-DMBTR
*------------------------------
amount_sap = BSAD-DMBTR.

    CALL FUNCTION 'CURRENCY_AMOUNT_SAP_TO_DISPLAY'
        EXPORTING
          CURRENCY              = BSAD-WAERS
          AMOUNT_INTERNAL       = amount_sap
       IMPORTING
         AMOUNT_DISPLAY        = amount_display.

    WRITE amount_display TO STR_CTA_CTE-DMBTR.
    REPLACE '.' WITH SPACE INTO STR_CTA_CTE-DMBTR.
    CONDENSE STR_CTA_CTE-DMBTR NO-GAPS.
*------------------------------
* FIN BSAD-DMBTR
*------------------------------
*------------------------------
* INICIO BSAD-WRBTR
*------------------------------
amount_sap = BSAD-WRBTR.

    CALL FUNCTION 'CURRENCY_AMOUNT_SAP_TO_DISPLAY'
        EXPORTING
          CURRENCY              = BSAD-WAERS
          AMOUNT_INTERNAL       = amount_sap
       IMPORTING
         AMOUNT_DISPLAY        = amount_display.

    WRITE amount_display TO STR_CTA_CTE-WRBTR.
    REPLACE '.' WITH SPACE INTO STR_CTA_CTE-WRBTR.
    CONDENSE STR_CTA_CTE-WRBTR NO-GAPS.
*------------------------------
* FIN BSAD-WRBTR
*------------------------------
*------------------------------
* INICIO BSAD-MWSTS
*------------------------------
amount_sap = BSAD-MWSTS.

    CALL FUNCTION 'CURRENCY_AMOUNT_SAP_TO_DISPLAY'
        EXPORTING
          CURRENCY              = BSAD-WAERS
          AMOUNT_INTERNAL       = amount_sap
       IMPORTING
         AMOUNT_DISPLAY        = amount_display.

    WRITE amount_display TO STR_CTA_CTE-MWSTS.
    REPLACE '.' WITH SPACE INTO STR_CTA_CTE-MWSTS.
    CONDENSE STR_CTA_CTE-MWSTS NO-GAPS.

*------------------------------
* FIN BSAD-MWSTS
*------------------------------
*------------------------------
* INICIO BSAD-SKFBT
*------------------------------
    amount_sap = BSAD-SKFBT.

    CALL FUNCTION 'CURRENCY_AMOUNT_SAP_TO_DISPLAY'
        EXPORTING
          CURRENCY              = BSAD-WAERS
          AMOUNT_INTERNAL       = amount_sap
       IMPORTING
         AMOUNT_DISPLAY        = amount_display.

      WRITE amount_display TO STR_CTA_CTE-SKFBT.
      REPLACE '.' WITH SPACE INTO STR_CTA_CTE-SKFBT.
      CONDENSE STR_CTA_CTE-SKFBT NO-GAPS.
*------------------------------
* FIN BSAD-SKFBT
*------------------------------

*------------------------------
* INICIO BSAD-SKNTO
*------------------------------
    amount_sap = BSAD-SKNTO.

    CALL FUNCTION 'CURRENCY_AMOUNT_SAP_TO_DISPLAY'
        EXPORTING
          CURRENCY              = BSAD-WAERS
          AMOUNT_INTERNAL       = amount_sap
       IMPORTING
         AMOUNT_DISPLAY        = amount_display.

    WRITE amount_display TO STR_CTA_CTE-SKNTO.
    REPLACE '.' WITH SPACE INTO STR_CTA_CTE-SKNTO.
    CONDENSE STR_CTA_CTE-SKNTO NO-GAPS.
*------------------------------
* FIN BSAD-SKNTO
*------------------------------
*------------------------------
* INICIO BSAD-WSKTO
*------------------------------
    amount_sap = BSAD-WSKTO.

    CALL FUNCTION 'CURRENCY_AMOUNT_SAP_TO_DISPLAY'
        EXPORTING
          CURRENCY              = BSAD-WAERS
          AMOUNT_INTERNAL       = amount_sap
       IMPORTING
         AMOUNT_DISPLAY        = amount_display.

    WRITE amount_display TO STR_CTA_CTE-WSKTO.
    REPLACE '.' WITH SPACE INTO STR_CTA_CTE-WSKTO.
    CONDENSE STR_CTA_CTE-WSKTO NO-GAPS.
*------------------------------
* FIN BSAD-WSKTO
*------------------------------
*-----------------------------------------
*OBTENER     DATOS  DESDE zfac_anex 20131219
*-----------------------------------------
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*   SELECT SINGLE ZFEC_CONT
*    INTO  STR_CTA_CTE-ZFEC_CONT
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
   SELECT ZFEC_CONT
   UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZFEC_CONT
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

   ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01


* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*    SELECT SINGLE ZRUT_BENEF
*    INTO  STR_CTA_CTE-ZRUT_BENEF
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
    SELECT ZRUT_BENEF
    UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZRUT_BENEF
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

    ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZSECTOR
*    INTO  STR_CTA_CTE-ZSECTOR
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
  SELECT ZSECTOR
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZSECTOR
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*    SELECT SINGLE ZR_ETAREO
*    INTO  STR_CTA_CTE-ZR_ETAREO
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
    SELECT ZR_ETAREO
    UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZR_ETAREO
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

    ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
* SELECT SINGLE ZRUT_CLI_PAGADOR
*    INTO  STR_CTA_CTE-ZRUT_CLI_PAGADOR
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
 SELECT ZRUT_CLI_PAGADOR
 UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZRUT_CLI_PAGADOR
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

 ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
* SELECT SINGLE ZRUT_CLI_FACT
*    INTO  STR_CTA_CTE-ZRUT_CLI_FACT
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
 SELECT ZRUT_CLI_FACT
 UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZRUT_CLI_FACT
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

 ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01



* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*    SELECT SINGLE ZNOM_CLI_FACT
*    INTO  STR_CTA_CTE-ZNOM_CLI_FACT
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
    SELECT ZNOM_CLI_FACT
    UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZNOM_CLI_FACT
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

    ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZGIRO_CLI_FACT
*    INTO  STR_CTA_CTE-ZGIRO_CLI_FACT
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
  SELECT ZGIRO_CLI_FACT
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZGIRO_CLI_FACT
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZDIR_FACT
*    INTO  STR_CTA_CTE-ZDIR_FACT
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
  SELECT ZDIR_FACT
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZDIR_FACT
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZCOMUNA_FACT
*    INTO  STR_CTA_CTE-ZCOMUNA_FACT
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
  SELECT ZCOMUNA_FACT
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZCOMUNA_FACT
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*   SELECT SINGLE ZCIUDAD_FACT
*    INTO  STR_CTA_CTE-ZCIUDAD_FACT
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
   SELECT ZCIUDAD_FACT
   UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZCIUDAD_FACT
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

   ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01


* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
* SELECT SINGLE ZBLART
*    INTO  STR_CTA_CTE-ZBLART
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
 SELECT ZBLART
 UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZBLART
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

 ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01



* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE ZELECTRONICO
*    INTO  STR_CTA_CTE-ZELECTRONICO
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
SELECT ZELECTRONICO
UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZELECTRONICO
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZVKORG
*    INTO  STR_CTA_CTE-ZVKORG
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
  SELECT ZVKORG
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZVKORG
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE ZVTWEG
*    INTO  STR_CTA_CTE-ZVTWEG
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
SELECT ZVTWEG
UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZVTWEG
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*SELECT SINGLE ZKVGR3
*    INTO  STR_CTA_CTE-ZKVGR3
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
SELECT ZKVGR3
UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZKVGR3
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01


* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZCENTRO
*    INTO  STR_CTA_CTE-ZCENTRO
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
  SELECT ZCENTRO
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZCENTRO
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*     SELECT SINGLE ZNUM_MANDATO
*    INTO  STR_CTA_CTE-ZNUM_MANDATO
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
     SELECT ZNUM_MANDATO
     UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZNUM_MANDATO
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

     ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

*V1 18-08.2017
*     SELECT SINGLE ZCOD_RECHAZO
*    INTO  STR_CTA_CTE-ZCOD_RECHAZO
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZURL
*    INTO  STR_CTA_CTE-ZURL
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
  SELECT ZURL
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZURL
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01





* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZTIP_CAMBIO_REF
*    INTO  STR_CTA_CTE-ZTIP_CAMBIO_REF
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
  SELECT ZTIP_CAMBIO_REF
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZTIP_CAMBIO_REF
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZNUM_DOC_CORE
*    INTO  STR_CTA_CTE-ZNUM_DOC_CORE
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
  SELECT ZNUM_DOC_CORE
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZNUM_DOC_CORE
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*      SELECT SINGLE ZNUM_ENDOSO
*    INTO  STR_CTA_CTE-ZNUM_ENDOSO
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
      SELECT ZNUM_ENDOSO
      UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZNUM_ENDOSO
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

      ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*    SELECT SINGLE ZKVGR4
*    INTO  STR_CTA_CTE-ZKVGR4
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
    SELECT ZKVGR4
    UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZKVGR4
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

    ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*    SELECT SINGLE ZIND_AFECTO
*    INTO  STR_CTA_CTE-ZIND_AFECTO
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
    SELECT ZIND_AFECTO
    UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZIND_AFECTO
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

    ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*    SELECT SINGLE ZIND_TRASPASO
*    INTO  STR_CTA_CTE-ZIND_TRASPASO
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
    SELECT ZIND_TRASPASO
    UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZIND_TRASPASO
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

    ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*         SELECT SINGLE ZCOPAGO_PLAN
*    INTO  STR_CTA_CTE-ZCOPAGO_PLAN
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
         SELECT ZCOPAGO_PLAN
         UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZCOPAGO_PLAN
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

         ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZPLAN
*    INTO  STR_CTA_CTE-ZPLAN
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
  SELECT ZPLAN
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZPLAN
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01


* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE ZBLOQ_PAGO
*    INTO  STR_CTA_CTE-ZBLOQ_PAGO
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
  SELECT ZBLOQ_PAGO
  UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZBLOQ_PAGO
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*      SELECT SINGLE ZMONTO_TOTAL
*    INTO  STR_CTA_CTE-ZMONTO_TOTAL
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
      SELECT ZMONTO_TOTAL
      UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZMONTO_TOTAL
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

      ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01

* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*          SELECT SINGLE ZMONTO_UF
*    INTO  STR_CTA_CTE-ZMONTO_UF
*  FROM ZFAC_ANEX
*    WHERE BUKRS EQ BSAD-BUKRS
*    AND   BELNR  EQ BSAD-BELNR
*    AND   GJAHR EQ BSAD-GJAHR
*    AND   BUZEI EQ BSAD-BUZEI.
*
* NEW CODE
          SELECT ZMONTO_UF
          UP TO 1 ROWS 
    INTO  STR_CTA_CTE-ZMONTO_UF
  FROM ZFAC_ANEX
    WHERE BUKRS EQ BSAD-BUKRS
    AND   BELNR  EQ BSAD-BELNR
    AND   GJAHR EQ BSAD-GJAHR
    AND   BUZEI EQ BSAD-BUZEI ORDER BY PRIMARY KEY.

          ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
*-----------------------------------------
*FIN OBTENER     DATOS  DESDE zfac_anex 20131219
*-----------------------------------------
    APPEND STR_CTA_CTE.
  ENDSELECT.

ENDFUNCTION.
