FUNCTION ZWS_MOD_CLIENTES.
*"----------------------------------------------------------------------
*"*"Interfase local
*"  IMPORTING
*"     VALUE(STR_CLIENTE) LIKE  ZSD_BI_CLIENTES STRUCTURE
*"        ZSD_BI_CLIENTES
*"  EXPORTING
*"     VALUE(L_MESSAGE) TYPE  BAPI_MSG
*"  TABLES
*"      RETURN STRUCTURE  BAPIRET2
*"----------------------------------------------------------------------
  TABLES ADR2.

  DATA L_KUNNR LIKE KNA1-KUNNR.
  CLEAR WA_DATA.
  WA_DATA = STR_CLIENTE.
  SELECT SINGLE * FROM KNA1 WHERE STCD1 EQ WA_DATA-RUT.
  IF SY-SUBRC = 0.
    PERFORM BDC_DYNPRO USING 'SAPMF02D'    '0101'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'  'RF02D-SPART'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'  '=MALL'.
    PERFORM BDC_FIELD  USING 'RF02D-KUNNR' KNA1-KUNNR.
    PERFORM BDC_FIELD  USING 'RF02D-BUKRS' WA_DATA-SOCIEDAD.
    PERFORM BDC_FIELD  USING 'RF02D-VKORG' WA_DATA-OVENTAS.
    PERFORM BDC_FIELD  USING 'RF02D-VTWEG' WA_DATA-CANAL.
    PERFORM BDC_FIELD  USING 'RF02D-SPART' WA_DATA-SECTOR.

    PERFORM BDC_DYNPRO USING 'SAPMF02D'         '0101'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'       '/00'.
    PERFORM BDC_FIELD  USING 'USE_ZAV'          'X'.

    PERFORM BDC_DYNPRO USING 'SAPMF02D'     '0111'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'   '=$MTE'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'   'SZA1_D0100-TITLE_MEDI'.
    PERFORM BDC_FIELD  USING 'ADDR1_DATA-NAME1' WA_DATA-NOMBRE1.
    PERFORM BDC_FIELD  USING 'ADDR1_DATA-NAME2' WA_DATA-NOMBRE2.
    PERFORM BDC_FIELD  USING 'ADDR1_DATA-SORT1'   WA_DATA-RUT.
    PERFORM BDC_FIELD  USING 'ADDR1_DATA-SORT2'   WA_DATA-NROCLIENTECORE.
    PERFORM BDC_FIELD  USING 'ADDR1_DATA-BUILDING' WA_DATA-DEPTO.
    PERFORM BDC_FIELD  USING 'ADDR1_DATA-FLOOR'    WA_DATA-PISO.
    PERFORM BDC_FIELD  USING 'ADDR1_DATA-STR_SUPPL1'  WA_DATA-CALLE2.
    PERFORM BDC_FIELD  USING 'ADDR1_DATA-STR_SUPPL2' WA_DATA-BLOCK.
    PERFORM BDC_FIELD  USING 'ADDR1_DATA-STREET'         WA_DATA-CALLE.
    PERFORM BDC_FIELD  USING 'ADDR1_DATA-HOUSE_NUM1'      WA_DATA-NUMERO.
    PERFORM BDC_FIELD  USING 'ADDR1_DATA-LOCATION' WA_DATA-VILLA.
    PERFORM BDC_FIELD  USING 'ADDR1_DATA-CITY2'         WA_DATA-COMUNA.
    PERFORM BDC_FIELD  USING 'ADDR1_DATA-CITY1'         WA_DATA-CIUDAD.
    PERFORM BDC_FIELD  USING 'ADDR1_DATA-COUNTRY'     WA_DATA-PAIS.
    PERFORM BDC_FIELD  USING 'ADDR1_DATA-REGION'         WA_DATA-REGION.
    PERFORM BDC_FIELD  USING 'ADDR1_DATA-LANGU'         SY-LANGU.
    PERFORM BDC_FIELD  USING 'SZA1_D0100-TEL_NUMBER'  WA_DATA-TELEFONO1.
    PERFORM BDC_FIELD  USING 'SZA1_D0100-MOB_NUMBER'    WA_DATA-MOVIL.
    PERFORM BDC_FIELD  USING 'ADDR1_DATA-REMARK'       WA_DATA-FECHANAC.

    PERFORM BDC_DYNPRO USING 'SAPLSZA6'     '0200'.
    PERFORM BDC_FIELD  USING 'ADTEL-TEL_NUMBER(01)' WA_DATA-TELEFONO1.

    SELECT SINGLE * FROM ADR2 WHERE ADDRNUMBER EQ KNA1-ADRNR
                                AND R3_USER    EQ SPACE.
    IF SY-SUBRC = 0.
      PERFORM BDC_FIELD  USING 'BDC_OKCODE' '=CONT'.
      IF WA_DATA-TELEFONO2 EQ SPACE.
        PERFORM BDC_FIELD  USING 'ADTEL-TEL_NUMBER(02)' '0'.
      ELSE.
        PERFORM BDC_FIELD  USING 'ADTEL-TEL_NUMBER(02)' WA_DATA-TELEFONO2.
      ENDIF.
    ELSE.
      IF WA_DATA-TELEFONO2 NE SPACE.
        PERFORM BDC_FIELD  USING 'BDC_OKCODE' '=NEWL'.
        PERFORM BDC_DYNPRO USING 'SAPLSZA6'     '0200'.
        PERFORM BDC_FIELD  USING 'BDC_OKCODE'   '=CONT'.
        PERFORM BDC_FIELD  USING 'ADTEL-TEL_NUMBER(01)' WA_DATA-TELEFONO2.
      ENDIF.
    ENDIF.

    PERFORM BDC_DYNPRO USING 'SAPMF02D'     '0111'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'   '/00'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'   'SZA1_D0100-TITLE_MEDI'.

    PERFORM BDC_DYNPRO USING 'SAPMF02D'     '0120'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'   'KNA1-STCD1'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'   '/00'.
    PERFORM BDC_FIELD  USING 'KNA1-STCD1'   WA_DATA-RUT2.

    PERFORM BDC_DYNPRO USING 'SAPMF02D'     '0125'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'   'KNA1-NIELS'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'   '/00'.

    PERFORM BDC_DYNPRO USING 'SAPMF02D'     '0130'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'   'KNBK-BANKS(01)'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'   '=ENTR'.

    PERFORM BDC_DYNPRO USING 'SAPMF02D'     '0360'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'   'KNVK-NAMEV(01)'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'   '=ENTR'.

    PERFORM BDC_DYNPRO USING 'SAPMF02D'     '0210'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'   'KNB1-FDGRV'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'   '/00'.
    PERFORM BDC_FIELD  USING 'KNB1-AKONT'   WA_DATA-CUENTAASOCIADA.
    PERFORM BDC_FIELD  USING 'KNB1-ZUAWA'   WA_DATA-CLAVECLASIF.
    PERFORM BDC_FIELD  USING 'KNB1-FDGRV'   WA_DATA-GRUPOTESORERIA.

    PERFORM BDC_DYNPRO USING 'SAPMF02D'     '0215'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'   'KNB1-HBKID'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'   '/00'.
    PERFORM BDC_FIELD  USING 'KNB1-ZTERM'    WA_DATA-CONDICIONPAGO.
    PERFORM BDC_FIELD  USING 'KNB1-XZVER'   'X'.
    PERFORM BDC_FIELD  USING 'KNB1-ZWELS'   WA_DATA-VIAPAGO.
    PERFORM BDC_FIELD  USING 'KNB1-HBKID'   WA_DATA-BANCOPROPIO.

    PERFORM BDC_DYNPRO USING 'SAPMF02D'     '0220'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'   'KNB5-MAHNA'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'   '/00'.

    PERFORM BDC_DYNPRO USING 'SAPMF02D'     '0230'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'   'KNB1-VRSNR'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'   '/00'.

    PERFORM BDC_DYNPRO USING 'SAPMF02D' '0610'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'   '/00'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'   'RF02D-KUNNR'.

    PERFORM BDC_DYNPRO USING 'SAPMF02D' '0310'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'   'KNVV-KALKS'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'  '/00'.

    PERFORM BDC_DYNPRO USING 'SAPMF02D'     '0320'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'   'KNVV-KTGRD'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'   '/00'.
    PERFORM BDC_FIELD  USING 'KNVV-ZTERM'   WA_DATA-CONDPAGO.
    PERFORM BDC_FIELD  USING 'KNVV-KTGRD'   WA_DATA-GRUPOIMPUTACION.

    PERFORM BDC_DYNPRO USING 'SAPMF02D'    '1350'.
    PERFORM BDC_FIELD  USING 'BDC_CURSOR'  'KNVI-TAXKD(01)'.
    PERFORM BDC_FIELD  USING 'BDC_OKCODE'  '=UPDA'.
    PERFORM BDC_FIELD  USING 'KNVI-TAXKD(01)' WA_DATA-CLASIFFISCAL.

    CALL TRANSACTION 'XD02' USING BDCDATA
                     MODE   CTUMODE
                     UPDATE CUPDATE
                     MESSAGES INTO MESSTAB.
    FREE BDCDATA.

    READ TABLE MESSTAB INTO LS_MESS WITH KEY MSGTYP = 'S'
                                             MSGID  = 'F2'
                                             MSGNR  = '056'.
    IF SY-SUBRC EQ 0.
      RETURN-TYPE       = LS_MESS-MSGTYP.
      RETURN-ID         = LS_MESS-MSGID.
      RETURN-NUMBER     = LS_MESS-MSGNR.
      CONCATENATE 'El cliente' WA_DATA-NROCLIENTECORE 'se ha actualizado exitosamente en SAP'
             INTO RETURN-MESSAGE SEPARATED BY SPACE.
      RETURN-LOG_NO     = SPACE.
      RETURN-LOG_MSG_NO = SPACE.
      RETURN-MESSAGE_V1 = LS_MESS-MSGV1.
      RETURN-MESSAGE_V2 = LS_MESS-MSGV2.
      RETURN-MESSAGE_V3 = LS_MESS-MSGV3.
      RETURN-MESSAGE_V4 = LS_MESS-MSGV4.
      RETURN-PARAMETER  = SPACE.
      RETURN-ROW        = SPACE.
      RETURN-FIELD      = SPACE.
      RETURN-SYSTEM     = SPACE.
      APPEND RETURN.
      CLEAR RETURN.
      PERFORM ACTUALIZAR_TEXTOS USING KNA1-KUNNR WA_DATA-TEXTO1 WA_DATA-TEXTO2.
    ELSE.
      LOOP AT MESSTAB INTO LS_MESS.
        SELECT SINGLE TEXT INTO RETURN-MESSAGE FROM T100 WHERE SPRSL EQ SY-LANGU
                                                           AND ARBGB EQ LS_MESS-MSGID
                                                           AND MSGNR EQ LS_MESS-MSGNR.
        REPLACE '&1' INTO RETURN-MESSAGE WITH LS_MESS-MSGV1.
        REPLACE '&2' INTO RETURN-MESSAGE WITH LS_MESS-MSGV2.
        REPLACE '&3' INTO RETURN-MESSAGE WITH LS_MESS-MSGV3.
        REPLACE '&4' INTO RETURN-MESSAGE WITH LS_MESS-MSGV4.
        RETURN-TYPE       = LS_MESS-MSGTYP.
        RETURN-ID         = LS_MESS-MSGID.
        RETURN-NUMBER     = LS_MESS-MSGNR.
        RETURN-LOG_NO     = SPACE.
        RETURN-LOG_MSG_NO = SPACE.
        RETURN-MESSAGE_V1 = LS_MESS-MSGV1.
        RETURN-MESSAGE_V2 = LS_MESS-MSGV2.
        RETURN-MESSAGE_V3 = LS_MESS-MSGV3.
        RETURN-MESSAGE_V4 = LS_MESS-MSGV4.
        RETURN-PARAMETER  = SPACE.
        RETURN-ROW        = SPACE.
        RETURN-FIELD      = SPACE.
        RETURN-SYSTEM     = SPACE.
        APPEND RETURN.
        CLEAR RETURN.
      ENDLOOP.
    ENDIF.
  ELSE.
    RETURN-TYPE       = LS_MESS-MSGTYP.
    RETURN-ID         = LS_MESS-MSGID.
    RETURN-NUMBER     = LS_MESS-MSGNR.
    CONCATENATE 'El cliente' WA_DATA-NROCLIENTECORE 'no existe en el sistema SAP' INTO L_MESSAGE.
    RETURN-LOG_NO     = SPACE.
    RETURN-LOG_MSG_NO = SPACE.
    RETURN-MESSAGE_V1 = LS_MESS-MSGV1.
    RETURN-MESSAGE_V2 = LS_MESS-MSGV2.
    RETURN-MESSAGE_V3 = LS_MESS-MSGV3.
    RETURN-MESSAGE_V4 = LS_MESS-MSGV4.
    RETURN-PARAMETER  = SPACE.
    RETURN-ROW        = SPACE.
    RETURN-FIELD      = SPACE.
    RETURN-SYSTEM     = SPACE.
    APPEND RETURN.
    CLEAR RETURN.
  ENDIF.
  FREE MESSTAB.

ENDFUNCTION.
