*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZLCE_SIITOP.                      " Global Data
  INCLUDE LZLCE_SIIUXX.                      " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZLCE_SIIF00                            . " subprograms
  INCLUDE LZLCE_SIII00                            . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZLCE_SIIF...                      " Subprograms
* INCLUDE LZLCE_SIIO...                      " PBO-Modules
* INCLUDE LZLCE_SIII...                      " PAI-Modules
