"Name: \FU:BESTAND_INVENTUR_PRUEFEN\SE:BEGIN\EI
ENHANCEMENT 0 ZMM_STOCK_LOTE.
   IF sy-uname EQ 'V1_FUN' AND ( SY-TCODE EQ 'MM02' OR SY-TCODE EQ 'MASS' ).
     flag2_out = ''.
     EXIT.
   ENDIF.
ENDENHANCEMENT.
