*&---------------------------------------------------------------------*
*&  Include           ZMON_FACT_TOP
*&---------------------------------------------------------------------*
TABLES ZCABPEDEXT.
TABLES ZDETPEDEXT.
TYPES: BEGIN OF TY.
        INCLUDE STRUCTURE ZCABPEDEXT.
TYPES:  CELL_STYLES TYPE LVC_T_STYL,
       END OF TY.
CONSTANTS TRUE TYPE C VALUE 'X'.

DATA GT_CABPEDEXT     TYPE STANDARD TABLE OF TY WITH HEADER LINE.      "Output-Table
DATA LS_CABPEDEXT     LIKE LINE OF GT_CABPEDEXT.
DATA GT_DETPEDEXT     TYPE STANDARD TABLE OF ZDETPEDEXT WITH HEADER LINE.      "Output-Table
DATA LS_DETPEDEXT     LIKE LINE OF GT_DETPEDEXT.
DATA POS TYPE I.
DATA: GT_FIELDCATALOG TYPE LVC_T_FCAT, "Fieldcatalog
      LS_FIELDCATALOG TYPE LVC_S_FCAT,
      GT_SORT         TYPE LVC_T_SORT, "Sortiertabelle
      OK_CODE         LIKE SY-UCOMM.   "OK-Code
DATA TREE1  TYPE REF TO CL_GUI_ALV_TREE_SIMPLE.
DATA G_TOOLBAR          TYPE REF TO CL_GUI_TOOLBAR.
DATA L_TREE_CONTAINER_NAME(30) TYPE C.
DATA L_CUSTOM_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER.
INCLUDE <ICON>.
DATA NAME LIKE ICON-NAME.
DATA INFO(20).
DATA ORDER_HEAD           LIKE BAPISDHD1.
DATA ORDER_HEADX          LIKE BAPISDHD1X.
DATA SALESDOCUMENT        LIKE BAPIVBELN-VBELN.
DATA RETURN               LIKE BAPIRET2   OCCURS 0 WITH HEADER LINE.
DATA ORDER_PARTNERS       LIKE BAPIPARNR  OCCURS 0 WITH HEADER LINE.
DATA ORDER_ITEMS_IN       LIKE BAPISDITM  OCCURS 0 WITH HEADER LINE.
DATA ORDER_ITEMS_INX      LIKE BAPISDITMX OCCURS 0 WITH HEADER LINE.
DATA ORDER_SCHEDULES_IN   LIKE BAPISCHDL OCCURS 0 WITH HEADER LINE.
DATA ORDER_SCHEDULES_INX  LIKE BAPISCHDLX OCCURS 0 WITH HEADER LINE.
DATA ORDER_CONDITIONS_IN  LIKE BAPICOND OCCURS 0 WITH HEADER LINE.
DATA ORDER_CONDITIONS_INX LIKE BAPICONDX OCCURS 0 WITH HEADER LINE.
DATA IND_OUT              TYPE LVC_T_INDX.
DATA IT_INDEX_OUTTAB      TYPE LVC_T_INDX.
DATA LS_IND_OUT           TYPE LVC_INDEX.
DATA TMP_INDEX            TYPE I.
DATA BILL_DATA            TYPE STANDARD TABLE OF BAPIVBRK WITH HEADER LINE.
DATA RETURN_FAC           TYPE STANDARD TABLE OF BAPIRET1 WITH HEADER LINE.
DATA SUCCESS              TYPE STANDARD TABLE OF BAPIVBRKSUCCESS WITH HEADER LINE.
