PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZMOT_EMIS CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZMOT_EMIS-BUKRS .
    FIELD ZMOT_EMIS-ZZMOT_EMIS .
    FIELD ZMOT_EMIS-ZZDESCR .
    FIELD ZMOT_EMIS-MATERNAL .
    FIELD ZMOT_EMIS-CONCEPTO .
    FIELD ZMOT_EMIS-CTA_CADF .
    FIELD ZMOT_EMIS-CTA_CADE .
    FIELD ZMOT_EMIS-CTA_CADPRES .
    FIELD ZMOT_EMIS-CTA_PRES_D .
    FIELD ZMOT_EMIS-CTA_PRES_H .
    FIELD ZMOT_EMIS-CTA_CADVV .
    FIELD ZMOT_EMIS-BANCO_PRO .
    FIELD ZMOT_EMIS-ID_BANCO .
    FIELD ZMOT_EMIS-V_PAGO .
    FIELD ZMOT_EMIS-REPORT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZMOT_EMIS-BUKRS .
    FIELD ZMOT_EMIS-ZZMOT_EMIS .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
