*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZMOT_EMISTOP.                     " Global Data
  INCLUDE LZMOT_EMISUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZMOT_EMISF00                           . " subprograms
  INCLUDE LZMOT_EMISI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZMOT_EMISF...                     " Subprograms
* INCLUDE LZMOT_EMISO...                     " PBO-Modules
* INCLUDE LZMOT_EMISI...                     " PAI-Modules
