*&---------------------------------------------------------------------*
*& Report  ZMOV_FILE_TO_SERVER
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT ZMOV_FILE_TO_SERVER.

TYPE-POOLS TRUXS.
DATA IT_RAW TYPE TRUXS_T_TEXT_DATA.
DATA SERVER_NAME TYPE STRING.
CONSTANTS CON_TAB  TYPE C VALUE CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
TYPES: BEGIN OF STR_FILE,
    NROCLIENTE(10)  TYPE C,
    SOCIEDAD(4)     TYPE C,
    OVENTAS(4)      TYPE C,
    CANAL(2)        TYPE C,
    SECTOR(2)       TYPE C,
    GRUPOCUENTAS(4) TYPE C,
    NOMBRE1(30)     TYPE C,
    NOMBRE2(30)     TYPE C,
    RUT(20)         TYPE C,
    NROCLIENTECORE(20) TYPE C,
    CALLE(60) TYPE C,
    CALLE2(40) TYPE C,
    NUMERO(10) TYPE C,
    DEPTO(20) TYPE C,
    PISO(10) TYPE C,
    BLOCK(40) TYPE C,
    VILLA(40) TYPE C,
    COMUNA(40) TYPE C,
    CIUDAD(40) TYPE C,
    PAIS(3) TYPE C,
    REGION(3) TYPE C,
     FECHANAC(50) TYPE C,
     TELEFONO1(30) TYPE C,
     TELEFONO2(30) TYPE C,
     MOVIL(30) TYPE C,
     PREVISION(2) TYPE C,
     ESTADOCIVIL(2) TYPE C,
     SEXO(2) TYPE C,
     CATCLIENTE(2) TYPE C,
     RANGOETAREO(2) TYPE C,
     PERFILCOBRANZA(3) TYPE C,
     RENTABILIDAD(3) TYPE C,
     PROFESION(3) TYPE C,
     CARGO(3) TYPE C,
     RUT2(16) TYPE C,
     CUENTAASOCIADA(10) TYPE C,
     CLAVECLASIF(3) TYPE C,
     GRUPOTESORERIA(10) TYPE C,
     CONDICIONPAGO(4) TYPE C,
     VIAPAGO(10) TYPE C,
     GRABARHPAGOS(1) TYPE C,
     BANCOPROPIO(5) TYPE C,
     CONDPAGO(4) TYPE C,
     GRUPOIMPUTACION(2) TYPE C,
     CLASIFFISCAL(1) TYPE C,
     TEXTO1(40) TYPE C,
     TEXTO2(40) TYPE C,
  END OF STR_FILE.
DATA TI_FILE TYPE STANDARD TABLE OF STR_FILE WITH HEADER LINE.

PARAMETERS P_FILE LIKE RLGRAP-FILENAME LOWER CASE.
SELECTION-SCREEN SKIP.
SELECTION-SCREEN BEGIN OF BLOCK B_TPO WITH FRAME TITLE TEXT-P01.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 3(22) TEXT-SVR.
PARAMETERS PATH_O TYPE C LENGTH 60 LOWER CASE default '/tmp/'.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN COMMENT 7(18) TEXT-N_F.
PARAMETERS FILE_O LIKE FILENAME-FILEEXTERN LOWER CASE.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B_TPO.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_FILE.
  CALL FUNCTION 'WS_FILENAME_GET'
    EXPORTING
      DEF_FILENAME     = '*.txt'
      DEF_PATH         = 'C:\'
      MASK             = ',*.txt.'
      MODE             = 'O'
      TITLE            = TEXT-C12
    IMPORTING
      FILENAME         = P_FILE
    EXCEPTIONS
      INV_WINSYS       = 01
      NO_BATCH         = 02
      SELECTION_CANCEL = 03
      SELECTION_ERROR  = 04.

START-OF-SELECTION.
  CALL FUNCTION 'TEXT_CONVERT_XLS_TO_SAP'
    EXPORTING
      I_LINE_HEADER        = 'X'
      I_TAB_RAW_DATA       = IT_RAW
      I_FILENAME           = P_FILE
    TABLES
      I_TAB_CONVERTED_DATA = TI_FILE[]
    EXCEPTIONS
      CONVERSION_FAILED    = 1
      OTHERS               = 2.

  CONCATENATE PATH_O FILE_O INTO SERVER_NAME.
  OPEN DATASET SERVER_NAME FOR OUTPUT IN TEXT MODE ENCODING DEFAULT.
  IF SY-SUBRC EQ 0.
    LOOP AT TI_FILE.
      TRANSFER TI_FILE TO SERVER_NAME.
      IF SY-SUBRC NE 0.
        MESSAGE E899(FI) WITH 'No se pudo escribir en el archivo:'
                              SERVER_NAME.
        EXIT.
      ENDIF.
    ENDLOOP.
    CLOSE DATASET SERVER_NAME.
    MESSAGE E899(FI)
    WITH 'Proceso finalizado. Verificar en transacción AL11'
         'La existencia del archivo:' SERVER_NAME.
  ELSE.
    MESSAGE E899(FI) WITH 'No se pudo acceder al archivo:' SERVER_NAME.
  ENDIF.
