*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZNC_ESPECIAL_BANTOP.              " Global Data
  INCLUDE LZNC_ESPECIAL_BANUXX.              " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZNC_ESPECIAL_BANF00                    . " subprograms
  INCLUDE LZNC_ESPECIAL_BANI00                    . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZNC_ESPECIAL_BANF...              " Subprograms
* INCLUDE LZNC_ESPECIAL_BANO...              " PBO-Modules
* INCLUDE LZNC_ESPECIAL_BANI...              " PAI-Modules
