PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZNC_ESPECIAL_BAN CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZNC_ESPECIAL_BAN-SOCIEDAD .
    FIELD ZNC_ESPECIAL_BAN-NUMERO .
    FIELD ZNC_ESPECIAL_BAN-BLART .
    FIELD ZNC_ESPECIAL_BAN-FECHA .
    FIELD ZNC_ESPECIAL_BAN-NOMBRE .
    FIELD ZNC_ESPECIAL_BAN-MONEDA .
    FIELD ZNC_ESPECIAL_BAN-RUT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZNC_ESPECIAL_BAN-SOCIEDAD .
    FIELD ZNC_ESPECIAL_BAN-NUMERO .
    FIELD ZNC_ESPECIAL_BAN-BLART .
    FIELD ZNC_ESPECIAL_BAN-FECHA .
    FIELD ZNC_ESPECIAL_BAN-NOMBRE .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
