*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZPRESTACIONTOP.                   " Global Data
  INCLUDE LZPRESTACIONUXX.                   " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZPRESTACIONF00                         . " subprograms
  INCLUDE LZPRESTACIONI00                         . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZPRESTACIONF...                   " Subprograms
* INCLUDE LZPRESTACIONO...                   " PBO-Modules
* INCLUDE LZPRESTACIONI...                   " PAI-Modules
