*&---------------------------------------------------------------------*
*& Report  ZPROC_DEL_REG_CORE
*&
*&---------------------------------------------------------------------*
*&
*&
*&---------------------------------------------------------------------*

REPORT ZPROC_DEL_REG_CORE.

TABLES ZCABPEDEXT.
TABLES ZDETPEDEXT.
TABLES ZSTR_MON_FAC.

DATA TI_CABPEDEXT TYPE STANDARD TABLE OF ZCABPEDEXT WITH HEADER LINE.

RANGES R_FECFACCON FOR ZCABPEDEXT-FECFACCON.
DATA TMP_DATE LIKE SY-DATUM.

SELECTION-SCREEN BEGIN OF BLOCK ONLINE WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS SO_NC FOR ZCABPEDEXT-ZNUM_DOC_CORE.
SELECTION-SCREEN END OF BLOCK ONLINE.

START-OF-SELECTION.

  SELECT * FROM ZCABPEDEXT WHERE ZNUM_DOC_CORE IN SO_NC.
    SELECT * FROM ZDETPEDEXT
      WHERE ZNUM_DOC_CORE EQ ZCABPEDEXT-ZNUM_DOC_CORE.
      MOVE-CORRESPONDING ZCABPEDEXT TO TI_CABPEDEXT.
      APPEND TI_CABPEDEXT.
      DELETE FROM ZCABPEDEXT
       WHERE ZNUM_DOC_CORE EQ TI_CABPEDEXT-ZNUM_DOC_CORE.
      DELETE FROM ZDETPEDEXT
       WHERE ZNUM_DOC_CORE EQ TI_CABPEDEXT-ZNUM_DOC_CORE.
      CLEAR TI_CABPEDEXT.
    ENDSELECT.
  ENDSELECT.

END-OF-SELECTION.

  WRITE:/ TEXT-002.
  LOOP AT TI_CABPEDEXT.
    WRITE:/ TI_CABPEDEXT-ZNUM_DOC_CORE.
  ENDLOOP.
