*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZPROV_LCE_BUKTOP.                 " Global Data
  INCLUDE LZPROV_LCE_BUKUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZPROV_LCE_BUKF00                       . " subprograms
  INCLUDE LZPROV_LCE_BUKI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZPROV_LCE_BUKF...                 " Subprograms
* INCLUDE LZPROV_LCE_BUKO...                 " PBO-Modules
* INCLUDE LZPROV_LCE_BUKI...                 " PAI-Modules
