*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZRANGOS_PRESCRITOP.               " Global Data
  INCLUDE LZRANGOS_PRESCRIUXX.               " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZRANGOS_PRESCRIF00                     . " subprograms
  INCLUDE LZRANGOS_PRESCRII00                     . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZRANGOS_PRESCRIF...               " Subprograms
* INCLUDE LZRANGOS_PRESCRIO...               " PBO-Modules
* INCLUDE LZRANGOS_PRESCRII...               " PAI-Modules
