PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZREVERSACHEQUE CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZREVERSACHEQUE-CODUSUARIO .
    FIELD ZREVERSACHEQUE-BUKRS .
    FIELD ZREVERSACHEQUE-HBKID .
    FIELD ZREVERSACHEQUE-HKTID .
    FIELD ZREVERSACHEQUE-BUDAT .
    FIELD ZREVERSACHEQUE-ESTREVER .
    FIELD ZREVERSACHEQUE-VBLNR .
    FIELD ZREVERSACHEQUE-BELNR .
    FIELD ZREVERSACHEQUE-BUZEI .
    FIELD ZREVERSACHEQUE-GJAHR .
    FIELD ZREVERSACHEQUE-FECPROCESO .
    FIELD ZREVERSACHEQUE-HORAPROCESO .
    FIELD ZREVERSACHEQUE-HKONT .
    FIELD ZREVERSACHEQUE-WRBTR .
    FIELD ZREVERSACHEQUE-WAERS .
    FIELD ZREVERSACHEQUE-CHECT .
    FIELD ZREVERSACHEQUE-HKONTD .
    FIELD ZREVERSACHEQUE-ESTADO .
    FIELD ZREVERSACHEQUE-BLDAT .
    FIELD ZREVERSACHEQUE-LIFNR .
    FIELD ZREVERSACHEQUE-ZALDT .
    FIELD ZREVERSACHEQUE-ZMOTE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZREVERSACHEQUE-CODUSUARIO .
    FIELD ZREVERSACHEQUE-BUKRS .
    FIELD ZREVERSACHEQUE-HBKID .
    FIELD ZREVERSACHEQUE-HKTID .
    FIELD ZREVERSACHEQUE-BUDAT .
    FIELD ZREVERSACHEQUE-ESTREVER .
    FIELD ZREVERSACHEQUE-VBLNR .
    FIELD ZREVERSACHEQUE-BELNR .
    FIELD ZREVERSACHEQUE-BUZEI .
    FIELD ZREVERSACHEQUE-GJAHR .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
