PROCESS BEFORE OUTPUT.
  MODULE D1400_INIT.
  MODULE FILL_BDC_PROTOCOL.
  LOOP AT BDC_PROTOCOL WITH CONTROL TC_PROT_DIS
              CURSOR TC_PROT_DIS-CURRENT_LINE.
    MODULE CHECK_BDC_PROTOCOL.
  ENDLOOP.
*
PROCESS AFTER INPUT.
  MODULE D1400_GET_CURSOR.
  LOOP AT BDC_PROTOCOL.
  ENDLOOP.
  MODULE D1400_PCODE.
