PROCESS BEFORE OUTPUT.
  MODULE D1600_INIT.
* MODULE FILL_DEL_PROTOCOL.
  LOOP AT DEL_PROTOCOL WITH CONTROL TC_PROT_DEL
          CURSOR TC_PROT_DEL-CURRENT_LINE.
*   MODULE SET_MARK.
  ENDLOOP.
*
PROCESS AFTER INPUT.
  LOOP AT DEL_PROTOCOL.
*   MODULE GET_MARK.
  ENDLOOP.
  MODULE D1600_FCODE.
