PROCESS BEFORE OUTPUT.
  MODULE D0100_INIT_MAIN.
  CALL SUBSCREEN SCR_INFO
                 INCLUDING 'ZRSBDC_PROTOCOL' HEADER_SUBSCREEN_DYNPRO.
  CALL SUBSCREEN SCR_CONTENT
                 INCLUDING 'ZRSBDC_PROTOCOL' DYNPROTAB_SUBSCREEN_DYNPRO.

*
PROCESS AFTER INPUT.
  MODULE EXIT_MAIN AT EXIT-COMMAND.
  CALL SUBSCREEN SCR_INFO.
  CALL SUBSCREEN SCR_CONTENT.
  MODULE USER_COMMAND_MAIN.
