PROCESS BEFORE OUTPUT.
  MODULE STATUS_0001.
*
PROCESS AFTER INPUT.
    CHAIN.
      FIELD IUSER_DIR-DIRNAME.
      FIELD IUSER_DIR-SVRNAME.
      FIELD IUSER_DIR-ALIASS.
        MODULE CHANGE_VALUES ON CHAIN-REQUEST.
    ENDCHAIN.

  MODULE USER_COMMAND_0001.

PROCESS ON VALUE-REQUEST.
    field iuser_dir-dirname module show_user_dir.
