*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZRUT_TERCTOP.                     " Global Data
  INCLUDE LZRUT_TERCUXX.                     " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZRUT_TERCF00                           . " subprograms
  INCLUDE LZRUT_TERCI00                           . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZRUT_TERCF...                     " Subprograms
* INCLUDE LZRUT_TERCO...                     " PBO-Modules
* INCLUDE LZRUT_TERCI...                     " PAI-Modules
