PROCESS BEFORE OUTPUT.
  MODULE INIT_SUBSCREEN.
  MODULE CLEAR_ITAB_SELECTED.
  LOOP AT ITAB_APQI WITH CONTROL TC_APQI.
    MODULE FILL_TC.
  ENDLOOP.
*
PROCESS AFTER INPUT.
  MODULE GET_TC_CURSOR.
  LOOP AT ITAB_APQI.
    MODULE EXTRACT_SELECTED.
  ENDLOOP.
  MODULE COPY_SELECTIONS_TO_MTAB.
