PROCESS BEFORE OUTPUT.
  MODULE D0300_INIT.
*
PROCESS AFTER INPUT.
  CHAIN.
    FIELD: D0300-HELL, D0300-ERROR, D0300-BATCH.
    MODULE D0300_START.
  ENDCHAIN.
*
PROCESS ON VALUE-REQUEST.
   FIELD D0300-BATCHSYS MODULE  SHOW_TARGET_SYSTEMS.




