PROCESS BEFORE OUTPUT.
*
  MODULE D1050_STATUS.
  LOOP AT MTAB WITH CONTROL TC_MTAB.
  ENDLOOP.
*
PROCESS AFTER INPUT.
*
  LOOP AT MTAB.
  ENDLOOP.
  MODULE D1050_FCODE.
*
PROCESS ON VALUE-REQUEST.
*
  FIELD D0300-BATCHSYS MODULE SHOW_TARGET_SYSTEMS.
