REPORT ZSDBICONTRATO NO STANDARD PAGE HEADING LINE-SIZE 255.

TABLES ZSD_CONTRATO.
TYPE-POOLS TRUXS.
TYPES BEGIN OF STR_FILE.
        INCLUDE STRUCTURE ZSD_CONTRATO.
TYPES END OF STR_FILE.

CONSTANTS CLASE_CONTRATO TYPE C LENGTH 010 VALUE 'ZCONTRATOS'.

DATA BDCDATA    TYPE STANDARD TABLE OF BDCDATA.
DATA MESSTAB    TYPE STANDARD TABLE OF BDCMSGCOLL.
DATA T_LOG      TYPE STANDARD TABLE OF BDCMSGCOLL.
DATA T_LINES    TYPE STANDARD TABLE OF TLINE.
DATA TI_FILE    TYPE STANDARD TABLE OF STR_FILE WITH HEADER LINE.
DATA CTUMODE    TYPE CTU_MODE   VALUE 'N'.
DATA CUPDATE    TYPE CTU_UPDATE VALUE 'L'.
DATA G_REGINDEX TYPE C LENGTH 10.
DATA GS_LINES   LIKE LINE OF T_LINES.
DATA GS_THEAD   TYPE THEAD  .
DATA IT_RAW     TYPE TRUXS_T_TEXT_DATA.
DATA LS_BDC     LIKE LINE OF BDCDATA.
DATA LS_LOG     LIKE LINE OF T_LOG.
DATA LS_MESS    LIKE LINE OF MESSTAB.
DATA L_MESSAGE  TYPE BAPI_MSG.
DATA TMP_FEC    TYPE C LENGTH 10.

**************************************************************************
***********************************************************************
DATA VC_CLOCKTLINES TYPE I.
DATA VC_TIME0 TYPE F.
***********************************************************************
DEFINE VC_SECONDS2HMS.
  PERFORM VC_SECONDS2HMS USING &1 CHANGING &2.
END-OF-DEFINITION.
*
FORM VC_SECONDS2HMS USING PSECONDS CHANGING PHMS.
  DATA VC_SEGUNDOS TYPE UZEIT.
  DATA VC_SEGUNDOSI TYPE I.
  VC_SEGUNDOSI = PSECONDS.
  IF VC_SEGUNDOSI < 360000.
    VC_SEGUNDOS = VC_SEGUNDOSI.
    WRITE VC_SEGUNDOS TO PHMS.
  ELSE.
    PHMS = '+100h'.
  ENDIF.
ENDFORM.                    "vc_seconds2hms
***********************************************************************
DEFINE VC_CLOCKRESET.
  VC_CLOCKTLINES = 0.
  DESCRIBE TABLE &1 LINES VC_CLOCKTLINES.
  GET RUN TIME FIELD VC_TIME0.
END-OF-DEFINITION.
***********************************************************************
DEFINE VC_CLOCKTIMER.
  PERFORM VC_CLOCKTIMER USING &1.
END-OF-DEFINITION.
*
FORM VC_CLOCKTIMER USING VC_PTEXTO.

  DATA VC_PORCENTAJE TYPE I.
  DATA VC_PORCENTAJET(4).
  DATA VC_PEND TYPE F.
  DATA VC_TABIXT(8).
  DATA VC_TFILLT(8).
  DATA VC_LINEST(20).

  DATA VC_TIME TYPE F.
  DATA VC_TIMETOTAL TYPE F.
  DATA VC_TIMETOTALT(8).
  DATA VC_TIMEFALTA TYPE F.
  DATA VC_TIMEFALTAT(8).
  DATA VC_TIMEFIN TYPE UZEIT.
  DATA VC_TIMEFINT(8).
  DATA VC_MENSAJE(100).

  CHECK VC_CLOCKTLINES > 0.
  CHECK SY-TABIX > 0.

  GET RUN TIME FIELD VC_TIME.

  VC_PEND = ( VC_TIME - VC_TIME0 ) / SY-TABIX .
  VC_TIMETOTAL = VC_PEND * VC_CLOCKTLINES / 1000000.
  VC_TIMEFALTA = VC_PEND * ( VC_CLOCKTLINES - SY-TABIX ) / 1000000 + 1.
  VC_PORCENTAJE = SY-TABIX * 100 / VC_CLOCKTLINES.

  WRITE VC_PORCENTAJE TO VC_PORCENTAJET.
  CONCATENATE VC_PORCENTAJET '%' INTO VC_PORCENTAJET.
  CONDENSE VC_PORCENTAJET NO-GAPS.
  WRITE SY-TABIX TO VC_TABIXT.
  WRITE VC_CLOCKTLINES TO VC_TFILLT.
  CONCATENATE '[' VC_TABIXT '/' VC_TFILLT ']' INTO VC_LINEST.
  CONDENSE VC_LINEST NO-GAPS.
  VC_SECONDS2HMS VC_TIMETOTAL VC_TIMETOTALT.
  VC_SECONDS2HMS VC_TIMEFALTA VC_TIMEFALTAT.
  VC_TIMEFIN = SY-UZEIT + VC_TIMEFALTA.
  WRITE VC_TIMEFIN TO VC_TIMEFINT.

  CONCATENATE
    VC_PTEXTO
    VC_PORCENTAJET
    'Total'
    VC_TIMETOTALT
    'Resta'
    VC_TIMEFALTAT
    'Final'
    VC_TIMEFINT
    VC_LINEST
  INTO VC_MENSAJE SEPARATED BY SPACE.
  CONDENSE VC_MENSAJE.

  CALL FUNCTION 'SAPGUI_PROGRESS_INDICATOR'
    EXPORTING
      PERCENTAGE = VC_PORCENTAJE
      TEXT       = VC_MENSAJE.
ENDFORM.                    "vc_clocktimer
***********************************************************************
**************************************************************************

PARAMETERS P_FILE LIKE RLGRAP-FILENAME.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_FILE.

  CALL FUNCTION 'WS_FILENAME_GET'
    EXPORTING
      DEF_FILENAME     = '*.xls*'
      DEF_PATH         = 'C:\'
      MASK             = ',*.txt.'
      MODE             = 'O'
      TITLE            = TEXT-C12
    IMPORTING
      FILENAME         = P_FILE
    EXCEPTIONS
      INV_WINSYS       = 01
      NO_BATCH         = 02
      SELECTION_CANCEL = 03
      SELECTION_ERROR  = 04.

START-OF-SELECTION.
  DATA STR_FILE TYPE STRING.
  DATA LIN TYPE I.
  DATA PORCENTAJE TYPE I.
  DATA MENSAJE TYPE STRING.

  TYPE-POOLS: TRUXS.
*  DATA: IT_RAW TYPE TRUXS_T_TEXT_DATA.
  DATA STR_POR TYPE STRING.
  FIELD-SYMBOLS <FS> TYPE STANDARD TABLE.

  ASSIGN TI_FILE[] TO <FS>.

  CALL FUNCTION 'TEXT_CONVERT_XLS_TO_SAP'
    EXPORTING
*     I_FIELD_SEPERATOR        =
      I_LINE_HEADER            =  'X'
      I_TAB_RAW_DATA           =  IT_RAW       " WORK TABLE
      I_FILENAME               =  P_FILE
    TABLES
      I_TAB_CONVERTED_DATA     = <FS>    "ACTUAL DATA
   EXCEPTIONS
      CONVERSION_FAILED        = 1
      OTHERS                   = 2.

  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ELSE.
    IF <FS> IS INITIAL.
      SY-SUBRC = 4.
      MESSAGE 'No existen registros para procesar'(002) TYPE 'I'.
    ENDIF.
  ENDIF.

  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ELSE.
    DELETE TI_FILE WHERE VKORG EQ SPACE.
    CLEAR: LIN, PORCENTAJE.
    DESCRIBE TABLE TI_FILE LINES LIN.
    LOOP AT TI_FILE.

      ADD 1 TO G_REGINDEX.
      PORCENTAJE = ( 100 * G_REGINDEX ) / LIN.
      CLEAR MENSAJE.
      STR_POR = PORCENTAJE.
      CONCATENATE 'Porcentaj de avance del proceso' STR_POR '%' INTO MENSAJE SEPARATED BY SPACE.
      CALL FUNCTION 'SAPGUI_PROGRESS_INDICATOR'
        EXPORTING
          PERCENTAGE = PORCENTAJE
          TEXT       = MENSAJE.
      FREE BDCDATA.
      CLEAR BDCDATA.
      PERFORM BDC_DYNPRO USING 'SAPMF02D'           '0100'.
      PERFORM BDC_FIELD  USING 'BDC_CURSOR'         'USE_ZAV'.
      PERFORM BDC_FIELD  USING 'BDC_OKCODE'         '/00'.
      PERFORM BDC_FIELD  USING 'RF02D-VKORG'        TI_FILE-VKORG.
      PERFORM BDC_FIELD  USING 'RF02D-VTWEG'        TI_FILE-VTWEG.
      PERFORM BDC_FIELD  USING 'RF02D-SPART'        TI_FILE-SPART.
      PERFORM BDC_FIELD  USING 'RF02D-KTOKD'        TI_FILE-KTOKD.
      PERFORM BDC_FIELD  USING 'USE_ZAV'            'X'.

      PERFORM BDC_DYNPRO USING 'SAPMF02D'           '0111'.
      PERFORM BDC_FIELD  USING 'BDC_OKCODE'         '/00'.
      PERFORM BDC_FIELD  USING 'BDC_CURSOR'         'ADDR1_DATA-COUNTRY'.
      PERFORM BDC_FIELD  USING 'ADDR1_DATA-NAME1'   TI_FILE-NAME1.
      PERFORM BDC_FIELD  USING 'ADDR1_DATA-SORT2'   TI_FILE-SORT2.
      PERFORM BDC_FIELD  USING 'ADDR1_DATA-COUNTRY' TI_FILE-COUNTRY.
      PERFORM BDC_FIELD  USING 'ADDR1_DATA-LANGU'   SY-LANGU.

      PERFORM BDC_DYNPRO USING 'SAPMF02D'           '0310'.
      PERFORM BDC_FIELD  USING 'BDC_CURSOR'         'KNVV-WAERS'.
      PERFORM BDC_FIELD  USING 'BDC_OKCODE'         '/00'.
      PERFORM BDC_FIELD  USING 'KNVV-WAERS'         'CLP'.

      PERFORM BDC_DYNPRO USING 'SAPMF02D'           '0324'.
      PERFORM BDC_FIELD  USING 'BDC_CURSOR'         'KNVP-PARVW(01)'.
      PERFORM BDC_FIELD  USING 'BDC_OKCODE'         '=KLAS'.

      PERFORM BDC_DYNPRO USING 'SAPLCLCA'           '0602'.
      PERFORM BDC_FIELD  USING 'BDC_CURSOR'         'RMCLF-KLART'.
      PERFORM BDC_FIELD  USING 'BDC_OKCODE'         '=ENTE'.
      PERFORM BDC_FIELD  USING 'RMCLF-KLART'        '011'.

      PERFORM BDC_DYNPRO USING 'SAPLCLFM'           '0500'.
      PERFORM BDC_FIELD  USING 'BDC_CURSOR'         'RMCLF-CLASS(01)'.
      PERFORM BDC_FIELD  USING 'BDC_OKCODE'         '/00'.
      PERFORM BDC_FIELD  USING 'RMCLF-CLASS(01)'    CLASE_CONTRATO.

      PERFORM BDC_DYNPRO USING 'SAPLCTMS'           '0109'.
      PERFORM BDC_FIELD  USING 'BDC_CURSOR'         'RCTMS-MWERT(10)'.
      PERFORM BDC_FIELD  USING 'BDC_OKCODE'         '=BACK'.
*
      PERFORM BDC_FIELD  USING 'RCTMS-MNAME(01)'    'ZFEC_SUSCRIPCION'.
      PERFORM BDC_FIELD  USING 'RCTMS-MWERT(01)'    TI_FILE-FEC_SUS.
*
      PERFORM BDC_FIELD  USING 'RCTMS-MNAME(02)'    'ZFEC_CAJA'.
      PERFORM BDC_FIELD  USING 'RCTMS-MWERT(02)'    TI_FILE-FEC_CAJ.
*
      PERFORM BDC_FIELD  USING 'RCTMS-MNAME(03)'    'ZRUT_VENDEDOR'.
      PERFORM BDC_FIELD  USING 'RCTMS-MWERT(03)'    TI_FILE-RUT_VEN.
*
      PERFORM BDC_FIELD  USING 'RCTMS-MNAME(04)'    'ZMONEDA'.
      PERFORM BDC_FIELD  USING 'RCTMS-MWERT(04)'    TI_FILE-MONEDA.
*
      PERFORM BDC_FIELD  USING 'RCTMS-MNAME(05)'    'ZGRUPO_VENTA'.
      PERFORM BDC_FIELD  USING 'RCTMS-MWERT(05)'    TI_FILE-GRP_VTA.
*
      PERFORM BDC_FIELD  USING 'RCTMS-MNAME(06)'    'ZCOMPANIA'.
      PERFORM BDC_FIELD  USING 'RCTMS-MWERT(06)'    TI_FILE-COMPANIA.
*
      PERFORM BDC_FIELD  USING 'RCTMS-MNAME(07)'    'ZMCPA'.
      PERFORM BDC_FIELD  USING 'RCTMS-MWERT(07)'    TI_FILE-ZMCPA.
*
      PERFORM BDC_FIELD  USING 'RCTMS-MNAME(08)'    'ZPACCR'.
      PERFORM BDC_FIELD  USING 'RCTMS-MWERT(08)'    TI_FILE-ZPACCR.
*
      PERFORM BDC_FIELD  USING 'RCTMS-MNAME(09)'    'ZBETA'.
      PERFORM BDC_FIELD  USING 'RCTMS-MWERT(09)'    TI_FILE-ZBETA.
*
      PERFORM BDC_FIELD  USING 'RCTMS-MNAME(10)'    'ZMCOB'.
      PERFORM BDC_FIELD  USING 'RCTMS-MWERT(10)'    TI_FILE-ZMCOB.
*
      PERFORM BDC_DYNPRO USING 'SAPLCLFM'           '0500'.
      PERFORM BDC_FIELD  USING 'BDC_CURSOR'         'RMCLF-CLASS(01)'.
      PERFORM BDC_FIELD  USING 'BDC_OKCODE'         '=AUSW'.
      PERFORM BDC_FIELD  USING 'RMCLF-PAGPOS'       '1'.
      PERFORM BDC_FIELD  USING 'RMCLF-KREUZ(01)'    'X'.

      PERFORM BDC_DYNPRO USING 'SAPLCTMS'           '0109'.
      PERFORM BDC_FIELD  USING 'BDC_CURSOR'         'RCTMS-MWERT(10)'.
      PERFORM BDC_FIELD  USING 'BDC_OKCODE'         'BACK'.
*
      PERFORM BDC_FIELD  USING 'RCTMS-MNAME(01)'    'ZOMEGA'.
      PERFORM BDC_FIELD  USING 'RCTMS-MWERT(01)'    TI_FILE-ZOMEGA.
*
      PERFORM BDC_FIELD  USING 'RCTMS-MNAME(02)'    'ZALFA'.
      PERFORM BDC_FIELD  USING 'RCTMS-MWERT(02)'    TI_FILE-ZALFA.
*
      PERFORM BDC_FIELD  USING 'RCTMS-MNAME(03)'    'ZREAJUSTE_IPC'.
      PERFORM BDC_FIELD  USING 'RCTMS-MWERT(03)'    TI_FILE-ZREAJUSTE_IPC.
*
      PERFORM BDC_FIELD  USING 'RCTMS-MNAME(04)'    'ZREAJUSTE_TARIFA'.
      PERFORM BDC_FIELD  USING 'RCTMS-MWERT(04)'    TI_FILE-ZREAJUSTE_TARIFA.
*
      PERFORM BDC_FIELD  USING 'RCTMS-MNAME(05)'    'ZNUMERO_CONVENIO'.
      PERFORM BDC_FIELD  USING 'RCTMS-MWERT(05)'    TI_FILE-ZNUM_CONVENIO.
*
      PERFORM BDC_FIELD  USING 'RCTMS-MNAME(06)'    'ZVERSION_CONVENIO'.
      PERFORM BDC_FIELD  USING 'RCTMS-MWERT(06)'    TI_FILE-ZVER_CONVENIO.
*
      PERFORM BDC_FIELD  USING 'RCTMS-MNAME(07)'    'ZRUT_PAGADOR'.
      PERFORM BDC_FIELD  USING 'RCTMS-MWERT(07)'    TI_FILE-ZRUT_PAG.
*
      PERFORM BDC_FIELD  USING 'RCTMS-MNAME(08)'    'ZSISTEMA_PAGO'.
      PERFORM BDC_FIELD  USING 'RCTMS-MWERT(08)'    TI_FILE-ZSIS_PAGO.
*
      PERFORM BDC_FIELD  USING 'RCTMS-MNAME(09)'    'ZMARCA1'.
      PERFORM BDC_FIELD  USING 'RCTMS-MWERT(09)'    TI_FILE-ZMARCA1.
*
      PERFORM BDC_FIELD  USING 'RCTMS-MNAME(10)'    'ZMARCA2'.
      PERFORM BDC_FIELD  USING 'RCTMS-MWERT(10)'    TI_FILE-ZMARCA2.
*
      PERFORM BDC_DYNPRO USING 'SAPLCLFM'           '0500'.
      PERFORM BDC_FIELD  USING 'BDC_CURSOR'         'RMCLF-CLASS(01)'.
      PERFORM BDC_FIELD  USING 'BDC_OKCODE'         '=AUSW'.
      PERFORM BDC_FIELD  USING 'RMCLF-PAGPOS'       '1'.
      PERFORM BDC_FIELD  USING 'RMCLF-KREUZ(01)'    'X'.

      PERFORM BDC_DYNPRO USING 'SAPLCTMS'           '0109'.
      PERFORM BDC_FIELD  USING 'BDC_CURSOR'         'RCTMS-MWERT(02)'.
      PERFORM BDC_FIELD  USING 'BDC_OKCODE'         '=BACK'.
*
      PERFORM BDC_FIELD  USING 'RCTMS-MNAME(01)'    'ZMARCA3'.
      PERFORM BDC_FIELD  USING 'RCTMS-MWERT(01)'    TI_FILE-ZMARCA3.
*
      PERFORM BDC_FIELD  USING 'RCTMS-MNAME(02)'    'ZTIPO_PLAN'.
      PERFORM BDC_FIELD  USING 'RCTMS-MWERT(02)'    TI_FILE-ZTIPO_PLAN.
*
      PERFORM BDC_DYNPRO USING 'SAPLCLFM'           '0500'.
      PERFORM BDC_FIELD  USING 'BDC_CURSOR'         'RMCLF-CLASS(01)'.
      PERFORM BDC_FIELD  USING 'BDC_OKCODE'         '=ENDE'.
      PERFORM BDC_FIELD  USING 'RMCLF-PAGPOS'       '1'.

      PERFORM BDC_DYNPRO USING 'SAPMF02D'           '0324'.
      PERFORM BDC_FIELD  USING 'BDC_CURSOR'         'KNVP-PARVW(01)'.
      PERFORM BDC_FIELD  USING 'BDC_OKCODE'         '=UPDA'.

      FREE MESSTAB.
      CALL TRANSACTION 'XD01' USING BDCDATA
                       MODE   CTUMODE
                       UPDATE CUPDATE
                       MESSAGES INTO MESSTAB.

      CLEAR LS_MESS.
      READ TABLE MESSTAB INTO LS_MESS WITH KEY MSGTYP = 'S'
                                  MSGID = 'F2'
                                  MSGNR = '172'.
      IF SY-SUBRC EQ 0.
        LS_LOG-MSGTYP = LS_MESS-MSGTYP.
        LS_LOG-MSGID = '00'.
        LS_LOG-MSGNR = '398'.
        LS_LOG-MSGV1 = G_REGINDEX .
        CONCATENATE 'El deudor' LS_MESS-MSGV1 INTO LS_LOG-MSGV2 SEPARATED BY SPACE.
        APPEND LS_LOG TO T_LOG.
        PERFORM ACTUALIZAR_TEXTOS USING LS_MESS-MSGV1.
      ELSE.
        READ TABLE MESSTAB INTO LS_MESS WITH KEY MSGTYP = 'E'.
        IF SY-SUBRC NE 0.
          READ TABLE MESSTAB INTO LS_MESS WITH KEY MSGTYP = 'A'.
        ENDIF.
        IF SY-SUBRC EQ 0.
          MESSAGE ID LS_MESS-MSGID TYPE LS_MESS-MSGTYP NUMBER LS_MESS-MSGNR
            INTO L_MESSAGE
            WITH LS_MESS-MSGV1 LS_MESS-MSGV2 LS_MESS-MSGV3 LS_MESS-MSGV4.
          CONDENSE L_MESSAGE.
          LS_LOG-MSGTYP = LS_MESS-MSGTYP.
          LS_LOG-MSGID  = '00'.
          LS_LOG-MSGNR  = '398'.
          LS_LOG-MSGV1  = G_REGINDEX .
          LS_LOG-MSGV2  = L_MESSAGE(100).
          LS_LOG-MSGV3  = L_MESSAGE+100(100).
          APPEND LS_LOG TO T_LOG.
        ENDIF.
      ENDIF.
    ENDLOOP.
  ENDIF.

END-OF-SELECTION.
  IF T_LOG IS NOT INITIAL.
    PERFORM DISPLAY_LOG.
  ENDIF.

*----------------------------------------------------------------------*
*        Start new screen                                              *
*----------------------------------------------------------------------*
FORM BDC_DYNPRO USING PROGRAM DYNPRO.
  CLEAR LS_BDC.
  LS_BDC-PROGRAM  = PROGRAM.
  LS_BDC-DYNPRO   = DYNPRO.
  LS_BDC-DYNBEGIN = 'X'.
  APPEND LS_BDC TO BDCDATA.
ENDFORM.                    "BDC_DYNPRO

*----------------------------------------------------------------------*
*        Insert field                                                  *
*----------------------------------------------------------------------*
FORM BDC_FIELD USING FNAM FVAL.

  CLEAR LS_BDC.
  LS_BDC-FNAM = FNAM.
  LS_BDC-FVAL = FVAL.
  APPEND LS_BDC TO BDCDATA.

ENDFORM.                    "BDC_FIELD
*&---------------------------------------------------------------------*
*&      Form  ACTUALIZAR_TEXTOS
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM ACTUALIZAR_TEXTOS USING CONTRATO.

  CLEAR GS_THEAD.
  CLEAR GS_LINES.
  REFRESH T_LINES.

  GS_THEAD-TDOBJECT = 'KNA1'.
  GS_THEAD-TDNAME   = CONTRATO.
  GS_THEAD-TDID     = 'Z001'.
  GS_THEAD-TDSPRAS  = SY-LANGU.

*  GS_LINES-TDFORMAT = '*'.
*  GS_LINES-TDLINE   = WA_DATA-TEXTO1.
*  APPEND GS_LINES TO T_LINES.

  CALL FUNCTION 'SAVE_TEXT'
    EXPORTING
      HEADER          = GS_THEAD
      SAVEMODE_DIRECT = 'X'
    TABLES
      LINES           = T_LINES
    EXCEPTIONS
      ID              = 1
      LANGUAGE        = 2
      NAME            = 3
      OBJECT          = 4
      OTHERS          = 5.

  IF SY-SUBRC <> 0.
    PERFORM ADD_SY_MESS_TO_LOG.
  ELSE.
    LS_LOG-MSGTYP = 'I'.
    LS_LOG-MSGID = '00'.
    LS_LOG-MSGNR = '398'.
    LS_LOG-MSGV1 = G_REGINDEX .
    LS_LOG-MSGV2 = 'Texto1 Cliente'.
    LS_LOG-MSGV3 = CONTRATO.
    LS_LOG-MSGV4 = 'actualizado con exito'.
    APPEND LS_LOG TO T_LOG.
  ENDIF.

ENDFORM.                    " ACTUALIZAR_TEXTOS
*&---------------------------------------------------------------------*
*&      Form  ADD_SY_MESS_TO_LOG
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM ADD_SY_MESS_TO_LOG .

  LS_LOG-MSGTYP  = SY-MSGTY.
  LS_LOG-MSGSPRA = SY-LANGU.
  LS_LOG-MSGID   =  SY-MSGID.
  LS_LOG-MSGNR   = SY-MSGNO.
  LS_LOG-MSGV1   = SY-MSGV1.
  LS_LOG-MSGV2   = SY-MSGV2.
  LS_LOG-MSGV3   = SY-MSGV3.
  LS_LOG-MSGV4   =  SY-MSGV3.
  APPEND  LS_LOG TO T_LOG.

ENDFORM.                    " ADD_SY_MESS_TO_LOG
*&---------------------------------------------------------------------*
*&      Form  DISPLAY_LOG
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*  -->  p1        text
*  <--  p2        text
*----------------------------------------------------------------------*
FORM DISPLAY_LOG .

  DATA: LS_HEADER     TYPE BALHDRI,
        LF_LOG_HANDLE TYPE BALLOGHNDL,
        LF_LOG_NUMBER TYPE BALOGNR,
        LT_MSG        TYPE BALMI_TAB,
        LS_MSG        TYPE BALMI,
        LT_LOGNUM     TYPE TABLE OF BALNRI,
        LS_LOGNUM     TYPE BALNRI.
*
  LS_HEADER-OBJECT     = 'ZSD_LOG'.
  LS_HEADER-SUBOBJECT  = 'Z03'.
  LS_HEADER-ALDATE     = SY-DATUM.
  LS_HEADER-ALTIME     = SY-UZEIT.
  LS_HEADER-ALUSER     = SY-UNAME.
  LS_HEADER-ALDATE_DEL = SY-DATUM + 1.
*
  CALL FUNCTION 'APPL_LOG_WRITE_HEADER'
    EXPORTING
      HEADER              = LS_HEADER
    IMPORTING
      E_LOG_HANDLE        = LF_LOG_HANDLE
    EXCEPTIONS
      OBJECT_NOT_FOUND    = 1
      SUBOBJECT_NOT_FOUND = 2
      ERROR               = 3
      OTHERS              = 4.
  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.

  CALL FUNCTION 'BAL_DB_LOGNUMBER_GET'
    EXPORTING
      I_CLIENT                 = SY-MANDT
      I_LOG_HANDLE             = LF_LOG_HANDLE
    IMPORTING
      E_LOGNUMBER              = LF_LOG_NUMBER
    EXCEPTIONS
      LOG_NOT_FOUND            = 1
      LOGNUMBER_ALREADY_EXISTS = 2
      NUMBERING_ERROR          = 3
      OTHERS                   = 4.
*
  LOOP AT T_LOG INTO LS_MESS.
    MOVE-CORRESPONDING LS_MESS TO LS_MSG.
    MOVE: LS_MESS-MSGTYP TO LS_MSG-MSGTY,
          LS_MESS-MSGNR  TO LS_MSG-MSGNO.
    LS_MSG-MSGV2 = LS_MESS-MSGV2(50).
    LS_MSG-MSGV3 = LS_MESS-MSGV2+50(50).
    APPEND LS_MSG TO LT_MSG.
  ENDLOOP.

  CALL FUNCTION 'APPL_LOG_WRITE_MESSAGES'
    EXPORTING
      OBJECT              = LS_HEADER-OBJECT
      SUBOBJECT           = LS_HEADER-SUBOBJECT
      LOG_HANDLE          = LF_LOG_HANDLE
    TABLES
      MESSAGES            = LT_MSG[]
    EXCEPTIONS
      OBJECT_NOT_FOUND    = 1
      SUBOBJECT_NOT_FOUND = 2
      OTHERS              = 3.
  IF SY-SUBRC <> 0.
    MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
            WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
  ENDIF.
  CALL FUNCTION 'BAL_DSP_LOG_DISPLAY'.

ENDFORM.                    " DISPLAY_LOG
