*&---------------------------------------------------------------------*
*&  Include           ZSDPROCFAC_SCR
*&---------------------------------------------------------------------*

SELECTION-SCREEN BEGIN    OF   BLOCK online WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS   so_n_cor FOR  zcabpedext-znum_doc_core.
SELECT-OPTIONS   so_blart FOR  zstr_mon_fac-zblart.
PARAMETERS       p_monat  LIKE bkpf-monat.
SELECT-OPTIONS   so_fp    FOR  zcabpedext-fecventes.
SELECT-OPTIONS   so_via   FOR  zstr_mon_fac-zlsch.
SELECT-OPTIONS   so_f_c   FOR  zcabpedext-fec_car.
SELECT-OPTIONS   so_h_c   FOR  zcabpedext-hor_car.
SELECTION-SCREEN SKIP.

SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 10.
PARAMETERS       p_spr  AS   CHECKBOX.
SELECTION-SCREEN COMMENT 13(23) TEXT-009 FOR FIELD p_spr.

PARAMETERS       p_error  AS   CHECKBOX.
SELECTION-SCREEN COMMENT 40(21) TEXT-005 FOR FIELD p_error.

PARAMETERS       p_err_e  AS   CHECKBOX.
SELECTION-SCREEN COMMENT 65(28) TEXT-006 FOR FIELD p_err_e.

SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END      OF   BLOCK online.

SELECTION-SCREEN BEGIN    OF   BLOCK statistics WITH FRAME TITLE TEXT-008.
PARAMETERS p_dpc TYPE i.
PARAMETERS p_dpp TYPE i.
PARAMETERS p_des TYPE i.
PARAMETERS p_dea TYPE i.
SELECTION-SCREEN END      OF   BLOCK statistics.

SELECTION-SCREEN BEGIN    OF   BLOCK batch WITH FRAME TITLE TEXT-002.
SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS rb_ol RADIOBUTTON GROUP gr1 USER-COMMAND opc1.
SELECTION-SCREEN COMMENT 5(10) TEXT-003 FOR FIELD rb_ol.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS rb_bi RADIOBUTTON GROUP gr1.
SELECTION-SCREEN COMMENT 5(10)  TEXT-004 FOR FIELD rb_bi.
SELECTION-SCREEN COMMENT 22(17) TEXT-007 FOR FIELD p_npbd.
PARAMETERS p_npbd TYPE i.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END      OF   BLOCK batch.


INITIALIZATION.
  AUTHORITY-CHECK OBJECT 'S_TCODE'
     ID 'TCD' FIELD sy-tcode.
  IF sy-subrc NE 0.
    MESSAGE e077(s#) WITH sy-tcode.
  ENDIF.
