PROGRAM ZSDPROCFAC.

INCLUDE <ICON>.
INCLUDE ZSDPROCFAC_TOP.
INCLUDE ZSDPROCFAC_CLS.
INCLUDE ZSDPROCFAC_SCR.
INCLUDE ZSDPROCFAC_F01.
INCLUDE ZSDPROCFAC_PAI.
INCLUDE ZSDPROCFAC_PBO.

INITIALIZATION.
  PERFORM %INITIALIZATION.

AT SELECTION-SCREEN OUTPUT.
  PERFORM CTRL_SCREEN.

START-OF-SELECTION.
  CALL SCREEN 100.
