*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZTIPCHEQUEMATTOP.                 " Global Data
  INCLUDE LZTIPCHEQUEMATUXX.                 " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZTIPCHEQUEMATF00                       . " subprograms
  INCLUDE LZTIPCHEQUEMATI00                       . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZTIPCHEQUEMATF...                 " Subprograms
* INCLUDE LZTIPCHEQUEMATO...                 " PBO-Modules
* INCLUDE LZTIPCHEQUEMATI...                 " PAI-Modules
