*---------------------------------------------------------------------*
*    generated viewmaintenance function pool
*---------------------------------------------------------------------*
*******************************************************************
*   System-defined Include-files.                                 *
*******************************************************************
  INCLUDE LZUNID_PRODTOP.                    " Global Data
  INCLUDE LZUNID_PRODUXX.                    " Function Modules

*******************************************************************
*   include-files generated by view maintenance tool              *
*******************************************************************

*      view related include-files   (never change, please)        *
  INCLUDE LZUNID_PRODF00                          . " subprograms
  INCLUDE LZUNID_PRODI00                          . " PAI modules

*      general include-files        (never change, please)        *
  INCLUDE LSVIMFXX                                . " subprograms
  INCLUDE LSVIMOXX                                . " PBO modules
  INCLUDE LSVIMIXX                                . " PAI modules

*******************************************************************
*   User-defined Include-files (if necessary).                    *
*******************************************************************
* INCLUDE LZUNID_PRODF...                    " Subprograms
* INCLUDE LZUNID_PRODO...                    " PBO-Modules
* INCLUDE LZUNID_PRODI...                    " PAI-Modules

INCLUDE lzunid_prodf01.
