PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZV_ITER_CC CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZV_ITER_CC-BUKRS .
    FIELD ZV_ITER_CC-HBKID .
    FIELD ZV_ITER_CC-HKTID .
    FIELD ZV_ITER_CC-SECUENCIA .
    FIELD ZV_ITER_CC-CODITER .
    FIELD ZV_ITER_CC-ORDEN .
    FIELD ZV_ITER_CC-ENABLED .
    FIELD ZV_ITER_CC-DESCRIP .
    FIELD ZV_ITER_CC-DESDE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
    MODULE COMPLETE_ZV_ITER_CC ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZV_ITER_CC-BUKRS .
    FIELD ZV_ITER_CC-HBKID .
    FIELD ZV_ITER_CC-HKTID .
    FIELD ZV_ITER_CC-SECUENCIA .
    FIELD ZV_ITER_CC-CODITER .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
