*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZV_ITER_CC......................................*
FORM GET_DATA_ZV_ITER_CC.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
* BEGIN. 07-07-2026 - ATC - ATC-03
* OLD CODE
*  SELECT * FROM ZCB_ITER_CC WHERE
*(VIM_WHERETAB) .
*
* NEW CODE
  SELECT *
 FROM ZCB_ITER_CC WHERE
(VIM_WHERETAB)  ORDER BY PRIMARY KEY.

* END. 07-07-2026 - ATC - ATC-03
    CLEAR ZV_ITER_CC .
ZV_ITER_CC-MANDT =
ZCB_ITER_CC-MANDT .
ZV_ITER_CC-BUKRS =
ZCB_ITER_CC-BUKRS .
ZV_ITER_CC-HBKID =
ZCB_ITER_CC-HBKID .
ZV_ITER_CC-HKTID =
ZCB_ITER_CC-HKTID .
ZV_ITER_CC-SECUENCIA =
ZCB_ITER_CC-SECUENCIA .
ZV_ITER_CC-CODITER =
ZCB_ITER_CC-CODITER .
ZV_ITER_CC-ORDEN =
ZCB_ITER_CC-ORDEN .
ZV_ITER_CC-ENABLED =
ZCB_ITER_CC-ENABLED .
ZV_ITER_CC-DESDE =
ZCB_ITER_CC-DESDE .
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*    SELECT SINGLE * FROM ZCB_ITER WHERE
*CODITER = ZCB_ITER_CC-CODITER .
*
* NEW CODE
    SELECT *
    UP TO 1 ROWS  FROM ZCB_ITER WHERE
CODITER = ZCB_ITER_CC-CODITER  ORDER BY PRIMARY KEY.

    ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
    IF SY-SUBRC EQ 0.
ZV_ITER_CC-DESCRIP =
ZCB_ITER-DESCRIP .
    ENDIF.
<VIM_TOTAL_STRUC> = ZV_ITER_CC.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZV_ITER_CC .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZV_ITER_CC.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZV_ITER_CC-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZCB_ITER_CC WHERE
  BUKRS = ZV_ITER_CC-BUKRS AND
  HBKID = ZV_ITER_CC-HBKID AND
  HKTID = ZV_ITER_CC-HKTID AND
  SECUENCIA = ZV_ITER_CC-SECUENCIA AND
  CODITER = ZV_ITER_CC-CODITER .
    IF SY-SUBRC = 0.
    DELETE ZCB_ITER_CC .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZCB_ITER_CC WHERE
  BUKRS = ZV_ITER_CC-BUKRS AND
  HBKID = ZV_ITER_CC-HBKID AND
  HKTID = ZV_ITER_CC-HKTID AND
  SECUENCIA = ZV_ITER_CC-SECUENCIA AND
  CODITER = ZV_ITER_CC-CODITER .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZCB_ITER_CC.
    ENDIF.
ZCB_ITER_CC-MANDT =
ZV_ITER_CC-MANDT .
ZCB_ITER_CC-BUKRS =
ZV_ITER_CC-BUKRS .
ZCB_ITER_CC-HBKID =
ZV_ITER_CC-HBKID .
ZCB_ITER_CC-HKTID =
ZV_ITER_CC-HKTID .
ZCB_ITER_CC-SECUENCIA =
ZV_ITER_CC-SECUENCIA .
ZCB_ITER_CC-CODITER =
ZV_ITER_CC-CODITER .
ZCB_ITER_CC-ORDEN =
ZV_ITER_CC-ORDEN .
ZCB_ITER_CC-ENABLED =
ZV_ITER_CC-ENABLED .
ZCB_ITER_CC-DESDE =
ZV_ITER_CC-DESDE .
    IF SY-SUBRC = 0.
    UPDATE ZCB_ITER_CC .
    ELSE.
    INSERT ZCB_ITER_CC .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZV_ITER_CC-UPD_FLAG,
STATUS_ZV_ITER_CC-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZV_ITER_CC.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE * FROM ZCB_ITER_CC WHERE
*BUKRS = ZV_ITER_CC-BUKRS AND
*HBKID = ZV_ITER_CC-HBKID AND
*HKTID = ZV_ITER_CC-HKTID AND
*SECUENCIA = ZV_ITER_CC-SECUENCIA AND
*CODITER = ZV_ITER_CC-CODITER .
*
* NEW CODE
  SELECT *
  UP TO 1 ROWS  FROM ZCB_ITER_CC WHERE
BUKRS = ZV_ITER_CC-BUKRS AND
HBKID = ZV_ITER_CC-HBKID AND
HKTID = ZV_ITER_CC-HKTID AND
SECUENCIA = ZV_ITER_CC-SECUENCIA AND
CODITER = ZV_ITER_CC-CODITER  ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
ZV_ITER_CC-MANDT =
ZCB_ITER_CC-MANDT .
ZV_ITER_CC-BUKRS =
ZCB_ITER_CC-BUKRS .
ZV_ITER_CC-HBKID =
ZCB_ITER_CC-HBKID .
ZV_ITER_CC-HKTID =
ZCB_ITER_CC-HKTID .
ZV_ITER_CC-SECUENCIA =
ZCB_ITER_CC-SECUENCIA .
ZV_ITER_CC-CODITER =
ZCB_ITER_CC-CODITER .
ZV_ITER_CC-ORDEN =
ZCB_ITER_CC-ORDEN .
ZV_ITER_CC-ENABLED =
ZCB_ITER_CC-ENABLED .
ZV_ITER_CC-DESDE =
ZCB_ITER_CC-DESDE .
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*    SELECT SINGLE * FROM ZCB_ITER WHERE
*CODITER = ZCB_ITER_CC-CODITER .
*
* NEW CODE
    SELECT *
    UP TO 1 ROWS  FROM ZCB_ITER WHERE
CODITER = ZCB_ITER_CC-CODITER  ORDER BY PRIMARY KEY.

    ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
    IF SY-SUBRC EQ 0.
ZV_ITER_CC-DESCRIP =
ZCB_ITER-DESCRIP .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZV_ITER_CC-DESCRIP .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZV_ITER_CC USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZV_ITER_CC-BUKRS TO
ZCB_ITER_CC-BUKRS .
MOVE ZV_ITER_CC-HBKID TO
ZCB_ITER_CC-HBKID .
MOVE ZV_ITER_CC-HKTID TO
ZCB_ITER_CC-HKTID .
MOVE ZV_ITER_CC-SECUENCIA TO
ZCB_ITER_CC-SECUENCIA .
MOVE ZV_ITER_CC-CODITER TO
ZCB_ITER_CC-CODITER .
MOVE ZV_ITER_CC-MANDT TO
ZCB_ITER_CC-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZCB_ITER_CC'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZCB_ITER_CC TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZCB_ITER_CC'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZV_ITER_CC USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
ZCB_ITER_CC-MANDT =
ZV_ITER_CC-MANDT .
ZCB_ITER_CC-BUKRS =
ZV_ITER_CC-BUKRS .
ZCB_ITER_CC-HBKID =
ZV_ITER_CC-HBKID .
ZCB_ITER_CC-HKTID =
ZV_ITER_CC-HKTID .
ZCB_ITER_CC-SECUENCIA =
ZV_ITER_CC-SECUENCIA .
ZCB_ITER_CC-CODITER =
ZV_ITER_CC-CODITER .
ZCB_ITER_CC-ORDEN =
ZV_ITER_CC-ORDEN .
ZCB_ITER_CC-ENABLED =
ZV_ITER_CC-ENABLED .
ZCB_ITER_CC-DESDE =
ZV_ITER_CC-DESDE .
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*    SELECT SINGLE * FROM ZCB_ITER WHERE
*CODITER = ZCB_ITER_CC-CODITER .
*
* NEW CODE
    SELECT *
    UP TO 1 ROWS  FROM ZCB_ITER WHERE
CODITER = ZCB_ITER_CC-CODITER  ORDER BY PRIMARY KEY.

    ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
    IF SY-SUBRC EQ 0.
ZV_ITER_CC-DESCRIP =
ZCB_ITER-DESCRIP .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZV_ITER_CC-DESCRIP .
    ENDIF.
ENDFORM.
