*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZV_T042.........................................*
FORM GET_DATA_ZV_T042.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM T042 WHERE
(VIM_WHERETAB) .
    CLEAR ZV_T042 .
ZV_T042-MANDT =
T042-MANDT .
ZV_T042-BUKRS =
T042-BUKRS .
ZV_T042-ZBUKR =
T042-ZBUKR .
ZV_T042-ULSK1 =
T042-ULSK1 .
ZV_T042-ULSK2 =
T042-ULSK2 .
ZV_T042-ULSD1 =
T042-ULSD1 .
ZV_T042-ULSD2 =
T042-ULSD2 .
ZV_T042-XKDFB =
T042-XKDFB .
ZV_T042-XGBTR =
T042-XGBTR .
ZV_T042-TOLTG =
T042-TOLTG .
ZV_T042-SKTUG =
T042-SKTUG .
ZV_T042-XSKR1 =
T042-XSKR1 .
ZV_T042-ABSBU =
T042-ABSBU .
ZV_T042-XUZAW =
T042-XUZAW .
ZV_T042-XBPTR =
T042-XBPTR .
    SELECT SINGLE * FROM T001 WHERE
BUKRS = T042-ZBUKR .
    IF SY-SUBRC EQ 0.
ZV_T042-BUTXT =
T001-BUTXT .
    ENDIF.
<VIM_TOTAL_STRUC> = ZV_T042.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZV_T042 .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZV_T042.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZV_T042-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM T042 WHERE
  BUKRS = ZV_T042-BUKRS .
    IF SY-SUBRC = 0.
    DELETE T042 .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM T042 WHERE
  BUKRS = ZV_T042-BUKRS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR T042.
    ENDIF.
T042-MANDT =
ZV_T042-MANDT .
T042-BUKRS =
ZV_T042-BUKRS .
T042-ZBUKR =
ZV_T042-ZBUKR .
T042-ULSK1 =
ZV_T042-ULSK1 .
T042-ULSK2 =
ZV_T042-ULSK2 .
T042-ULSD1 =
ZV_T042-ULSD1 .
T042-ULSD2 =
ZV_T042-ULSD2 .
T042-XKDFB =
ZV_T042-XKDFB .
T042-XGBTR =
ZV_T042-XGBTR .
T042-TOLTG =
ZV_T042-TOLTG .
T042-SKTUG =
ZV_T042-SKTUG .
T042-XSKR1 =
ZV_T042-XSKR1 .
T042-ABSBU =
ZV_T042-ABSBU .
T042-XUZAW =
ZV_T042-XUZAW .
T042-XBPTR =
ZV_T042-XBPTR .
    IF SY-SUBRC = 0.
    UPDATE T042 ##WARN_OK.
    ELSE.
    INSERT T042 .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZV_T042-UPD_FLAG,
STATUS_ZV_T042-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZV_T042.
  SELECT SINGLE * FROM T042 WHERE
BUKRS = ZV_T042-BUKRS .
ZV_T042-MANDT =
T042-MANDT .
ZV_T042-BUKRS =
T042-BUKRS .
ZV_T042-ZBUKR =
T042-ZBUKR .
ZV_T042-ULSK1 =
T042-ULSK1 .
ZV_T042-ULSK2 =
T042-ULSK2 .
ZV_T042-ULSD1 =
T042-ULSD1 .
ZV_T042-ULSD2 =
T042-ULSD2 .
ZV_T042-XKDFB =
T042-XKDFB .
ZV_T042-XGBTR =
T042-XGBTR .
ZV_T042-TOLTG =
T042-TOLTG .
ZV_T042-SKTUG =
T042-SKTUG .
ZV_T042-XSKR1 =
T042-XSKR1 .
ZV_T042-ABSBU =
T042-ABSBU .
ZV_T042-XUZAW =
T042-XUZAW .
ZV_T042-XBPTR =
T042-XBPTR .
    SELECT SINGLE * FROM T001 WHERE
BUKRS = T042-ZBUKR .
    IF SY-SUBRC EQ 0.
ZV_T042-BUTXT =
T001-BUTXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZV_T042-BUTXT .
    ENDIF.
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZV_T042 USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZV_T042-BUKRS TO
T042-BUKRS .
MOVE ZV_T042-MANDT TO
T042-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'T042'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN T042 TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'T042'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
FORM COMPL_ZV_T042 USING WORKAREA.
*      provides (read-only) fields from secondary tables related
*      to primary tables by foreignkey relationships
T042-MANDT =
ZV_T042-MANDT .
T042-BUKRS =
ZV_T042-BUKRS .
T042-ZBUKR =
ZV_T042-ZBUKR .
T042-ULSK1 =
ZV_T042-ULSK1 .
T042-ULSK2 =
ZV_T042-ULSK2 .
T042-ULSD1 =
ZV_T042-ULSD1 .
T042-ULSD2 =
ZV_T042-ULSD2 .
T042-XKDFB =
ZV_T042-XKDFB .
T042-XGBTR =
ZV_T042-XGBTR .
T042-TOLTG =
ZV_T042-TOLTG .
T042-SKTUG =
ZV_T042-SKTUG .
T042-XSKR1 =
ZV_T042-XSKR1 .
T042-ABSBU =
ZV_T042-ABSBU .
T042-XUZAW =
ZV_T042-XUZAW .
T042-XBPTR =
ZV_T042-XBPTR .
    SELECT SINGLE * FROM T001 WHERE
BUKRS = T042-ZBUKR .
    IF SY-SUBRC EQ 0.
ZV_T042-BUTXT =
T001-BUTXT .
    ELSE.
      CLEAR SY-SUBRC.
      CLEAR ZV_T042-BUTXT .
    ENDIF.
ENDFORM.

* base table related FORM-routines.............
INCLUDE LSVIMFTX .
