*---------------------------------------------------------------------*
*    view related FORM routines
*---------------------------------------------------------------------*
*...processing: ZVFI_REGUH......................................*
FORM GET_DATA_ZVFI_REGUH.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
* BEGIN. 07-07-2026 - ATC - ATC-03
* OLD CODE
*  SELECT * FROM REGUH WHERE
*(VIM_WHERETAB) .
*
* NEW CODE
  SELECT *
 FROM REGUH WHERE
(VIM_WHERETAB)  ORDER BY PRIMARY KEY.

* END. 07-07-2026 - ATC - ATC-03
    CLEAR ZVFI_REGUH .
ZVFI_REGUH-MANDT =
REGUH-MANDT .
ZVFI_REGUH-LAUFD =
REGUH-LAUFD .
ZVFI_REGUH-LAUFI =
REGUH-LAUFI .
ZVFI_REGUH-XVORL =
REGUH-XVORL .
ZVFI_REGUH-ZBUKR =
REGUH-ZBUKR .
ZVFI_REGUH-LIFNR =
REGUH-LIFNR .
ZVFI_REGUH-KUNNR =
REGUH-KUNNR .
ZVFI_REGUH-EMPFG =
REGUH-EMPFG .
ZVFI_REGUH-VBLNR =
REGUH-VBLNR .
ZVFI_REGUH-IDENTIF_PAGO =
REGUH-IDENTIF_PAGO .
ZVFI_REGUH-IND_PAGO =
REGUH-IND_PAGO .
ZVFI_REGUH-FECHA_PAGO =
REGUH-FECHA_PAGO .
ZVFI_REGUH-IND_DEVUELTO =
REGUH-IND_DEVUELTO .
ZVFI_REGUH-FECHA_DEVUELTO =
REGUH-FECHA_DEVUELTO .
ZVFI_REGUH-IND_RECHAZO =
REGUH-IND_RECHAZO .
ZVFI_REGUH-FECHA_RECHAZO =
REGUH-FECHA_RECHAZO .
ZVFI_REGUH-BELNR_DEV =
REGUH-BELNR_DEV .
ZVFI_REGUH-GJAHR_DEV =
REGUH-GJAHR_DEV .
ZVFI_REGUH-IND_CUSTODIA =
REGUH-IND_CUSTODIA .
ZVFI_REGUH-FECHA_CUSTODIA =
REGUH-FECHA_CUSTODIA .
ZVFI_REGUH-MOTIVO_RECHAZO =
REGUH-MOTIVO_RECHAZO .
ZVFI_REGUH-IND_ENTREGADO =
REGUH-IND_ENTREGADO .
ZVFI_REGUH-FECHA_ENTREGADO =
REGUH-FECHA_ENTREGADO .
ZVFI_REGUH-IND_RESCATADO =
REGUH-IND_RESCATADO .
ZVFI_REGUH-FECHA_RESCATADO =
REGUH-FECHA_RESCATADO .
ZVFI_REGUH-IND_REDEPO =
REGUH-IND_REDEPO .
ZVFI_REGUH-FECHA_REDEPO =
REGUH-FECHA_REDEPO .
ZVFI_REGUH-GLOSA_REDEPO =
REGUH-GLOSA_REDEPO .
<VIM_TOTAL_STRUC> = ZVFI_REGUH.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZVFI_REGUH .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZVFI_REGUH.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZVFI_REGUH-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM REGUH WHERE
  LAUFD = ZVFI_REGUH-LAUFD AND
  LAUFI = ZVFI_REGUH-LAUFI AND
  XVORL = ZVFI_REGUH-XVORL AND
  ZBUKR = ZVFI_REGUH-ZBUKR AND
  LIFNR = ZVFI_REGUH-LIFNR AND
  KUNNR = ZVFI_REGUH-KUNNR AND
  EMPFG = ZVFI_REGUH-EMPFG AND
  VBLNR = ZVFI_REGUH-VBLNR .
    IF SY-SUBRC = 0.
    DELETE REGUH .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM REGUH WHERE
  LAUFD = ZVFI_REGUH-LAUFD AND
  LAUFI = ZVFI_REGUH-LAUFI AND
  XVORL = ZVFI_REGUH-XVORL AND
  ZBUKR = ZVFI_REGUH-ZBUKR AND
  LIFNR = ZVFI_REGUH-LIFNR AND
  KUNNR = ZVFI_REGUH-KUNNR AND
  EMPFG = ZVFI_REGUH-EMPFG AND
  VBLNR = ZVFI_REGUH-VBLNR .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR REGUH.
    ENDIF.
REGUH-MANDT =
ZVFI_REGUH-MANDT .
REGUH-LAUFD =
ZVFI_REGUH-LAUFD .
REGUH-LAUFI =
ZVFI_REGUH-LAUFI .
REGUH-XVORL =
ZVFI_REGUH-XVORL .
REGUH-ZBUKR =
ZVFI_REGUH-ZBUKR .
REGUH-LIFNR =
ZVFI_REGUH-LIFNR .
REGUH-KUNNR =
ZVFI_REGUH-KUNNR .
REGUH-EMPFG =
ZVFI_REGUH-EMPFG .
REGUH-VBLNR =
ZVFI_REGUH-VBLNR .
REGUH-IDENTIF_PAGO =
ZVFI_REGUH-IDENTIF_PAGO .
REGUH-IND_PAGO =
ZVFI_REGUH-IND_PAGO .
REGUH-FECHA_PAGO =
ZVFI_REGUH-FECHA_PAGO .
REGUH-IND_DEVUELTO =
ZVFI_REGUH-IND_DEVUELTO .
REGUH-FECHA_DEVUELTO =
ZVFI_REGUH-FECHA_DEVUELTO .
REGUH-IND_RECHAZO =
ZVFI_REGUH-IND_RECHAZO .
REGUH-FECHA_RECHAZO =
ZVFI_REGUH-FECHA_RECHAZO .
REGUH-BELNR_DEV =
ZVFI_REGUH-BELNR_DEV .
REGUH-GJAHR_DEV =
ZVFI_REGUH-GJAHR_DEV .
REGUH-IND_CUSTODIA =
ZVFI_REGUH-IND_CUSTODIA .
REGUH-FECHA_CUSTODIA =
ZVFI_REGUH-FECHA_CUSTODIA .
REGUH-MOTIVO_RECHAZO =
ZVFI_REGUH-MOTIVO_RECHAZO .
REGUH-IND_ENTREGADO =
ZVFI_REGUH-IND_ENTREGADO .
REGUH-FECHA_ENTREGADO =
ZVFI_REGUH-FECHA_ENTREGADO .
REGUH-IND_RESCATADO =
ZVFI_REGUH-IND_RESCATADO .
REGUH-FECHA_RESCATADO =
ZVFI_REGUH-FECHA_RESCATADO .
REGUH-IND_REDEPO =
ZVFI_REGUH-IND_REDEPO .
REGUH-FECHA_REDEPO =
ZVFI_REGUH-FECHA_REDEPO .
REGUH-GLOSA_REDEPO =
ZVFI_REGUH-GLOSA_REDEPO .
    IF SY-SUBRC = 0.
    UPDATE REGUH ##WARN_OK.
    ELSE.
    INSERT REGUH .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZVFI_REGUH-UPD_FLAG,
STATUS_ZVFI_REGUH-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ENTRY_ZVFI_REGUH.
* BEGIN. 07-07-2026 - ATC - ATC-01
* OLD CODE
*  SELECT SINGLE * FROM REGUH WHERE
*LAUFD = ZVFI_REGUH-LAUFD AND
*LAUFI = ZVFI_REGUH-LAUFI AND
*XVORL = ZVFI_REGUH-XVORL AND
*ZBUKR = ZVFI_REGUH-ZBUKR AND
*LIFNR = ZVFI_REGUH-LIFNR AND
*KUNNR = ZVFI_REGUH-KUNNR AND
*EMPFG = ZVFI_REGUH-EMPFG AND
*VBLNR = ZVFI_REGUH-VBLNR .
*
* NEW CODE
  SELECT *
  UP TO 1 ROWS  FROM REGUH WHERE
LAUFD = ZVFI_REGUH-LAUFD AND
LAUFI = ZVFI_REGUH-LAUFI AND
XVORL = ZVFI_REGUH-XVORL AND
ZBUKR = ZVFI_REGUH-ZBUKR AND
LIFNR = ZVFI_REGUH-LIFNR AND
KUNNR = ZVFI_REGUH-KUNNR AND
EMPFG = ZVFI_REGUH-EMPFG AND
VBLNR = ZVFI_REGUH-VBLNR  ORDER BY PRIMARY KEY.

  ENDSELECT.
* END. 07-07-2026 - ATC - ATC-01
ZVFI_REGUH-MANDT =
REGUH-MANDT .
ZVFI_REGUH-LAUFD =
REGUH-LAUFD .
ZVFI_REGUH-LAUFI =
REGUH-LAUFI .
ZVFI_REGUH-XVORL =
REGUH-XVORL .
ZVFI_REGUH-ZBUKR =
REGUH-ZBUKR .
ZVFI_REGUH-LIFNR =
REGUH-LIFNR .
ZVFI_REGUH-KUNNR =
REGUH-KUNNR .
ZVFI_REGUH-EMPFG =
REGUH-EMPFG .
ZVFI_REGUH-VBLNR =
REGUH-VBLNR .
ZVFI_REGUH-IDENTIF_PAGO =
REGUH-IDENTIF_PAGO .
ZVFI_REGUH-IND_PAGO =
REGUH-IND_PAGO .
ZVFI_REGUH-FECHA_PAGO =
REGUH-FECHA_PAGO .
ZVFI_REGUH-IND_DEVUELTO =
REGUH-IND_DEVUELTO .
ZVFI_REGUH-FECHA_DEVUELTO =
REGUH-FECHA_DEVUELTO .
ZVFI_REGUH-IND_RECHAZO =
REGUH-IND_RECHAZO .
ZVFI_REGUH-FECHA_RECHAZO =
REGUH-FECHA_RECHAZO .
ZVFI_REGUH-BELNR_DEV =
REGUH-BELNR_DEV .
ZVFI_REGUH-GJAHR_DEV =
REGUH-GJAHR_DEV .
ZVFI_REGUH-IND_CUSTODIA =
REGUH-IND_CUSTODIA .
ZVFI_REGUH-FECHA_CUSTODIA =
REGUH-FECHA_CUSTODIA .
ZVFI_REGUH-MOTIVO_RECHAZO =
REGUH-MOTIVO_RECHAZO .
ZVFI_REGUH-IND_ENTREGADO =
REGUH-IND_ENTREGADO .
ZVFI_REGUH-FECHA_ENTREGADO =
REGUH-FECHA_ENTREGADO .
ZVFI_REGUH-IND_RESCATADO =
REGUH-IND_RESCATADO .
ZVFI_REGUH-FECHA_RESCATADO =
REGUH-FECHA_RESCATADO .
ZVFI_REGUH-IND_REDEPO =
REGUH-IND_REDEPO .
ZVFI_REGUH-FECHA_REDEPO =
REGUH-FECHA_REDEPO .
ZVFI_REGUH-GLOSA_REDEPO =
REGUH-GLOSA_REDEPO .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZVFI_REGUH USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZVFI_REGUH-LAUFD TO
REGUH-LAUFD .
MOVE ZVFI_REGUH-LAUFI TO
REGUH-LAUFI .
MOVE ZVFI_REGUH-XVORL TO
REGUH-XVORL .
MOVE ZVFI_REGUH-ZBUKR TO
REGUH-ZBUKR .
MOVE ZVFI_REGUH-LIFNR TO
REGUH-LIFNR .
MOVE ZVFI_REGUH-KUNNR TO
REGUH-KUNNR .
MOVE ZVFI_REGUH-EMPFG TO
REGUH-EMPFG .
MOVE ZVFI_REGUH-VBLNR TO
REGUH-VBLNR .
MOVE ZVFI_REGUH-MANDT TO
REGUH-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'REGUH'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN REGUH TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'REGUH'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
